// AUTO-GENERATED by tools/dlg-compile.py from a .dlg source — do not edit by hand.
// Re-generate with: python3 tools/dlg-compile.py
using UnityEngine;
using SunderedCrown.Dialogue;
using SunderedCrown.Stats;

namespace SunderedCrown.Content
{
    public class CandlekeepDenizensThreeContent
    {
        public DialogueGraph NpcKeepRevenantDialogue { get; private set; }
        public DialogueGraph NpcKeepCatDialogue { get; private set; }
        public DialogueGraph NpcKeepPolDialogue { get; private set; }

        public CandlekeepDenizensThreeContent()
        {
            BuildNpcKeepRevenantDialogue();
            BuildNpcKeepCatDialogue();
            BuildNpcKeepPolDialogue();
        }

        private void BuildNpcKeepRevenantDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.keep.revenant";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "A Voice From the Margins",
                text = "*(The sealed stacks are walled in iron and silence. Behind the grate, something that was once a person — paper-thin, ink-dark, more marginalia than man — turns its eyeless face toward you and *recognizes* you, the way one mirror recognizes another.)* ...You're warm. *(a sound like a page turning underwater.)* You're *warm*, and you came *down here*, which means you've started reading the margins. Good. I wrote them. *(the thing presses a hand of dried vellum to the grate.)* I am what's left of the one who came before you, Returned. I walked the road you're walking. I reached the Court of the Dead. And I am *here* now — sealed in the stacks, indexed under *Cautionary* — because I made the choice you are about to be offered, and it was the *wrong* one.",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.revenant_met", op = FlagOp.SetTrue }, new FlagClause { key = "act2.predecessor_found", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "The Sealed-Stacks Revenant",
                text = "*(It speaks faster now, as if afraid it will be reshelved mid-sentence.)* Listen — they don't seal you for *failing.* Failing's easy, failing just kills you and the loop starts fresh with a new fool. They seal you for *almost winning the wrong way.* *(the vellum hand trembles.)* I stood before the Wall. I was *offered the crown* — the Crown of Horns, the authority over the dead, the power to *re-sort* every soul by my own better judgment. And I took it. I thought: *I* will be the merciful sorter. *I* will judge rightly where the gods judged cruelly. *(a sound of terrible grief.)* And the moment I wore it, Returned, I *became the Wall.* A kinder Wall. A Wall that *agonized.* But a Wall. Because the crown doesn't let you *end* the sorting — it only lets you *do it better*, forever, and *better forever* is still *forever.* They sealed me here so the next Returned could *read what I learned* before reaching for the same bright ruin. *Don't take the crown.* Whatever else you do. The crown is the trap that looks like the answer.",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 18] \"You didn't fail and you didn't win. You're a *warning the system files on purpose*. The Wall *keeps* a cautionary predecessor so each Returned arrives pre-discouraged. You're bait, and you know it.\"", nextNodeId = "bait", checkAbility = Ability.Wisdom, checkDC = 18, failNodeId = "grieve" },
                    new DialogueChoice { text = "\"If not the crown, then what? You walked further than anyone. Tell me the road past the place you fell.\"", nextNodeId = "road" },
                    new DialogueChoice { text = "\"Give me the margins. All of them. Every note you scratched. I'll read what it cost you to learn.\"", nextNodeId = "margins", effects = new[] { new FlagClause { key = "sq.read_the_margins", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 3 } } },
                    new DialogueChoice { text = "\"You wore it and you *agonized*. That's not nothing. A Wall that grieves is one crack from a Wall that *stops*.\"", nextNodeId = "grieve" },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "bait", speaker = "The Sealed-Stacks Revenant",
                text = "*(The eyeless face goes very still.)* ...Bait. *(the page-turn sound, slow.)* You read *that* in the margins too, then. The note I almost scratched out. *(quietly.)* Yes. I worked it out in my third decade behind this grate. They didn't seal me to *warn* you — warning me would mean they *want* you to win, and they do not. They sealed me because a Returned who meets a *broken predecessor* arrives at the Wall already half-convinced it can't be done. *(a sound like dry laughter.)* I am *demoralization*, indexed and shelved. The most efficient thing the Wall ever did was keep one of us *alive enough to despair at.* *(the vellum hand flattens on the grate, and its voice changes — fierce, freed.)* But here is the thing they didn't count on, Returned: *a piece of bait that knows it's bait can change what it says.* I was *meant* to tell you it's hopeless. *(slowly.)* I'm telling you instead: it can be done. Just *not with the crown.* I've spent forty years rewriting my own warning into a *map.* Read the margins. I turned the trap into directions while they thought I was just decaying.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.revenant_is_bait", op = FlagOp.SetTrue }, new FlagClause { key = "sq.read_the_margins", op = FlagOp.SetTrue }, new FlagClause { key = "act2.predecessor_freed", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "road", speaker = "The Sealed-Stacks Revenant",
                text = "*(It is quiet a long moment, gathering the most expensive thing it knows.)* The road past the crown. *(softly.)* I only glimpsed it, in the half-second before I reached for the bright thing instead. *(the vellum hand traces a shape on the grate.)* The crown offers you *authority over* the dead — to sort them *better.* But there is another thing in that room, Returned, smaller, dimmer, almost hidden behind the crown's glare. *(quietly.)* It is the authority to *un-make the office entirely.* To not be a *better* sorter but the *last* one. To take the crown and *break* it, knowing that breaking it strips you of every power it offered — that you save the dead by making yourself *unable to rule them*, which means you cannot protect them after, which means you must *trust* what comes when no one sorts at all. *(a sound of unbearable longing.)* I couldn't do it. The crown was *certain* and the breaking was a *leap into dark.* I chose certainty. That's why I'm shelved. *(fiercely.)* You take the leap. Promise a dead thing behind a grate that *you'll take the leap.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.revenant_the_road", op = FlagOp.SetTrue }, new FlagClause { key = "act2.break_the_crown_known", op = FlagOp.SetTrue }, new FlagClause { key = "prologue.crack_seeded", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "margins", speaker = "The Sealed-Stacks Revenant",
                text = "*(Relief floods the paper-thin face.)* Yes — *yes* — take them, read them, they're scratched in every cautionary volume in this stack, forty years of a dead fool's working-out. *(the vellum hand sketches frantically.)* The notes will tell you which gods *quit* and which still *care*; which faces at the Court can be *turned* and which are only painted on; the *exact* words the Wall uses to make taking the crown feel like *mercy.* *(quietly.)* I wrote them for you, you understand. Not for *me* — I was already lost when I started scratching. I wrote them the way a man falling down a well carves handholds *below* himself, for whoever falls next. *(its voice softens to almost nothing.)* That's the only afterlife I get, Returned. Not the crown. Not rest. Just the chance that my *forty years of failing usefully* become the reason *you* don't fail. Read the margins. Make me worth the shelving.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.revenant_gives_margins", op = FlagOp.SetTrue }, new FlagClause { key = "sq.read_the_margins", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "grieve", speaker = "The Sealed-Stacks Revenant",
                text = "*(The eyeless face turns away, and the silence stretches.)* A Wall that grieves. *(barely audible.)* I *did* grieve. Every soul I re-sorted, even mercifully, even *weeping* — I felt each one. I thought the grief *redeemed* the office. *(a sound of ash.)* It does not. Grief that *continues the thing it grieves* is just *suffering with good manners*, Returned. The dead I sorted kindly were *still sorted.* My tears changed the *temperature* of the Wall, not its *function.* *(it faces you again, and the warning is total.)* Do not mistake *feeling bad about a cruelty* for *ending* it. The crown will *let* you grieve — will *encourage* it, because a grieving sorter is a *committed* sorter, one who'll never quit because quitting would *waste* all that beautiful pain. *(quietly.)* My grief is the chain. Don't pick up a crown that runs on tears. *Yours* would be just as bright, and just as binding.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.revenant_grief_warning", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "The Sealed-Stacks Revenant",
                text = "*(The thing behind the grate settles back into the dark of the sealed stacks — half man, half marginalia, the indexed warning that learned to rewrite itself into a map — and you climb back toward the lamplight carrying the one piece of knowledge the whole library was built to keep from you: that the crown at the end of the road is the *trap*, not the prize, and the one who came before you spent forty years of decay making certain you'd know it.)*",
            });

            NpcKeepRevenantDialogue = g;
        }

        private void BuildNpcKeepCatDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.keep.cat";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "A Grey Cat on a Closed Book",
                text = "*(A large grey cat sits with deliberate, possessive weight upon a single closed volume, regarding you with the flat patience of a creature that has watched a great many warm things come and go. As you near, it does not run. It *blinks*, slowly, which from a cat is either a benediction or an appraisal, and you feel — absurdly, certainly — that it has *decided something* about you.)*",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.cat_met", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "The Cat Who Reads",
                text = "*(The cat does not speak — cats don't — but its eyes track yours, and it shifts, very slightly, so the title of the book beneath it shows for one heartbeat before its paw covers it again. It is the book. The dangerous one. The one you came for. And the cat is *sitting on it*, watching you understand, entirely unhurried.)* *(A monk passes, murmurs:)* \"Don't mind Margin. She's the oldest thing in Candlekeep — older than the First Reader, some say. Animals aren't *judged*, you see, never sorted, so she's the one creature here that simply... goes *on.* She's watched every reader who ever opened *that* book.\" *(the monk lowers his voice.)* \"And she sits on it now because the last one who read it died at this table. She sat with the body three days before anyone came. She *liked* him.\"",
                choices = new[]
                {
                    new DialogueChoice { text = "[SPEAK-WITH-ANIMALS] \"*(crouch, meet the cat's eyes, and speak the small magic that lets you hear her)* Margin. May I read your book?\"", nextNodeId = "speak" },
                    new DialogueChoice { text = "[HANDLE-ANIMAL 15] \"*(slow blink back; offer the back of your hand; let her decide if you're worth the book)*\"", nextNodeId = "earn", failNodeId = "hiss" },
                    new DialogueChoice { text = "\"*(reach, carefully, for the book beneath her)*\"", nextNodeId = "grab" },
                    new DialogueChoice { text = "\"Three days with the body. I'm sorry, Margin. He must have been kind.\"", nextNodeId = "mourn", effects = new[] { new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 2 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "speak", speaker = "The Cat Who Reads",
                text = "*(The magic catches, and the cat's regard arrives in your mind not as words but as *weights* — pressures of meaning, ancient and dry and grieving.)* *You are warm and you will go cold. They all go cold. I sit on the cold ones until someone comes.* *(she does not move from the book.)* *This one killed the last warm thing that opened it. Not the book. The* knowing *in it. He read what it said and his heart could not hold the size of it and it stopped.* *(her tail curls.)* *I have watched ten thousand readers. I cannot read. I do not need to. I know which books make the warm things go cold, and I sit on those, because I am the only one here who* remembers each of them *and the library only remembers the* books. *(slowly, she rises, and steps off the volume.)* *You may read it. You have the smell of a thing already half-cold — it cannot kill you the way it killed him; you are past the place where knowing stops a heart.* *(she watches you, ancient.)* *But sit when you read it. So that when you are cold, you will already be where I can reach you.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.cat_speaks", op = FlagOp.SetTrue }, new FlagClause { key = "sq.dangerous_book_access", op = FlagOp.SetTrue }, new FlagClause { key = "act2.the_book_known", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 3 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "earn", speaker = "The Cat Who Reads",
                text = "*(She considers your hand with the gravity of a magistrate. A long moment. Then she leans, and presses the side of her face — once, deliberately — against your knuckles, marking you as a thing she has chosen to allow. She steps off the book.)* *(The passing monk stops dead.)* \"...She *moved.* For *you.* In sixty years I have seen her step off that book for exactly no one. She sits on it because she decides who's *ready*, and she has decided *no one* was ready, ever, until — \" *(he stares at you.)* \"What *are* you?\" *(The cat, for her part, has already returned to washing one paw, her work of judgment concluded. The book is yours to read. Her permission, you understand, is the only ward Candlekeep ever truly trusted.)*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.cat_allows", op = FlagOp.SetTrue }, new FlagClause { key = "sq.dangerous_book_access", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "grab", speaker = "The Cat Who Reads",
                text = "*(Your fingers reach the book's edge — and the cat does not hiss, does not scratch, merely *looks*, and the look is so old and so unsurprised and so *disappointed* that your hand stops on its own. The monk hisses a warning too late.)* \"Don't — the ones who *take* it instead of *ask*, that's — that's how the *last* one started, he grabbed it off her too, and three days later — \" *(The cat steps off the book of her own accord, having made her point: she was never the lock. She was the *warning.* She lets you take it. She simply wants you to know she let the last warm thing take it too, and sat with him after.)*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.cat_disappointed", op = FlagOp.SetTrue }, new FlagClause { key = "sq.dangerous_book_access", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "mourn", speaker = "The Cat Who Reads",
                text = "*(The cat goes still under your soft words. Then — slowly, the way a very old creature does anything — she rises, turns three times, and settles again, but this time facing *you*, the book half-uncovered between her paws like an offering she hasn't decided to give. Her purr starts: a low, dust-dry sound, the sound of the one mourner in a library that does not mourn.)* *(The monk whispers:)* \"She's *purring.* She purrs for the dead, mostly. For *him*, when she thinks no one's near. I think — I think she's deciding you're someone she'll have to sit with, someday. That's how she loves things. By agreeing, in advance, to keep their bodies company.\" *(The cat blinks at you, slow and final, and nudges the book a half-inch closer.)*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.cat_mourns", op = FlagOp.SetTrue }, new FlagClause { key = "sq.dangerous_book_access", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 3 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "hiss", speaker = "The Cat Who Reads",
                text = "*(You move too fast, or want it too plainly, and the cat flows backward onto the book with a single warning sound — not anger, just *no* — and settles immovably, eyes half-lidded, having reclassified you as Not Yet. The monk winces.)* \"Ah. She's decided you're not ready. She's never wrong about that, I'm afraid. Come back when you've... I don't know. *Changed.* She'll know before you do.\" *(The cat begins, pointedly, to wash, the audience concluded.)*",
                autoNextNodeId = "close",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "The Cat Who Reads",
                text = "*(The grey cat resumes her vigil on the dangerous book — the oldest unjudged thing in Candlekeep, the one mourner in the house of memory, who guards the lore not with claws but with the simple, devastating fact that she remembers every reader the books forgot, and intends to sit with each of them when they go cold.)*",
            });

            NpcKeepCatDialogue = g;
        }

        private void BuildNpcKeepPolDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.keep.pol";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "Scrivener Pol",
                text = "*(A young copyist in a back alcove, ink to the elbows, who startles so violently at your approach that he knocks a candle and catches it mid-fall with the reflexes of a man who lives expecting to be caught.)* I'm not — this isn't — *(he sees you're no monk, and the panic curdles into wary calculation.)* ...You're the Returned. The one everyone's whispering about. *(he glances down the corridor, then back, lowering his voice to a thread.)* Then you'll want what I sell. Forbidden pages. Copied clean, no questions, half what a fence would charge — the things Candlekeep *seals* and pretends it doesn't have. *(his hands shake.)* I need the coin. Don't ask why. Everyone asks why. Just — do you want the pages or not?",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.pol_met", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "Scrivener Pol",
                text = "*(He doesn't wait for an answer — terror makes him talk.)* I started two years ago. My sister's debt — the bad kind, the kind with men who *visit.* And I'm a *copyist*, it's the one thing I have, so I started copying the sealed pages by candlelight and selling them, and it *worked*, it paid the men, and I told myself I wasn't *reading* them, just *copying*, just letters, just *shapes.* *(his voice cracks.)* But you can't copy ten thousand words without *some* of them getting *in*, and the things they sealed, Returned — the things Candlekeep decided no one should read — *they're not dangerous spells.* Most of them. They're *true things.* About the Wall. About the Faithless. About what the gods *quietly stopped doing.* *(he stares at his ink-black hands.)* I'm a frightened man copying out the truth for coin, and somewhere in the last two years I *started believing it*, and now I can't stop copying because *someone has to be leaking this*, and I am going to *die* for pages I only meant to *sell.*",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 16] \"You're not a smuggler anymore, Pol. You're a *whistleblower* who hasn't admitted it. The coin stopped being the reason a while ago. You copy them now because they're *true.*\"", nextNodeId = "whistleblower", checkAbility = Ability.Wisdom, checkDC = 16, failNodeId = "deny" },
                    new DialogueChoice { text = "[PERSUADE 15] \"Then leak them *properly.* Not one page to one buyer — *all* of them, copied wide, nailed where the city reads. Make the dying *count* for something more than your sister's debt.\"", nextNodeId = "leak", checkAbility = Ability.Charisma, checkDC = 15, failNodeId = "scared" },
                    new DialogueChoice { text = "\"Your sister's debt. Tell me the number. Maybe the leaking and the paying don't have to be the same desperate thing.\"", nextNodeId = "sister", effects = new[] { new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 2 } } },
                    new DialogueChoice { text = "\"Give me the pages. The true ones. I'll carry the truth where it does more than pay a debt.\"", nextNodeId = "pages", effects = new[] { new FlagClause { key = "sq.pol_pages", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 2 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "whistleblower", speaker = "Scrivener Pol",
                text = "*(He goes white, then very still, the word landing like a verdict he's been avoiding.)* A whistleblower. *(quietly.)* ...That's — no. No, I'm a *copyist*, I sell *pages*, I'm not *brave*, I'm not some — *(he stops, because his own hands betray him: they're still copying, even now, even talking to you, the pen moving on its own.)* ...Gods. Look at them. My hands kept *going.* *(he sets the pen down with effort.)* You're right. The coin stopped mattering months ago — my sister's debt's been *paid* since winter, Returned. *Paid.* And I *kept copying.* I told myself it was habit, momentum, fear of stopping — but I kept copying the sealed truth after the reason ran out *because someone has to and I'm the one with the ink.* *(he laughs, terrified and amazed at himself.)* I'm a whistleblower. I've been one since winter and too scared to know it. *(he meets your eyes.)* That's worse. That's so much worse. A smuggler can *stop.* A man who copies the truth because it's *true* can't, and they hang men for that here, and I — *(steadying)* — and I'm going to keep doing it anyway. Help me do it *right*, before doing it *frightened* gets me killed for nothing.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.pol_whistleblower", op = FlagOp.SetTrue }, new FlagClause { key = "sq.pol_pages", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "leak", speaker = "Scrivener Pol",
                text = "*(The fear and the longing war in his face — and the longing, barely, wins.)* All of them. Copied wide. Nailed where the city reads. *(he breathes like a man stepping off a ledge.)* I've *dreamed* it. Lying awake, I've *composed* it — which presses, which nights the watch is thin, which walls the most eyes pass. I know *exactly* how to leak the sealed truth across the whole Gate in a single night, Returned. I've planned my own gallows in *detail*, because the planning was the only way to make the fear hold *still.* *(he grips a sheaf of pages.)* And I never *did* it, because doing it alone is just a quick way to hang. But you — *(hope, naked and dangerous)* — *you* could be the hands that carry, while I'm the hands that *copy.* I make the truth, you *spread* it, and maybe neither of us hangs because neither of us did the whole crime alone. *(fiercely, terrified, alive.)* Yes. *Yes.* Let's leak the lot. Let's make Candlekeep's sealed shame into the thing the whole city reads over breakfast. I've been ready for a year. I just needed someone to be ready *with.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.pol_leaks", op = FlagOp.SetTrue }, new FlagClause { key = "sq.pol_pages", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "sister", speaker = "Scrivener Pol",
                text = "*(He blinks, thrown by the kindness.)* The number. *(quietly.)* It's — it's *paid*, actually. Since winter. *(he looks away, ashamed.)* I don't tell buyers that. They like the story — *the desperate boy, the sister, the debt* — it makes them feel they're *helping* when they buy. The truth's less flattering: the debt's been gone for months and I *kept selling*, and I let everyone think I was still desperate because *desperate* is easier to forgive than *committed.* *(he meets your eyes, and the calculation drops away entirely.)* My sister's fine. She's *married*, if you can believe it, to a chandler in the Lower City, she doesn't even know what I do. *(softly.)* So you've caught me, Returned. The debt's not why anymore. Hasn't been for a while. The why now is just... the pages are *true*, and someone has to be the one who *won't stop copying them.* I'd rather you knew that than the sister story. You asked straight. That's worth a straight answer, even a damning one.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.pol_honest", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 3 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "pages", speaker = "Scrivener Pol",
                text = "*(He hesitates — then presses a thick, ink-fresh sheaf into your hands, and the relief of *giving it to someone* nearly buckles him.)* The true ones. Not the spell-pages buyers want — these. *(he taps them.)* What the gods stopped doing and when. Which Reader sealed which truth and the *date* they did it. The Wall's own provenance, copied from the volume they pretend burned. *(his hands won't quite let go, then do.)* I've been *hoarding* these — too scared to sell the *real* dynamite, only the titillating stuff — telling myself I was *saving* them for the right hands. *(he laughs, wet.)* I think I was just saving them for someone who'd carry them somewhere *better* than a buyer's pocket. *(he wipes his eyes, smearing ink.)* Take them where they *do* something, Returned. I copied the truth for two years and never once got to see it *land.* Be the place it lands. That's — that's all a copyist ever wants, really. To have copied something that *mattered* to a hand that *used* it.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.pol_gives_pages", op = FlagOp.SetTrue }, new FlagClause { key = "sq.pol_pages", op = FlagOp.SetTrue }, new FlagClause { key = "act2.wall_provenance_pages", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 3 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "deny", speaker = "Scrivener Pol",
                text = "*(He shakes his head fast, retreating into the safer story.)* Whistleblower — no, no, I'm a *businessman*, I sell *pages*, it's *commerce*, don't — don't make it *grand*, grand things get *hanged.* *(he gathers his sheaf protectively.)* It's the *debt.* It's *always* been the debt. If you want pages, the price is the price. If you want to make me into some — some *hero* — find another copyist. I just want the coin and to not be *noticed.* *(he won't meet your eyes, and you both know the denial is the most frightened thing he's said.)*",
                autoNextNodeId = "close",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "scared", speaker = "Scrivener Pol",
                text = "*(The plan terrifies him back into his hole.)* Nailed across the *whole Gate* — no, no, that's — that's a *gallows*, that's not a *leak* that's a *confession with my name on it* — *(he's shaking.)* I copy in the *dark*, Returned, one page to one buyer, *small*, *quiet*, *survivable.* What you're describing is *loud*, and loud men *hang.* *(he hunches over his work.)* Buy a page if you want a page. But don't ask me to die *spectacularly* for a truth that'll get nailed over by noon. I haven't the *spine* for the version you're selling. I'm sorry. I'm only as brave as the dark allows.",
                autoNextNodeId = "close",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "Scrivener Pol",
                text = "*(Whatever you leave him with, Scrivener Pol bends back over his sealed pages, pen moving in the candlelight — a frightened man copying out the truth long after the coin stopped being the reason, becoming, one trembling letter at a time, the thing Candlekeep most fears and most needs: a hand that won't stop writing down what the library decided no one should read.)*",
            });

            NpcKeepPolDialogue = g;
        }
    }
}
