// AUTO-GENERATED by tools/dlg-compile.py from a .dlg source — do not edit by hand.
// Re-generate with: python3 tools/dlg-compile.py
using UnityEngine;
using SunderedCrown.Dialogue;
using SunderedCrown.Stats;

namespace SunderedCrown.Content
{
    public class ConnectiveDenizensTwoContent
    {
        public DialogueGraph NpcAnyGravetenderDialogue { get; private set; }
        public DialogueGraph NpcAnyListkeeperDialogue { get; private set; }
        public DialogueGraph NpcAnyPriorloopDialogue { get; private set; }

        public ConnectiveDenizensTwoContent()
        {
            BuildNpcAnyGravetenderDialogue();
            BuildNpcAnyListkeeperDialogue();
            BuildNpcAnyPriorloopDialogue();
        }

        private void BuildNpcAnyGravetenderDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.any.gravetender";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "A Grave-Tender at Their Work",
                text = "*(In a corner of whatever era you've reached, someone is doing a familiar thing: digging graves for the unclaimed dead, washing the bodies no one else will touch, speaking a few quiet words over each before the earth takes them. The face is a stranger's. The *work* is not — it is, exactly, line for line, the work your companion Garrow does, the vocation he carries like a wound and a calling both. The grave-tender straightens, wipes their hands, and nods to you with the unsurprised calm of someone whom death has made unflinchable.)* You've the look of someone who knows this work. *(quietly.)* Few do. Fewer *stay* to watch it done. Come to help, or come to ask why a person spends their one life tending the dead nobody wanted? Either's welcome. The dead don't mind an audience. They're past minding much.",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.gravetender_met", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "The Grave-Tender",
                text = "*(They return to the work as they speak, hands sure and gentle with the unclaimed dead.)* Somebody's always got to do it. *(they wash a stranger's hands, fold them.)* In every town I've ever heard of, every age the histories tell — there's *always* one. The grave-tender. The corpse-washer. The one who *stays* when the family's fled or the soul had *no* family, and makes sure the *forgotten* go into the ground *clean*, and *named* if a name can be found, and *spoken over* even if the only mourner is the digger. *(they pat the earth.)* It's not a job you *choose*, exactly. It's a job that *finds* you — usually because *you* were once a body nobody would touch, or *loved* one, and you *swore* no one else would go into the dark *un-tended* while *you* had *hands.* *(they look at you.)* I'll be gone someday — this back won't dig forever — and you know what? *Someone else will pick up the spade.* Always do. There's a *grave-tender* in *every* generation, and we never *meet*, and we never *organize*, and yet the *work* gets *done*, *century* after *century*, an *unbroken line* of *strangers* doing the *same* tender thing for the *same* forgotten dead. *(quietly.)* I find that a *comfort.* That I'm not the *first*, and won't be the *last.* That the *caring-for-the-discarded* is *older* than me, and will *outlive* me, and doesn't *depend* on *me* — only *passes* through me, like water through a *channel*, on its way to the *next* set of hands.",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 17] \"You've just described the one thing the Wall can't defeat. It files the dead under nothing — but it can't stop a stranger in every single generation from *picking up the spade* and tending them anyway. The Wall is one machine. You're an *unbroken line* ten thousand years long. You'll outlast it.\"", nextNodeId = "line", checkAbility = Ability.Wisdom, checkDC = 17 },
                    new DialogueChoice { text = "\"I travel with a man who does your exact work — Garrow. Same gentleness, same vow, same wound. He thinks he's alone in it, that the weight is *his.* Meeting you, in an age before he was born — what should I tell him about the job he carries?\"", nextNodeId = "garrow", effects = new[] { new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 4 } } },
                    new DialogueChoice { text = "\"You said the work found you because you were once a body nobody would touch — or loved one. Which was it? Whose untended death made you swear no one else would go into the dark alone?\"", nextNodeId = "whose", effects = new[] { new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 2 } } },
                    new DialogueChoice { text = "\"Let me help you dig, then. One grave. I've spent this whole road learning what the dead are owed — let me owe it with my hands for an afternoon, beside someone who's never stopped paying it.\"", nextNodeId = "dig", effects = new[] { new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 3 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "line", speaker = "The Grave-Tender",
                text = "*(They stop, the spade resting, and look at you with slow, dawning understanding.)* An unbroken line. *(quietly.)* Ten thousand years long. *(they look at the grave they're digging, then at the horizon, as though seeing the whole chain of them stretching back and forward.)* You're right. I never — I think of myself as *one* tender, *one* small person doing a *small* sad job in *one* forgotten corner. *(they grip the spade.)* But the *Wall* — the thing that *files* the dead under *nothing* — it's a *single* engine, isn't it. *One* machine, *one* cruelty, *running.* And *against* it, there isn't *one* opponent. There's *me*, and the *one before me*, and the *one before her*, and *forward*, the *one who'll* take my *spade* — a *line* of *strangers* who *never met*, *each* doing the *same* tender thing, *century* after *century*, *refusing*, *with our hands*, to let the *forgotten* go *untended.* *(their voice strengthens.)* The Wall has *eons* and *billions.* But it has to win *every* generation *forever* to win at *all.* And we — the *grave-tenders* — we only have to *keep showing up*, *one* at a *time*, *passing the spade*, and the Wall can *never* outlast *that*, because *caring* *regenerates* and *cruelty* just *grinds.* *(they almost smile.)* I'm not a *small* person doing a *small* job. I'm *one link* in the *longest chain of defiance there is.* Thank you. I'll dig *lighter* for knowing it. *Pass the spade* well, when your turn comes. There's *always* a next set of hands.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.gravetender_line", op = FlagOp.SetTrue }, new FlagClause { key = "act5.unbroken_line", op = FlagOp.SetTrue }, new FlagClause { key = "act2.cataloguing_defeats_the_wall", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "garrow", speaker = "The Grave-Tender",
                text = "*(They go still at the name, and something passes over their face — recognition, though they've never heard it.)* Garrow. *(softly.)* I don't know the name. But I know the *man*, because the *man* is *me*, and *every* tender there ever was. *(they set down the spade.)* Tell him this. *(quietly, with the weight of someone speaking across ten thousand years to a brother they'll never meet.)* Tell him the *weight* he carries — the *vow*, the *wound*, the *certainty* that *he* must be the one, that if *he* fails the forgotten go *untended* — tell him it is *real*, and it is *holy*, and it is *also* a *lie* the work tells you to keep you *digging.* *(they meet your eyes.)* The lie is *\"you are alone, and it all depends on you.\"* And it *feels* true, because in *his* town, in *his* hour, it *is* — he *is* the only one, *right then.* *(fiercely gentle.)* But he is *not* alone in the *long* way. There was a *grave-tender* before him he never knew, and there's *me*, in an *age* before he was *born*, doing the *same* work with the *same* wound, and there will be *one* after he sets down his spade. *(they press a hand to their chest.)* Tell Garrow the job is *not his to finish.* It is *only his to carry, well, for his span, and pass on.* The *forgetting* is *eternal* — but so is the *tending*, and he is *one* link in a chain that *predates* him and will *outlive* him, and *that* — not the *crushing solo weight* — is the *truth* of the vocation. *(quietly.)* He can *rest*, someday. The *line* will *hold* without him. *Tell him a grave-tender ten thousand years dead said so, and would have dug beside him gladly.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.gravetender_garrow", op = FlagOp.SetTrue }, new FlagClause { key = "act5.unbroken_line", op = FlagOp.SetTrue }, new FlagClause { key = "act5.garrow_not_alone", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 6 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "whose", speaker = "The Grave-Tender",
                text = "*(They are quiet a long moment, hands resting on the spade, and when they speak it's the low voice of an old grief worn smooth.)* Whose untended death. *(softly.)* ...My sister's. *(they look at the earth.)* We were poor, and *faithless* by the reckoning of the day — served no god, hadn't the *coin* for the *temples* that *mattered* — and when she *died*, *young*, the *priests* wouldn't *come*, and the *town* wouldn't *touch* her, and they were going to throw her in the *lime-pit* with the *plague-dead* and the *criminals*, *un-washed*, *un-named*, *un-spoken-over.* *(their hands tighten.)* And I was *fourteen*, and I had *nothing* — no *coin*, no *standing*, no *god* — but I had *hands.* So I *carried* her *myself.* *Dug* the grave *myself.* *Washed* her, *named* her, *spoke* over her the *only* words I knew, which weren't *holy* words, just — *\"you were my sister, and you were loved, and I will not let you go into the dark un-tended.\"* *(they meet your eyes.)* And then I *looked* around, and saw *how many* others there were — the *poor* dead, the *faithless* dead, the *unwanted* — *piling* up, *un-tended*, because *everyone* who *could* afford to *care* had decided they *didn't have to.* *(quietly.)* So I *kept* digging. For *her.* For *all* of them. *(they pick the spade back up.)* That's the *whole* secret of every grave-tender there ever was, I'd wager. *We* were *once* the *body* nobody would *touch* — or *loved* one — and we *swore*, over *one* grave, that *no one* else would go *alone.* And then we *spent our lives* keeping a *promise* we made to *one* dead person, to *everyone.* *(softly.)* Her name was *Maerin*, if you wondered. Everything I've dug, I've dug for *Maerin.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.gravetender_whose", op = FlagOp.SetTrue }, new FlagClause { key = "act5.dug_for_one", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "dig", speaker = "The Grave-Tender",
                text = "*(They consider you a moment, then hand you the spare spade with a small, grave nod — the highest courtesy of their trade.)* Then dig. *(and you work beside them, in silence at first, turning the good earth for a stranger no one else would bury — and there is a strange peace in it, the simplest possible answer to ten thousand years of walling: a hole in the ground, shaped like a person, dug by hands that decided the forgotten were worth the labor.)* *(After a while, the grave-tender speaks, low.)* You dig like someone who's been *carrying* the *weight* a long way. *(they pat the earth.)* It's *good* work, isn't it. *Honest.* You can't *argue* a soul into *resting*, can't *win* it with a *speech* or a *crown* — but you *can* dig it a *grave*, and *wash* it *clean*, and *say* its *name*, and that's — that's a thing the *hands* can *do* that the *whole* arguing *cosmos* can't *undo.* *(they straighten, the grave finished.)* There. One more soul that *won't* go into the dark *un-tended.* *(they look at you.)* Carry *that* feeling to wherever you're *going* with that *crack* in you. Whatever *vast* thing you *mean* to do — remember it's *made* of *this.* One *grave.* One *name.* One *pair of hands* that *decided to care.* The *rest* is just *that*, *repeated*, until the *Wall* runs out of *forgotten* faster than *we* run out of *spades.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.gravetender_dig", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "The Grave-Tender",
                text = "*(The grave-tender returns to their work — washing, digging, naming, speaking over the dead nobody else would touch, exactly as your companion does, exactly as someone did before them and someone will after — and you carry away the quiet backbone of the whole saga: that against a single eternal engine of forgetting stands an unbroken, unorganized, ten-thousand-year line of strangers who each, in their own age, picked up the spade and refused to let the forgotten go into the dark alone.)*",
            });

            NpcAnyGravetenderDialogue = g;
        }

        private void BuildNpcAnyListkeeperDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.any.listkeeper";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "A Child Keeping a List",
                text = "*(A child sits apart from the others — every era has its grave-eyed serious child — with a scrap of parchment, or a wax tablet, or a strip of bark, and a stub of something to write with, carefully printing names in a careful, laborious hand. They look up at you with the grave directness of a child engaged in important work, and decide, after a quick appraisal, that you can be trusted.)* I'm making a list. *(matter-of-fact.)* Don't worry, you're not on it. It's not *that* kind of list. *(they pat the space beside them.)* It's a list of people nobody else is going to remember. I do one a day, at least. Sometimes more, if it's been a bad day for it. *(they squint at you.)* Do you know anybody nobody's going to remember? You can tell me their name. I'll add them. I'm very careful with the spelling.",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.listkeeper_met", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "The Child With the List",
                text = "*(They show you the list, shy but proud, names in a child's painstaking hand.)* It started because of old Maman Bell. *(they explain, serious.)* She lived next to us, and she had *nobody*, and when she *died*, the day after, it was like she'd — like she'd *never been there at all.* Nobody *said* her name. The *room* got rented to someone *new* and they didn't even *know* a Maman Bell had *lived* and *died* in it. *(they frown at the unfairness.)* And I thought — that's *wrong.* That's the *worst* thing I ever heard of. That you can *live* a whole *life* and then be *gone* so *complete* that it's like *subtraction*, like the world just *takes you out* and *closes up the hole.* *(they tap the list.)* So I write them down. The ones nobody else will. Maman Bell was *first.* *(they look up at you.)* The grown-ups think it's *morbid.* A child keeping a list of *dead* nobodies. They want me to play at *something cheerful.* *(fiercely, in the way only a serious child can be.)* But I *asked* one of them — *\"if you died and nobody remembered, wouldn't you want* one *person to have written your name down?\"* — and they *didn't have an answer*, they just looked *sad* and *changed the subject*, which is what grown-ups do when a child is *right.* *(they go back to writing.)* So I keep the list. Somebody has to. Might as well be me. I've got *good* handwriting and I'm *not* scared of dead people. Those are the *main* qualifications, I think.",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 17] \"Do you know, child, that you invented something thousands of years old without being told? There's a girl named Lula, in a city far from here, doing exactly this — and a choir, and an indexer, and a clerk of memory. Nobody taught any of you. The *list* keeps being *reinvented*, in every age, by a serious child who can't bear the subtraction.\"", nextNodeId = "reinvented", checkAbility = Ability.Wisdom, checkDC = 17 },
                    new DialogueChoice { text = "\"You said being forgotten is like subtraction — the world closing up the hole. That's the most exact thing anyone has told me on a very long road. Where did a child learn to see a thing that clearly?\"", nextNodeId = "subtraction", effects = new[] { new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 2 } } },
                    new DialogueChoice { text = "\"Add a name for me. A potter named Halen. A soldier named Maerys. A weaver named Sariel. They were forgotten for ten thousand years — but you've got good handwriting and you're not scared, and I'd like them on a child's careful list.\"", nextNodeId = "names", effects = new[] { new FlagClause { key = "sq.childs_list", op = FlagOp.SetTrue } } },
                    new DialogueChoice { text = "\"What happens to the list when it's full? When you've written more names than the parchment holds — or more than one life can keep? Have you thought about who carries it after you?\"", nextNodeId = "after" },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "reinvented", speaker = "The Child With the List",
                text = "*(The child's eyes go wide, and they sit up straight, the parchment forgotten.)* There's — there's *another* one? *(barely breathing.)* A girl doing *exactly* this? *(and then, slowly, something even bigger dawns, too big for the small face to hold all at once.)* ...And a *choir*, and — you said *nobody taught us.* *(they look at their list, then up at you.)* So I didn't — I thought I *invented* it. The list. I thought I was the *only* one *clever* enough, or *sad* enough, to *think* of it. *(quietly, wonder replacing pride.)* But if there's a *Lula*, and a *choir*, and an *indexer*, all doing the *same thing*, in *different places*, *never* having *met* — *(their voice fills with something like awe)* — then it's not *my* idea. It's not *anybody's* idea. It's just — a *thing that's true*, that *keeps getting found*, by whoever *looks* at the *subtraction* and *can't stand* it. *(they grip the list.)* That means — that means even if *I* stop, even if they *make* me stop, even if I *grow up* and get *busy* and *forget* — *somewhere*, some *other* serious child is *starting their own list*, *right now*, because *Maman Bell* happened to *them* too, with a *different name.* *(they look up, and the serious face breaks into a fierce, hopeful smile.)* You *can't kill it.* The *remembering.* You'd have to make *every* child in *every* age *not mind* the *subtraction* — and *some* of us *always* will. *(they bend back to the list, writing harder.)* I'm not the *only* one. I'm just the *one that's here.* That's — that's *better*, actually. That's *so much* better. Thank you for telling me I'm not *alone* in it.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.listkeeper_reinvented", op = FlagOp.SetTrue }, new FlagClause { key = "act5.remembering_regenerates", op = FlagOp.SetTrue }, new FlagClause { key = "act2.cataloguing_defeats_the_wall", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "subtraction", speaker = "The Child With the List",
                text = "*(The child considers the question with the deep seriousness of someone who has thought about little else.)* Where I learned to see it. *(they pick at the parchment's edge.)* ...I don't think anybody *learns* it. I think everybody *knows* it, when they're *small*, and then most people *un-learn* it, because it's *too sad* to *keep* knowing. *(quietly.)* When you're little, you think *everything* that *exists* will *always* exist. Your house. Your Maman. The *cat.* And then *one* of them *goes* — for me it was Maman Bell, next door — and you find out the *terrible* secret nobody *warns* you about: that things can *stop being*, and the *world doesn't even wobble.* *(they look up, grave.)* That's the *subtraction.* Not just that she *died* — everybody *knows* people die. It's that she died and *the world filled in the space so fast* it was like she'd *never made a dent.* Like a *stone* dropped in a *pond* that doesn't even *ripple.* *(fiercely.)* And once you've *seen* that — *really* seen it — you can either *un-see* it, like the grown-ups do, so you can be *cheerful* — or you can *decide* it's *not allowed*, and spend your life *making ripples* where the world tried to *close up smooth.* *(they tap the list.)* The list is *ripples.* Every name is me saying *\"the pond is* not *allowed to* forget *this stone fell.\"* *(they shrug, small and certain.)* I just never *un-saw* it, is all. That's the only difference between me and the cheerful grown-ups. I *remember* being *small* and finding out things can *stop.* And I *minded.* I never *stopped* minding.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.listkeeper_subtraction", op = FlagOp.SetTrue }, new FlagClause { key = "act5.remembering_regenerates", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "names", speaker = "The Child With the List",
                text = "*(The child takes up their writing-stub with immediate, businesslike focus, and the care they bring to it is its own small heartbreak.)* Halen. *(they print it slowly.)* H-A-L-E-N. A potter. *(they look up.)* I'll write *potter* next to it, so it's not just a *name*, it's a *person who did something.* *(they write.)* Maerys. A soldier. *(carefully.)* M-A-E-R-Y-S. And — Sariel? *(they get the spelling right.)* A weaver. *(they finish, and study the three new names with satisfaction.)* There. *(quietly.)* Ten thousand years, you said. They were forgotten ten thousand years. *(they touch the names.)* But they're not *now.* They're on *my list.* In *good* handwriting. With what they *did* written next to them. *(they look up at you, fierce and certain.)* That's the thing the grown-ups don't understand about the list. They think it's about the *dead.* It's not. *Halen* doesn't *know* he's on it. It can't *help* him. *(they tap their own chest.)* It's about *me.* About *deciding* I'm the *kind* of person who *writes the name down* instead of the kind who *lets the pond close.* *(they carefully roll the list.)* When you write somebody's name, you don't *save them.* You can't. They're *gone.* You just — you *change what kind of world it is*, by a *tiny* bit. From a world where they were *forgotten*, to a world where *one* serious child *wrote them down careful.* *(they look up.)* That's worth doing. Even if it's *small.* *Especially* because it's small. Small is the only size that's *always* available.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.listkeeper_names", op = FlagOp.SetTrue }, new FlagClause { key = "sq.childs_list", op = FlagOp.SetTrue }, new FlagClause { key = "act5.remembering_regenerates", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "after", speaker = "The Child With the List",
                text = "*(The child's certainty falters, and for a moment they look their actual age — small, and a little frightened by the size of the question.)* When it's full. *(they look at the list, which is, you see, nearly out of room.)* ...I *have* thought about it. *(quietly.)* It scares me. Because *I'm* going to be *full* someday too — not the *parchment*, *me* — I'm going to *grow up*, or *get sick*, or *one day* I'll *die*, and then *who* writes *my* name down? Who keeps the *list* when the *list-keeper* needs *keeping?* *(they pick at the parchment.)* I used to think I had to do it *forever*, *alone*, and that was *too heavy*, it made me want to *stop.* *(then, slowly, they brighten, working it out as they speak.)* But — you said there's a *Lula.* And a *choir.* And *others.* Doing the same thing, *not* knowing about *me.* *(their eyes widen.)* So when *my* list is *full* — when *I'm* full — it doesn't *matter* if *this* parchment is *lost*, because *somewhere* there's *another* serious child *starting theirs.* The *list* isn't *this paper.* The *list* is the *deciding-to-keep-one.* And *that* can't be *full*, and can't be *lost*, because it lives in *whatever child next* can't *stand* the *subtraction.* *(they hug the parchment, relieved.)* I don't have to carry it *forever.* I just have to carry it *while it's mine*, and *trust* the *next* one *starts.* *(they look up, the fear gone.)* Will you — if you *meet* the next one, somewhere far away, a serious child with a *new* list — will you tell them *I* was here? That there was a *me*, before them, with *good handwriting?* That's all I want, really. Not to be *carried.* Just to be *one of the ones who kept it, in my turn.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.listkeeper_after", op = FlagOp.SetTrue }, new FlagClause { key = "act5.remembering_regenerates", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "The Child With the List",
                text = "*(The serious child bends back over their list of the forgotten — printing names in a careful hand, one a day, at least, more on the bad days — and you carry away the most hopeful thread in the whole saga: that the impulse to remember the discarded is not taught and cannot be killed, that it is *reinvented*, spontaneously, in every age, by whichever child looks at the subtraction of a life and decides, with the whole force of a small fierce heart, that *the pond is not allowed to close up smooth.*)*",
            });

            NpcAnyListkeeperDialogue = g;
        }

        private void BuildNpcAnyPriorloopDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.any.priorloop";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "A Traveler With Your Eyes",
                text = "*(At a crossroads between eras — the kind of liminal place the Spellplague left scattered through time — you meet a traveler, and the meeting stops you cold, because while the face is not *quite* yours, the *eyes* are, and the *crack* in their soul that matches the crack in yours hums between you like two struck tuning-forks. They are *worn* in a way you are not yet, harder, more certain, a few long steps further down a road you both walk — but not *gone*, not the warden, not the Last Returned. Something in between. They look at you with recognition and a terrible tenderness.)* ...Oh. *(quietly.)* You're an *earlier* one. *(they almost smile.)* Look at you. So much *road* still ahead of you. So much you don't *know* yet. I'd forgotten we ever looked that... *unhardened.*",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.priorloop_met", op = FlagOp.SetTrue }, new FlagClause { key = "act5.faced_the_loop", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "The Returned Before You",
                text = "*(They sit at the crossroads, and you sit across from them, two versions of one soul at different distances from the same end.)* Let me tell you what I *am*, so you can *use* it. *(quietly.)* I'm a *Returned*, like you. From a *loop* a few turns *ahead* of yours — or *behind*, the loop doesn't *number* cleanly. I walked the road you're walking. Met the *coffin-man*, the *complaint*, the *dog.* Reached the *Court.* Met *Jergal*, and the *Ledger*, and — *(their jaw tightens)* — and the *Last Returned.* The *warden.* The *me* at the *end.* *(they look at their own hands.)* And I *swore* I wouldn't *become* him. I was *certain* — as certain as *you* are *right now* — that *I'd* be the one to *break* it. *(softly.)* And then I reached the *Wall*, and saw the *billions*, and felt the *fear* — *the dark might be worse* — and I — *(they can't quite say it.)* I didn't take the *crown.* Not *all* the way. But I *hesitated.* I chose *\"not yet.\"* I decided to *loop once more* and *figure out something safer* — and *that*, it turns out, is *how* it *starts.* Not with *seizing* the crown. With *postponing* the *leap.* *(they meet your eyes, and the warning is total.)* I am *further* down the road than you, and I am *harder* than you, and I can *feel* myself *becoming* him, *one hesitation at a time* — and I came to this *crossroads* to do the *one* thing I *still* can: *warn the earlier one.* *Warn you.* *(fiercely.)* Don't *hesitate* at the Wall. Don't choose *\"not yet.\"* Don't *loop once more to be safe.* The *leap* never gets *less* terrifying. You only get *harder* and *more* certain that *postponing* is *wisdom.* *Be* the one who *leaps* while still *soft* enough to be *afraid* and do it *anyway.*",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 18] \"You came to warn me — which means the loop isn't a closed circle, it's a *chain*, and the links can *talk.* Each of us leaving a warning for the one behind. That's the annotator in Karsus's margins. That's the Revenant's map. We've been *passing notes down the loop* — and one of these notes is finally going to reach a Returned soft enough to act on it. Let it be me.\"", nextNodeId = "chain", checkAbility = Ability.Wisdom, checkDC = 18, failNodeId = "fade" },
                    new DialogueChoice { text = "\"You said you're becoming him one hesitation at a time. Then you're not gone yet — there's still a *you* in there, soft enough to have walked to this crossroads to warn a stranger. *That* you. Can *that* you still turn back, or are you only able to save *me?*\"", nextNodeId = "turnback" },
                    new DialogueChoice { text = "\"Tell me the exact moment. The hesitation that started it. Not the crown — the small choice before the crown, the 'not yet' that felt like wisdom. If I know the precise shape of the trap, I can feel it closing *before* it does.\"", nextNodeId = "moment", effects = new[] { new FlagClause { key = "act5.knows_the_trap", op = FlagOp.SetTrue } } },
                    new DialogueChoice { text = "\"We're the same soul. So this isn't you warning me — it's *us*, warning *ourselves*, across the loop. Whatever breaks the chain frees *all* of us, every link, you included. So help me leap, and you're not just saving the next one. You're saving the one who *hesitated.* You.\"", nextNodeId = "together", effects = new[] { new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 3 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "chain", speaker = "The Returned Before You",
                text = "*(They go very still, and then a slow, astonished light breaks across the worn face.)* ...A chain. That can *talk.* *(quietly.)* Not a *circle.* A *chain.* *(they look at their own hands as though seeing them new.)* I came here on an *impulse* I didn't *examine* — just a *certainty* that I *had* to *warn* the *earlier* one, that I *couldn't* let *you* walk it *blind* the way *I* did. *(their voice strengthens.)* And you're saying that *impulse* — that *passing the warning down* — is the *same* thing as the *hand in Karsus's margins.* The *Revenant's* map scratched over *forty years.* The *prior* Returned, *each* leaving a *note* for the *next.* *(fiercely.)* We've been *trying to break the loop from inside it for uncounted turns* — *not* by *seizing* anything, but by *each* of us *leaving a warning a little clearer than the last.* *(they grip your arm.)* And the loop *holds* only as long as *every* warning *arrives too late* — to a Returned *already* too *hardened* to *heed* it. *(their eyes blaze.)* But the warnings are getting *better.* The *Revenant* turned his into a *map.* I'm telling *you* the *exact* trap, *out loud*, *soft* enough that you *still* believe in the *leap.* *(softly, hopefully.)* You might be the one, *earlier* one. The link *soft* enough, with a *warning clear* enough, *finally* aligned. *(they meet your eyes.)* Don't let my *note* arrive too late like all the *others.* *Read* it *now*, while you're *young* enough to *act.* *Leap* at the Wall. And when you *do* — the *whole chain*, *every* link of *us* who *hesitated* and *passed the note*, *breaks* free at *once.* I *came* to *warn* you. *Let* it be the *warning* that finally *worked.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.priorloop_chain", op = FlagOp.SetTrue }, new FlagClause { key = "act5.loop_can_break", op = FlagOp.SetTrue }, new FlagClause { key = "act3.returned_annotator", op = FlagOp.SetTrue }, new FlagClause { key = "act3.loop_glimpsed", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "turnback", speaker = "The Returned Before You",
                text = "*(The question lands hard, and the worn face crumples, the hardness cracking to show the frightened soul still trapped inside it.)* Can *that* me still turn back. *(very quietly.)* ...I don't *know.* *(a long silence.)* That's the *honest* answer, and it's the one that *frightens* me most. *(they look at their hands.)* I'm *further* than you. *Harder.* The *crown's* not *on* my head — but its *shadow* is, and every *loop* I *hesitate*, the shadow *deepens*, and I can *feel* the *day* coming when I'll *reach* the Wall and *not* hesitate *toward* the leap but *toward* the *crown*, and *take* it, and *become* the *warden*, and *wait* at the *end* for the *next* of us. *(their voice shakes.)* So *can* I turn back? *Maybe.* I'm *soft* enough, *still*, to have *walked* to this crossroads to *warn* a *stranger* who's *me.* That's — that's *not nothing.* A *fully* hardened *warden* doesn't *warn.* He *recruits.* *(they meet your eyes.)* But I *fear* I'm too far to *leap* *myself* — that I've *hesitated* too many times, that the *fear* has *too* much *practice* in me now. *(quietly, with terrible courage.)* So I've made a *different* peace. Maybe *I* can't *break* the loop. But I can *spend* what *softness* I have *left* making *sure you can.* *(fiercely.)* That's *why* I'm *here.* Not to *save* myself — I might be *past* it. To make *certain* the *softness* I'm *losing* gets *spent* on *you*, who *still* have it *all.* *Take* it. *Take* my *warning* and my *fear* and the *exact* map of *how it starts*, and *leap* where I *couldn't.* If *I'm* too far gone — then let me be the *last* one who *hesitated*, by making *you* the *first* who *didn't.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.priorloop_turnback", op = FlagOp.SetTrue }, new FlagClause { key = "act5.loop_can_break", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "moment", speaker = "The Returned Before You",
                text = "*(They close their eyes, reaching back for the precise instant, and when they speak it's with the exactness of someone who has replayed it a thousand times.)* The exact moment. *(quietly.)* It wasn't at the *Wall.* That's the *first* lie — that the *trap* is the *crown*, the *big* shining *choice* at the *end.* *(they shake their head.)* The trap is *earlier*, and *smaller*. *(they meet your eyes.)* It was when I *first* truly *understood* the *golden road* — the *leap*, the *release*, the *fall* — and felt, *underneath* the understanding, a *small cold voice* say: *\"Yes. That's right. That's the answer. But you don't have* enough *yet. One more loop. Meet a few more souls, learn a little more, be a little* surer *— and* then *you'll leap, and you'll leap* better.\"* *(their voice tightens.)* *That's* the moment. Not *greed.* Not *fear* of the *dark.* The desire to be *more ready.* To *leap* from *certainty* instead of *faith.* *(fiercely.)* And it *feels* like *wisdom*, it feels *responsible*, it feels like *exactly* what a *careful* soul *should* do — *gather* more *before* the *irreversible* leap. *(they grip your arm.)* But the *leap* *cannot* be *made* from *certainty*, *earlier* one. There is *never* enough. The *golden road* is a *leap of* *faith* — that *un-kept* is *kinder* than *kept* — and the *trap* is the *voice* that says *\"wait until it's not a leap of faith anymore.\"* *(quietly, urgent.)* It will *never* stop being a leap of faith. *Every* loop you wait for *certainty*, you *harden*, and the *waiting itself becomes the warden.* *(they meet your eyes.)* So when you reach the *understanding*, and the *small cold voice* says *\"one more loop, to be sure\"* — *that's* it. *That's* the trap, *closing.* *Leap* *anyway.* *Afraid.* *Unsure.* *Soft.* That's the *only* way it's *ever* done — and the *only* way it's *never* been done, *yet.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.priorloop_moment", op = FlagOp.SetTrue }, new FlagClause { key = "act5.knows_the_trap", op = FlagOp.SetTrue }, new FlagClause { key = "act5.loop_can_break", op = FlagOp.SetTrue }, new FlagClause { key = "act3.break_the_crown_known", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "together", speaker = "The Returned Before You",
                text = "*(They look at you for a long moment, and then something in the worn face *eases*, a weight they've carried alone across loops finally shared.)* The same soul. *(softly.)* Warning *ourselves.* *(they almost laugh, wet-eyed.)* I've been thinking of it *wrong* this *whole* time — as *me*, the *failure*, warning *you*, the *hope.* As if we were *separate.* As if my *hesitation* and your *softness* were *different* people's. *(they shake their head.)* But we're *one* soul, *strung out* across the *loop*, and *that* changes — *everything.* *(their voice fills.)* It means I'm not *warning* you out of *pity*, from *above*, a *lost* thing helping a *saved* one. It means *we* — *all* of us, *every* link, the *Revenant*, the *annotator*, *me*, *you*, even the *warden* at the *end* — are *one* person *trying to save ourselves*, *passing* the *attempt* down the *chain*, *hand* to *hand*, *loop* to *loop.* *(they grip both your hands.)* And whatever *breaks* it *frees* *all* of us *at once* — *backward* and *forward* — because we're *not* a *line* of *separate* failures, we're *one* soul that *finally* got it *right*, *retroactively redeeming* every *link* that *tried.* *(fiercely, joyously.)* So when you *leap*, *earlier* one — you don't *leave* me *behind.* You *pull* the *whole* chain *through* with you. *Me.* The *warden.* *Every* hesitating, hardening, *trying* version of *us.* *(they meet your eyes, and for a moment they look *soft* again, *young* again, *freed* in *advance.*)* *Leap.* And *take us all* *with* you. That's not *me* saving *you.* That's *us*, *saving* *us.* *Finally.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.priorloop_together", op = FlagOp.SetTrue }, new FlagClause { key = "act5.loop_can_break", op = FlagOp.SetTrue }, new FlagClause { key = "act5.last_returned_freed", op = FlagOp.SetTrue }, new FlagClause { key = "act3.forgiveness_is_not_earned", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 6 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "fade", speaker = "The Returned Before You",
                text = "*(They shake their head slowly, the hardness reasserting, and the worn eyes go distant.)* You're trying to make it *hopeful.* A *chain*, *notes*, *breaking free.* *(quietly.)* I *had* that hope, *earlier* one. It's one of the *things* you *lose*, loop by loop — the *belief* that the *warning* will *land*, that *this* time is *different.* *(they rise.)* I've *given* you the warning. That's *all* I came to do. Whether it *lands* — whether *you're* the one *soft* enough — that's *not* mine to *see.* I'll have *looped* on by then, *harder*, *further*, *closer* to the *crown.* *(they look at you, and there's a terrible gentleness in it.)* Maybe you'll *break* it. Maybe you'll become *me*, and *then* him, and *warn* the *next* one from a *little* further down. *(they turn to go.)* Either way — *don't* waste the *softness* arguing with a *harder* you about *hope.* *Spend* it on the *Wall.* *Go.* *(and they walk on toward their own Court, their own Wall, their own hesitation, a few long steps ahead of you on the only road either of you has ever walked.)*",
                autoNextNodeId = "close",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "The Returned Before You",
                text = "*(The Returned before you walks on from the crossroads — worn, hardening, a few long steps further down the road toward the warden, but not gone, *not yet*, soft enough still to have stopped and warned an earlier self — and you carry away the most intimate hope and dread of the entire loop: that you are not one soul facing the Wall but a *chain* of selves stretching across uncounted turns, each leaving a clearer warning for the one behind, all of you *one person trying to save yourselves* — and that the leap which finally breaks it will pull every hesitating link through at once, *backward and forward*, redeeming even the warden who waits, grieving, at the end.)*",
            });

            NpcAnyPriorloopDialogue = g;
        }
    }
}
