// AUTO-GENERATED by tools/dlg-compile.py from a .dlg source — do not edit by hand.
// Re-generate with: python3 tools/dlg-compile.py
using UnityEngine;
using SunderedCrown.Dialogue;
using SunderedCrown.Stats;

namespace SunderedCrown.Content
{
    public class GlasswidowSideQuestContent
    {
        public DialogueGraph SqWindowThreadDialogue { get; private set; }

        public GlasswidowSideQuestContent()
        {
            BuildSqWindowThreadDialogue();
        }

        private void BuildSqWindowThreadDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "sq.window.thread";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "Senna the Glassblower",
                text = "*(Senna kneels in a litter of colored glass — ruby, cobalt, a gold like trapped afternoon — sweeping the shards of her seventh window into a pile with hands that are scarred from forty years of the craft and, you see now, from picking up what the church keeps breaking. The empty stone frame in the chapel wall above her holds nothing but morning light and the lead ghosts of a picture. She doesn't look up.)* They came at dawn. *(flatly.)* Justiciar's men. Hammers wrapped in cloth so it'd sound like *charity* instead of *smashing.* *(she lifts a piece of cobalt — part of an eye, you realize.)* Seventh time. *(now she looks at you, and her eyes are dry and furious and very tired.)* I'll have it back up by the festival. I always do. You've the look of someone who'll either help me carry glass or tell me to stop. Decide which before you speak. I haven't the patience this morning for the other kind.",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "sq.window_thread_begun", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "Senna the Glassblower",
                text = "*(She gathers the shards with terrible care, naming them to herself as she works.)* It's my husband. *(quietly.)* Corm. Glassblower, like me — better than me, though I'd never have told him. *(a piece of gold.)* He doubted. Out loud, the wrong year, to the wrong deacon — *\"if the gods are good, why's the glass so hard to make and so easy to break,\"* something foolish and *true* he said over ale — and when the fever took him the church remembered the doubt and walled him. *Faithless.* *(she sets the gold down.)* So I made him a window. Him, exactly — the squint he got at the furnace, the burn-scar on his thumb, *caught in light*, because that's what a glassblower *is*, a person who makes light *hold still* for a moment. *(her jaw tightens.)* And the church calls it heresy — *a Faithless soul, depicted in a place of worship, in glory* — and they *shatter* him. And I *rebuild* him. Seven times. *(she meets your eyes.)* They have hammers and doctrine and the Justiciar's leave. I have forty years of the craft and a frame in the wall and the *fact* that they cannot make me stop. *(quietly, fierce.)* But I'm sixty-one, and my hands are going, and somewhere under the fury I know I am losing a war of attrition with men who will outlive me and out-hammer me. So. Help me carry glass — or help me find a way to make Corm *last.* I'd take the second, if you've got it. I'm so tired of *picking him up off the floor.*",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 18] \"They can shatter 'a Faithless heresy' all day — it's an abstraction, it costs them nothing. But they can't so easily shatter *Corm the glassblower who fixed every lamp in the quarter.* Make the window unmistakably *him* — named, specific, the man the whole Gate knew — and every hammer-blow becomes the church smashing a neighbor's face. Specificity is the armor.\"", nextNodeId = "specific", checkAbility = Ability.Wisdom, checkDC = 18, failNodeId = "carry" },
                    new DialogueChoice { text = "\"One window they can break. A hundred they can't. Cut Corm into small panes — a hand here, the squint there, the burn-scarred thumb — and set them in a hundred windows across the Gate, in shops and homes and taverns. Let the whole city carry a piece of him. They'd have to smash the Gate itself to erase him then.\"", nextNodeId = "multiply", effects = new[] { new FlagClause { key = "sq.window_multiplied", op = FlagOp.SetTrue } } },
                    new DialogueChoice { text = "\"The rebuilding isn't honoring Corm anymore, Senna — it's a war that's killing you, on the church's terms, on the church's schedule. What if we took his image somewhere their hammers can't reach? Carry the design to the Court of the Dead — let the powers that walled him see the face the church keeps trying to break.\"", nextNodeId = "court" },
                    new DialogueChoice { text = "\"Tell me about the window itself. Not the war — the *picture.* What does Corm look like, caught in light? Forty years of the craft went into him. Let me see the man before we decide how to keep him.\"", nextNodeId = "picture", effects = new[] { new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 2 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "specific", speaker = "Senna the Glassblower",
                text = "*(Her sweeping hands go still. She looks up at the empty frame, and something shifts in her tired fury — a tactician finding the seam.)* ...Make it *him.* *(slowly.)* Not *\"a Faithless soul in glory.\"* *Corm.* *(she picks up the cobalt eye-shard.)* You're right. When the *deacons* look at the window they see a *doctrine* — *\"a heretic, depicted in light, an offense to the order\"* — and a *doctrine* is *easy* to *smash*, it has no *face*, it costs them *nothing.* *(her voice sharpens.)* But the *quarter* — the *quarter* doesn't see a doctrine. They see *Corm.* The man who *fixed* the *lamps*, who *blew* the *christening-cups* for half the *children* on this *street*, who gave *old* Marта her *spectacles* when she couldn't *pay.* *(she stands, fierce now.)* So I make him *unmistakable.* The *squint.* The *thumb-scar.* I'll put the *christening-cups* in his *hands* in the glass — the *actual* ones, the *patterns* the *families* would *recognize.* I'll make it so *plainly Corm* that when the *Justiciar's* men come with their *cloth-wrapped* hammers, the *whole* *street* is *standing* there, and *every* blow is them *smashing* the *face* of the *man* who *fixed* their *lamps*, in *front* of the *children* he *made* the *cups* for. *(she meets your eyes, blazing.)* They can shatter a *heresy.* Let's see them shatter a *neighbor.* *(quietly.)* The *abstraction* was the *weakness.* I made him *general* enough to *break.* Now I make him *specific* enough that *breaking* him *costs* them the *quarter.* Help me set the *cups* in his *hands.* This *eighth* window, they won't *dare.*",
                autoNextNodeId = "2",
                onEnter = new[] { new FlagClause { key = "sq.window_made_specific", op = FlagOp.SetTrue }, new FlagClause { key = "act2.cataloguing_defeats_the_wall", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "multiply", speaker = "Senna the Glassblower",
                text = "*(She stops, and a slow, dangerous craftsman's smile breaks through forty years of grief.)* A hundred windows. *(she turns the gold shard in the light.)* One they can break. A hundred — *(she laughs, short and amazed.)* I've been *fighting* them at the *one* frame, on *their* ground, the *chapel* wall they can *guard* and *smash* at *dawn* — and you're saying *don't.* *Scatter* him. *(her eyes sharpen.)* Cut Corm into *pieces* — not *shattered* pieces, *chosen* ones — the *squint* in the *tavern's* window, the *burn-scarred* thumb in the *baker's*, the *light* he's *caught* in over the *almshouse* door — and set a *piece* of him in a *hundred* homes and shops across the *Gate.* *(she gathers shards with new purpose.)* The *families* whose *children's* cups he *blew* would *take* a *pane*, gladly — *hide* it in *plain* sight, a *pretty* bit of *colored* glass in a *kitchen* window that *only they* know is *Corm's* thumb, *Corm's* squint, a *piece* of the *walled* man kept in *light* over their *supper.* *(fierce.)* And then the *church* would have to *smash* a *hundred* private windows, in a *hundred* homes, *accusing* a *hundred* families of *heresy* over a *bit* of *glass* — and *that* they *can't* do, because *that* isn't *enforcing* doctrine, that's *war* on the *whole* *quarter.* *(she meets your eyes.)* One window is a *target.* A *hundred* is a *city* that *won't* let a *man* be *erased.* *(quietly, wondering.)* I've been *guarding* a *frame* when I should have been *seeding* a *quarter.* Help me cut him into a *hundred* small *lights.* Let them *try* to *gather* the *dawn.*",
                autoNextNodeId = "2",
                onEnter = new[] { new FlagClause { key = "sq.window_multiplied", op = FlagOp.SetTrue }, new FlagClause { key = "act5.refusing_consent", op = FlagOp.SetTrue }, new FlagClause { key = "act2.cataloguing_defeats_the_wall", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "court", speaker = "Senna the Glassblower",
                text = "*(She is quiet a long moment, the fury banking into something more dangerous and more hopeful.)* Somewhere their hammers can't reach. *(she looks at the empty frame.)* I've thought of it as a *war for this wall.* This *one* frame, this *one* chapel, *Corm* against the *Justiciar*, *here.* *(her voice tightens.)* But you're walking to the *Court* — to the *powers* that *walled* him in the *first* place, the *source* the deacons only *serve.* *(she stands.)* What good is *winning* the *chapel* wall if the *Wall* that *took* him still *stands?* I could *guard* this *frame* till I *die* and Corm would *still* be *Faithless*, *still* *filed*, *still* *nothing*, in the *only* ledger that *finally* matters. *(she crosses to a chest, draws out a roll — the master cartoon, the full-size drawing of the window.)* Take his *image* to the *Court.* The *whole* design — Corm, caught in light, the *christening-cups* in his hands. *(she presses it to you.)* Let the *gods* who *file* the *Faithless* see what the *church* keeps *trying* to *break* — not an *abstraction*, not *\"a heretic,\"* but a *man*, *rendered* in *forty years* of a *widow's* craft, *exactly* as he *was.* *(fierce, hopeful.)* They can *argue* with a *doctrine.* Let them *argue* with his *face.* With the *squint.* With the *thumb-scar.* With the *cups* he *blew* for *children.* *(she meets your eyes.)* I can't *carry* glass to the *Court.* But I can *carry* the *cartoon* — the *light* held *still* — and *you* can *carry* it *for* me, to the *one* place where *winning* means Corm *isn't* *Faithless* *anymore.* *(quietly.)* Win it *there*, and I'll *never* have to *rebuild* this window *again* — because the *thing* that *shatters* it will be *gone.*",
                autoNextNodeId = "2",
                onEnter = new[] { new FlagClause { key = "sq.window_to_the_court", op = FlagOp.SetTrue }, new FlagClause { key = "act5.the_great_objection", op = FlagOp.SetTrue }, new FlagClause { key = "act2.cataloguing_defeats_the_wall", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "picture", speaker = "Senna the Glassblower",
                text = "*(The fury gentles, and she sits back on her heels among the shards, and for a moment she's not a woman at war but a widow describing the man she loved.)* The picture. *(softly.)* He's at the *furnace.* That's how I *made* him — not *praying*, not *pious*, not *\"in glory\"* the way the church *pretends* I claimed. At the *furnace*, where he *lived*, the *gather* of *molten* glass on the *pipe*, and the *light* of the *fire* coming *through* the *glass* and *through* him, so you can't *tell*, in the window, where the *fire* ends and *Corm* begins. *(her hands shape it in the air.)* That's the *whole* of it, you see. That's what I was *trying* to *say* in *glass.* A *glassblower* takes *fire* and *breath* and *sand* — *nothing*, *the cheapest* things there *are* — and makes *light* *hold a shape.* *(her voice fills.)* And *Corm* — *Corm* was *fire and breath*, and the *Wall* says he was *nothing*, *sand*, *the cheapest* thing — and I made a *window* that *says*: *look. Look what the nothing made. Look what holds a shape, in the light, that the gods called* faithless.* *(she touches the empty frame.)* The *squint*. The *thumb-scar* from a *gather* gone *wrong* in *'thirty-one.* The *christening-cups.* And the *fire* coming *through*, so he's *lit* from *inside*, the way a *good* window is, the way a *person* is when you've *loved* them forty years. *(she meets your eyes, and the dry fury is wet now.)* That's *Corm.* Caught in *light.* That's what they keep *smashing.* *Now* — help me decide how to *keep* him. You've *seen* him. You know what's *worth* keeping.",
                autoNextNodeId = "2",
                onEnter = new[] { new FlagClause { key = "sq.window_corm_seen", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "2", speaker = "Senna the Glassblower",
                text = "*(Senna stands among the colored shards of her seventh window — ruby and cobalt and trapped-afternoon gold, the pieces of a walled man she has rebuilt and rebuilt — and looks from the empty frame to you, forty years of craft and seven mornings of sweeping in her scarred hands.)* So. Which is it. *(quietly.)* How do I keep my husband in the light, where the church can't break him?",
                choices = new[]
                {
                    new DialogueChoice { text = "\"Make him specific, and multiply him both: one unmistakable Corm in the chapel where the quarter will guard it, and a hundred small panes of him in a hundred homes they'd have to wage war on the whole Gate to smash. Let the window be a target and the city be the armor.\"", nextNodeId = "both", effects = new[] { new FlagClause { key = "sq.window_made_specific", op = FlagOp.SetTrue }, new FlagClause { key = "sq.window_multiplied", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 4 } } },
                    new DialogueChoice { text = "\"Carry his image to the Court with me. The chapel wall is a battle; the Wall is the war. Let the powers that filed him Faithless argue with the squint and the thumb-scar and the cups he blew for children. Win it there, and the thing that shatters him is gone.\"", nextNodeId = "to_court", effects = new[] { new FlagClause { key = "sq.window_to_the_court", op = FlagOp.SetTrue }, new FlagClause { key = "act5.the_great_objection", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } } },
                    new DialogueChoice { text = "\"Stop fighting on their schedule. Build one window, slowly, in secret, of materials that don't shatter easy — and unveil it at the festival when the whole quarter's watching and the Justiciar can't move against it without a riot. One window that lasts, chosen by you, not smashed by them.\"", nextNodeId = "one_that_lasts", effects = new[] { new FlagClause { key = "sq.window_one_that_lasts", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 4 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "both", speaker = "Senna the Glassblower",
                text = "*(She nods slowly, the craftsman and the tactician and the widow all agreeing at once.)* A target and an armor. *(she gathers her tools.)* Yes. *Both.* *(fierce, decided.)* I'll build the *eighth* window — *Corm*, *unmistakable*, the *cups* in his *hands*, in the *chapel* frame where the *quarter* can *stand* around it and *dare* the *hammers.* *(she sorts the shards into chosen piles.)* And I'll cut a *hundred* small panes — a *squint* here, a *thumb-scar* there — and *seed* them across the *Gate*, in *kitchens* and *taverns* and over the *almshouse* door, so that *even if* they *somehow* *break* the *chapel* window an *eighth* time, *Corm* is *already* *scattered* into a *hundred* *homes* they'd have to *burn* the *quarter* to *erase.* *(she meets your eyes.)* One they can *break.* A *hundred* with the *street* watching they *cannot.* *(quietly, the war turning at last to her advantage.)* Forty years I made *light* *hold* a *shape.* Now I'll make it hold a *shape they can't* *catch.* *(she presses a small pane into your hand — the burn-scarred thumb, in gold.)* Carry *one* yourself. So that *wherever* you *go* — even to the *Court* — a *piece* of *Corm*, *caught* in *light*, goes *with* you. *(she almost smiles.)* Let them *try* to *gather* the *dawn.* I've a *hundred* windows to *seed* and an *eighth* to *build*, and for the *first* time in *seven* mornings, I'm not *sweeping.* I'm *making.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "sq.window_made_specific", op = FlagOp.SetTrue }, new FlagClause { key = "sq.window_multiplied", op = FlagOp.SetTrue }, new FlagClause { key = "act2.cataloguing_defeats_the_wall", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "to_court", speaker = "Senna the Glassblower",
                text = "*(She rolls the master cartoon with reverent care and binds it with a strip of cloth — and you realize the cloth is one of Corm's old work-aprons, scorched at the edge.)* To the Court. *(quietly.)* The war, not the battle. *(she ties the apron-strip tight.)* I've been so *busy* losing the *battle* — *this* frame, *this* dawn, *this* hammer — that I forgot there *was* a *war*, and the *war* is the *Wall* itself, and *that* I cannot *fight* with *glass* and a *frame* and an *old* woman's *fury.* *(she presses the rolled cartoon into your hands.)* But *you* can. You walk to where the *Wall* is *decided.* *(her voice fills.)* Take Corm. The *whole* of him — the *furnace*, the *fire coming through*, the *squint*, the *cups.* And when the *powers* of the *dead* defend their *filing* — *\"he doubted, he is Faithless, he is nothing\"* — you *unroll* him. You let them *look* at *forty years* of a *widow's* craft, at a *man* made of *fire and breath* who *holds a shape* in the *light*, and you *ask* them: *\"is this nothing? Is this what nothing looks like?\"* *(she meets your eyes, fierce and wet.)* They can *shatter* a *window.* They *cannot* *shatter* the *cartoon* — the *light held still* — once it's been *seen* at the *one* court that *can't* *look* *away.* *(quietly.)* Win it there, and I'll set the *eighth* window in the *frame* and it will *never* break *again* — because the *deacons* only *smash* what their *Wall* *condemns*, and you'll have *un-condemned* him. *(she steps back.)* Carry my husband to the *Court*, Returned. *Light* him *up* where it *matters.* I'll keep the *frame* ready for the *day* he comes *home* *un-Faithless.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "sq.window_to_the_court", op = FlagOp.SetTrue }, new FlagClause { key = "act5.the_great_objection", op = FlagOp.SetTrue }, new FlagClause { key = "act2.cataloguing_defeats_the_wall", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "one_that_lasts", speaker = "Senna the Glassblower",
                text = "*(She considers it, and slowly the seven-morning exhaustion gives way to something steadier — a craftsman choosing her ground instead of defending the ground chosen for her.)* On *my* schedule. *(quietly.)* Not *theirs.* *(she looks at the empty frame, then away from it.)* You're right that I've been *fighting* the *way* they *want* me to — *fast*, *reactive*, *rebuilding* at *dawn* what they *smash* at *dawn*, a *war of attrition* I *lose* by *aging.* *(her voice firms.)* But a *window* doesn't *have* to be *fast.* The *best* ones *aren't.* *(she gathers the chosen shards.)* I'll build *one.* *Slowly.* In *secret*, in the *back* of the *shop*, of *thick* *flashed* glass and *iron* came that *doesn't* *shatter* like *cheap* lead — a window *built* to *last*, *Corm* as I've *never* had *time* to *make* him because I was always *rebuilding* the *broken* one. *(her eyes sharpen.)* And I'll *unveil* it at the *festival.* When the *whole* quarter is in the *street*, *lanterns* lit, *children* with the *cups* he *blew* — and I set *Corm*, *finished*, *perfect*, in the *frame*, in *front* of *everyone.* *(fierce.)* And the *Justiciar's* men can *come* with their *cloth-wrapped* hammers — *into* a *festival*, *through* a *crowd* of *neighbors*, to *smash* the *beloved* glassblower in *front* of the *children he made cups for* — and they *won't.* They *can't.* Not *then.* Not *there.* *(she meets your eyes.)* I've been letting them choose the *hour.* I'll choose the *hour* now — the *one* hour they *daren't* lift a *hammer* — and set him so *deep* in the *quarter's* *love* that *breaking* him *after* means *breaking* the *festival*, the *children*, the *whole* *street.* *(quietly, the war finally hers.)* One window. *Built to last.* *Unveiled* where they *can't* *touch* it. Help me *make* him *slow*, this time. He's *worth* the *patience* I never *gave* the *broken* ones.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "sq.window_one_that_lasts", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "carry", speaker = "Senna the Glassblower",
                text = "*(She nods curtly and pushes a crate of sorted shards toward you, the offer of help accepted without ceremony — but she does not soften, and she does not stop sweeping.)* Carry, then. *(flatly.)* The cobalt in *that* pile, mind the edges. *(she works.)* I'll have him back up by the festival. *Eighth* time. And a *ninth*, if it comes to that, and a *tenth.* *(she meets your eyes, and the fury is a wall of its own.)* I *know* it's a war I'm *losing.* I *know* I'm *sixty-one* and my *hands* are *going* and they have *hammers* and *time.* *(quietly, fierce.)* But the *day* I *stop* *rebuilding* Corm is the *day* the *church* is *right* that he was *nothing* — and I will be *dead* before I give them *that.* So *carry* the *glass*, or *don't*, but don't *tell* me to *stop.* *Stopping* is the *one* hammer that would *actually* *break* him. *(and she bends back to sweeping up her husband, shard by shard, to build him again — defiant, exhausted, unbeaten and unwinning, a widow at war with hammers.)*",
                autoNextNodeId = "close",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "Senna the Glassblower",
                text = "*(Senna the Glassblower kneels among the colored shards of her seventh memorial window — Corm at the furnace, fire coming through him, the man the church calls Faithless and keeps shattering and she keeps rebuilding — and whether you helped her make him too specific to smash, scatter him into a hundred homes, carry his image to the Court, build one window slow enough to last, or simply carry glass beside her in her unwinnable war, you carry away the glassblower's truth, which is the saga's rendered in light: that a person the powers call *nothing* — fire and breath and the cheapest sand — can be made to *hold a shape* in the light that outlasts every hammer; and that the memorial of the forgotten is not a single window to be guarded, but a refusal, scattered wide enough that erasing it would mean smashing the whole quarter's love.)*",
            });

            SqWindowThreadDialogue = g;
        }
    }
}
