// AUTO-GENERATED by tools/dlg-compile.py from a .dlg source — do not edit by hand.
// Re-generate with: python3 tools/dlg-compile.py
using UnityEngine;
using SunderedCrown.Dialogue;
using SunderedCrown.Stats;

namespace SunderedCrown.Content
{
    public class HarvestSideQuestContent
    {
        public DialogueGraph SqHarvestRefusedDialogue { get; private set; }

        public HarvestSideQuestContent()
        {
            BuildSqHarvestRefusedDialogue();
        }

        private void BuildSqHarvestRefusedDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "sq.harvest.refused";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "A Soldier and a Singer",
                text = "*(You've brought them to the same back room — Corwin, the Flaming Fist deserter, still scanning the exits; and Sister Wren, the Choir convert, her pale robe folded away. They do not know each other. They size each other up with the wariness of two people who served the *machine* from opposite ends — the hand that *marked* the doors, and the hand that *burned* the villages of those who hid behind them. The air is taut.)* *(Corwin speaks first, low:)* Choir. *(flatly.)* I burned villages full of people your *songs* condemned. *(Wren, steady, not flinching:)* And I marked the doors your fire was sent to *enforce.* *(they look at each other, two halves of the same atrocity, and then at you.)* *(Corwin:)* You brought us here for a *reason.* Say it.",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "sq.harvest_refused_begun", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "A Soldier and a Singer",
                text = "*(You lay it out: apart, each of them is one hand that refused — a deserter dismissed as a coward, a convert dismissed as a doubter, *deniable.* Together, with Corwin's testimony of the burnings and Wren's knowledge of how the marking works, they are something the harvest cannot deny: proof that it runs on *ordinary hands.* Corwin and Wren listen, and you watch the same realization land on both of them.)* *(Wren, quietly:)* He has the *fire* and I have the *chalk.* *(Corwin:)* And between us, the whole *shape* of it — *how* the doors get marked, *who* gives the order, *what* happens to the villages that *resist.* *(he looks at Wren.)* Alone, they call me a deserter and you a doubter, and the machine grinds on. *(Wren:)* Together, we're *witnesses.* From *inside.* *Both* ends. *(she meets your eyes.)* But witnessing has a *cost*, and we should decide, the three of us, *exactly* what we're willing to *spend* — because the harvest does not forgive hands that not only *refuse*, but *speak.*",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 18] \"The harvest's whole defense is 'we had no choice — orders, doctrine, the way things are.' You two are the *refutation*, standing in one room: a soldier who put down the torch and a singer who put down the chalk. You don't need to *destroy* the harvest. You need to prove, publicly, that *every hand in it could have opened.* That's a fire no doctrine survives.\"", nextNodeId = "refutation", checkAbility = Ability.Wisdom, checkDC = 18 },
                    new DialogueChoice { text = "\"Corwin's testimony names the burnings; Wren's list names the marked. Put them together and you don't have two confessions — you have a *map* of the machine: order, mark, enforce, burn. Nail that map where the city reads, and every soldier and singer still serving has to see their own hand on it.\"", nextNodeId = "map", effects = new[] { new FlagClause { key = "sq.harvest_map_obtained", op = FlagOp.SetTrue } } },
                    new DialogueChoice { text = "\"Before you spend anything — know what you're spending it *for.* Not revenge. Not even justice, quite. You're spending your safety to make the *next* hand hesitate. One soldier who reads Corwin's testimony and puts down the torch. One singer who reads Wren's and won't mark the door. That's the whole prize. Is it worth the cost to you both?\"", nextNodeId = "prize" },
                    new DialogueChoice { text = "\"You came from opposite ends of the same cruelty — the mark and the fire. Before you can be witnesses *together*, you have to be able to stand in a room together. So look at each other, and say the thing: not 'I followed orders,' but 'my hand did this, and it could have opened.' Start there, or the testimony's a lie.\"", nextNodeId = "reconcile", effects = new[] { new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 2 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "refutation", speaker = "A Soldier and a Singer",
                text = "*(Both of them go still, and you watch the idea settle — not as a plan, but as a kind of absolution-through-purpose.)* *(Corwin, slowly:)* The refutation. *(he looks at his own hands.)* They told me — *fifteen years* — that the *sin* was on the *officers*, that a *soldier* has *no* *choice.* *(Wren, quietly:)* And they told *me* the *doctrine* was *justice*, that a *Sister* just *sings* what's *true.* *(she meets Corwin's eyes.)* And we *both* found out the *same* thing, from *opposite* ends: *the hand always had a choice.* *(Corwin nods, grim.)* You're saying we don't have to *fight* the harvest. We have to *stand* somewhere *public*, *together*, and *be* the *proof* — *\"here is a soldier who refused, and a singer who refused, and we are not* destroyed, *we are not* damned, *we are standing here* breathing, *which means refusing was always* possible.\"* *(Wren's voice fills.)* And that's the *one* thing the machine *can't* survive — not a *rebellion*, it can *crush* rebellions — but the *quiet*, *undeniable* *fact* of *two* ordinary hands that *opened*, standing where *every* other hand can *see* them. *(she looks at you.)* The harvest runs on *\"we had no choice.\"* We're the *living* *disproof.* *(Corwin almost smiles, the first time.)* A deserter and a doubter. The two *most* dangerous things in the machine — *because we prove the machine is made of people who could have stopped.* *(he meets your eyes.)* Let's go *stand* where they *can't* *un-see* us. *That's* worth the cost. *Finally* something is.",
                autoNextNodeId = "2",
                onEnter = new[] { new FlagClause { key = "sq.harvest_refutation", op = FlagOp.SetTrue }, new FlagClause { key = "act5.refusing_consent", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "faction.choir", op = FlagOp.AddInt, amount = -1 }, new FlagClause { key = "faction.fist", op = FlagOp.AddInt, amount = -1 }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "map", speaker = "A Soldier and a Singer",
                text = "*(They set to it at once — soldier and singer, building the thing the machine most fears.)* *(Corwin spreads what he knows:)* The *order* comes from the garrison — I can name the *officers*, the *chain*, who *signs* the *burn-warrants.* *(Wren adds hers:)* And the *marking* comes *before* — the *register*, *who* compiles it, *how* a name gets *added*, *which* Sisters *sing* and *mark.* *(together, the shape emerges on the table between them: a flowchart of atrocity.)* *Order. Mark. Enforce. Burn.* *(Corwin looks at it, grim.)* Laid out like *that*, it's not a *holy* *harvest.* It's a *process.* A *bureaucracy* of *taking* *people.* *(Wren, quietly:)* With a *box* for *every* *hand.* The *officer* who *signs.* The *clerk* who *registers.* The *Sister* who *marks.* The *soldier* who *burns.* *(she meets your eyes.)* And *that's* the *horror* and the *weapon* both — *every* box is a *person*, and *every* person *could* *step* *out* of their *box*, and the *map* *shows* them *exactly* *where* they *stand* in the *machine.* *(Corwin rolls it for carrying.)* Nail *this* where the city reads, and *every* hand in the harvest sees its *own* box, its *own* *name*, its *own* *place* in the *process* — and has to *decide*, in *daylight*, whether to *stay* in it. *(he meets your eyes.)* We're not *exposing* a *conspiracy.* We're handing *every* *gear* in the *machine* a *mirror.* Some of them will *put down the chalk.* Some will *put down the torch.* That's how a *process* *dies* — *not* all at once. *One* refusing *hand* at a *time.*",
                autoNextNodeId = "2",
                onEnter = new[] { new FlagClause { key = "sq.harvest_map_obtained", op = FlagOp.SetTrue }, new FlagClause { key = "sq.harvest_map_nailed", op = FlagOp.SetTrue }, new FlagClause { key = "act2.cataloguing_defeats_the_wall", op = FlagOp.SetTrue }, new FlagClause { key = "act5.refusing_consent", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "prize", speaker = "A Soldier and a Singer",
                text = "*(The question stops them both, and it's Wren who answers first, quietly.)* The next hand. *(she looks at her own, the ones that marked Mira's door.)* That's — that's the *only* prize I *want.* I *can't* *un-mark* Mira's door. *Corwin* can't *un-burn* his villages. *Nothing* we do *brings* *back* *one* soul the harvest *took.* *(Corwin, grim:)* No. The *dead* are *dead.* We're *not* doing this for *them.* *(Wren meets your eyes.)* We're doing it for the *one* *Sister*, *somewhere*, *next* *month*, who'll *read* my *testimony* and *feel* the *ash* in her *mouth* and *put down the chalk* *before* she marks her *first* door. *(Corwin:)* And the *one* *soldier* who'll *read* mine and *put down the torch* at his *first* village instead of his *fifth.* *(quietly.)* That's it. That's the *whole* prize. *Not* the villages *we* burned — those are *gone.* The villages *they* *won't.* *(he meets your eyes, and there's peace in the grimness.)* I spent *fifteen years* being a *hand* that *didn't* open *until* it was *fifteen years too late.* If my *testimony* makes *one* *other* hand open *sooner* — *one* *village* that *doesn't* *burn* because a *soldier* *read* what I *did* and *chose* *different* — *(his voice roughens)* — then the *four* I *burned* *bought* *something.* Not *forgiveness.* But a *future* *village* that *stands.* *(Wren nods.)* The *cost* is our *safety.* The *prize* is the *next* hand. *(she meets your eyes.)* We're *agreed.* It's *worth* it. *Spend* us *well.*",
                autoNextNodeId = "2",
                onEnter = new[] { new FlagClause { key = "sq.harvest_prize", op = FlagOp.SetTrue }, new FlagClause { key = "sq.deserter_testimony", op = FlagOp.SetTrue }, new FlagClause { key = "sq.choir_hands_refuse", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "reconcile", speaker = "A Soldier and a Singer",
                text = "*(They look at each other — the mark and the fire, two halves of the same atrocity — and for a long moment neither can do it. Then Corwin, the older, goes first.)* *(Corwin, low and hard:)* My hand burned four villages. *Greenhollow. Ashby. Pemberly. One I never learned the name of.* *(he forces it out.)* Not *\"orders.\"* *My* hand. On the *torch.* It *could* have *opened.* It *didn't*, until the fifth. *(he looks at Wren.)* There. *Your* turn, Choir. *(Wren swallows, and meets his eyes, and does not look away.)* My hand marked the door of a woman named *Mira*, who gave me a candle when I was a cold child. *(her voice shakes but holds.)* Not *\"the register.\"* *My* hand. On the *chalk.* It *could* have *refused.* It *didn't*, until her. *(they hold each other's gaze, two confessions laid bare, no orders, no doctrine, no machine to hide behind.)* *(Corwin, quietly:)* ...I can stand in a room with *that.* A *hand* that *did* it and *says* so. *(Wren:)* So can I. *(she almost smiles, painfully.)* We can't be *witnesses* against the *machine* while *hiding* behind the *machine's* *own* *excuse.* *(she meets your eyes.)* You were right. The *testimony's* a *lie* if it starts with *\"I had no choice.\"* It has to start with *\"my hand did this, and it could have opened.\"* *(Corwin nods.)* Now it *can.* We've *both* *said* it. *Out loud.* To the *one* person who'd *understand* — *each* *other.* *(he looks at Wren, something like kinship in it.)* Two hands. Both *guilty.* Both *opened*, *late.* *Both* *willing* to *say* so where it *counts.* *(to you:)* Now we're *ready.* Not *before.* *Now.*",
                autoNextNodeId = "2",
                onEnter = new[] { new FlagClause { key = "sq.harvest_reconciled", op = FlagOp.SetTrue }, new FlagClause { key = "act5.shame_feeds_the_wall", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "2", speaker = "A Soldier and a Singer",
                text = "*(Corwin and Wren stand together now — the deserter and the convert, the fire and the chalk, no longer two deniable doubters but one undeniable testimony from inside the machine. They look to you for where to aim it.)*",
                choices = new[]
                {
                    new DialogueChoice { text = "\"Nail it to the Gate's own message-boards, where the quarter reads over breakfast. Loud, public, undeniable. Make the city wake up to the *process* of the harvest written plain — and let every serving hand find its own box on the map by noon.\"", nextNodeId = "public", effects = new[] { new FlagClause { key = "sq.harvest_exposed_public", op = FlagOp.SetTrue }, new FlagClause { key = "act5.refusing_consent", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 4 } } },
                    new DialogueChoice { text = "\"Take it higher than the city — carry it to the Court of the Dead with the rest of the indictment. The harvest is just the Wall's *recruiting arm.* Let a soldier and a singer testify before the powers that the machine of taking-people runs on hands that could always have opened.\"", nextNodeId = "court", effects = new[] { new FlagClause { key = "sq.harvest_to_the_court", op = FlagOp.SetTrue }, new FlagClause { key = "act5.the_great_objection", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } } },
                    new DialogueChoice { text = "\"Don't aim it at the powerful at all — aim it at the *hands.* Get it to the garrisons and the Choir-houses directly, soldier to soldier, singer to singer. Skip the spectacle. Just put the mirror in front of every gear, quietly, where it can't become a martyrdom they spin.\"", nextNodeId = "hands", effects = new[] { new FlagClause { key = "sq.harvest_to_the_hands", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 4 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "public", speaker = "A Soldier and a Singer",
                text = "*(They nail it up together at first light — Corwin's testimony and Wren's map of the marking, the whole process of the harvest written plain where the quarter reads.)* *(By the time the bells ring, a crowd has gathered, and it is not the crowd the harvest is used to — not the cowed, not the marked, but the *ordinary*, reading the *flowchart of their own complicity* and going very quiet.)* *(Corwin watches from the edge, hood up.)* Look at their *faces.* *(quietly.)* That's not *fear.* That's *recognition.* Half of them have a *cousin* in the *Fist*, a *sister* in the *Choir*, a *neighbor* who *signs* the *registers.* *(Wren, beside him:)* And now they *see* it. The *boxes.* The *process.* That it's not a *holy* *harvest* — it's *people* they *know*, *marking* and *burning* *people* they *know.* *(she meets your eyes.)* It can't be *un-seen* now. *That's* the thing about nailing it *public.* The harvest survived on everyone *not looking* at the *whole* of it — each hand seeing *only* its *own* box. *(Corwin:)* We just made the city look at the *whole* machine *at once.* *(he almost smiles.)* They'll *try* to *tear* it *down*, the warrant-signers. But you can't *un-ring* the bell. *Every* hand in this quarter now *knows* what its *box* *does.* *(quietly.)* Some of them will *step out* of it. That's all we wanted. *The looking.* It's *started.* It won't *stop* now.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "sq.harvest_exposed_public", op = FlagOp.SetTrue }, new FlagClause { key = "act5.refusing_consent", op = FlagOp.SetTrue }, new FlagClause { key = "act2.cataloguing_defeats_the_wall", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "faction.choir", op = FlagOp.AddInt, amount = -2 }, new FlagClause { key = "faction.fist", op = FlagOp.AddInt, amount = -2 }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "court", speaker = "A Soldier and a Singer",
                text = "*(They agree to carry it to the end of the road — past the city, to the Court itself.)* *(Wren, quietly:)* The Wall's recruiting arm. *(she looks at the map of the marking.)* That's — that's *exactly* what we *are*, isn't it. The *harvest* *takes* the *living* *Faithless* and *feeds* them to the *Wall.* We're the *front* of the *same* machine the *whole* road's been *walking* toward. *(Corwin, grim:)* Then our testimony belongs *where* the *machine* *ends.* Not the *city* — the *Court.* *(he rolls the map.)* Let a *soldier* and a *singer* stand before the *powers* of the *dead* and say it *plain*: *\"Your Wall is fed by* hands. *Ordinary ones. Ours. And ours* opened. *Which means* every *hand that feeds you* could.\"* *(Wren meets your eyes.)* The *gods* of the *Wall* defend it as *order*, *justice*, *the* *way* *of* *things.* *(her voice firms.)* We're the *proof* that the *\"way of things\"* is just *people choosing*, *box* by *box*, and that *people* can *choose* *otherwise.* *(Corwin nods.)* Add our testimony to the *indictment.* The *Complaint's* grievances, *Naeve's* signatures, the *boy's* drawings, *our* map — *all* of it, *one* great *objection*, read where the *powers* *have* to *hear.* *(he meets your eyes.)* We came from *inside* the machine. Let us *testify* from *inside* it, at the *one* court that *can't* *adjourn.* *That's* where two refusing hands *belong.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "sq.harvest_to_the_court", op = FlagOp.SetTrue }, new FlagClause { key = "act5.the_great_objection", op = FlagOp.SetTrue }, new FlagClause { key = "act5.refusing_consent", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "hands", speaker = "A Soldier and a Singer",
                text = "*(They consider it, and slowly both nod — the quieter, harder, more patient path.)* *(Corwin, low:)* Not the spectacle. The *hands.* *(he sets the map down.)* You're *right* that a *public* nailing becomes a *martyrdom* — they *spin* it, *\"deserter* and *heretic* *slander* the *holy* *work,\"* and the *ordinary* hands *look* *away* *again.* *(Wren:)* But *soldier* to *soldier.* *Singer* to *singer.* *Quietly.* *(she meets your eyes.)* I *know* the Sisters who *taste* the *ash.* I can *feel* it on them — the *ones* who *flinch* when they *mark*, who *sing* the *harvest-hymn* a *half-beat* *behind.* *(Corwin:)* And I know the *soldiers* who *drink* after a *burning.* Who *carry* the *old* man *out* and *then* *torch* his *house* and *hate* themselves for the *\"saving.\"* *(he meets your eyes.)* We don't *need* the *city.* We need to *reach* the *hands* that are *already* *cracking* — *put* our *testimony* in *their* *hands*, *privately*, *\"you're not alone, we felt it too, here's what we did about it\"* — and let them *crack* the *rest* of the *way*, *one* at a *time*, *quietly*, where the *machine* *can't* *make* a *spectacle* of it. *(Wren nods.)* A *loud* exposure makes *enemies* the harvest can *rally* against. A *quiet* one makes *defectors* it can't even *find.* *(she meets your eyes.)* We'll *unmake* it the way it was *made* — *one* *hand* at a *time*, *in* the *dark*, *passed* *hand* to *hand.* It's *slower.* It *can't* be *crushed.* *Let's* go find the *cracking* ones.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "sq.harvest_to_the_hands", op = FlagOp.SetTrue }, new FlagClause { key = "sq.choir_hands_refuse", op = FlagOp.SetTrue }, new FlagClause { key = "act5.refusing_consent", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "A Soldier and a Singer",
                text = "*(Corwin the deserter and Sister Wren the convert leave together — the fire and the chalk, two hands from opposite ends of the same atrocity, no longer deniable apart but undeniable together — and whether they nailed the machine's own flowchart where the city had to read it, carried their testimony to the Court of the Dead, or passed it quietly hand to cracking hand through the garrisons and Choir-houses, you carry away the harvest's undoing and the saga's civic heart: that the cruelest process in the world is built box by box of ordinary hands, that its whole defense is \"we had no choice,\" and that it dies not to a rebellion it can crush but to the simple, spreading, unkillable proof — standing in one room, a soldier and a singer — that every hand in it could always have opened.)*",
            });

            SqHarvestRefusedDialogue = g;
        }
    }
}
