// AUTO-GENERATED by tools/dlg-compile.py from a .dlg source — do not edit by hand.
// Re-generate with: python3 tools/dlg-compile.py
using UnityEngine;
using SunderedCrown.Dialogue;
using SunderedCrown.Stats;

namespace SunderedCrown.Content
{
    public class HarvestDenizensContent
    {
        public DialogueGraph NpcHarvestMotherDialogue { get; private set; }
        public DialogueGraph NpcHarvestBoyDialogue { get; private set; }
        public DialogueGraph NpcHarvestHealerDialogue { get; private set; }

        public HarvestDenizensContent()
        {
            BuildNpcHarvestMotherDialogue();
            BuildNpcHarvestBoyDialogue();
            BuildNpcHarvestHealerDialogue();
        }

        private void BuildNpcHarvestMotherDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.harvest.mother";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "Goodwife Orla",
                text = "*(A woman sits behind a blanket spread with woodworking tools — chisels, gouges, a fine plane, a set of carving knives — all clean, all cared-for, all clearly belonging to someone who knew the craft. She is not calling out prices like the other sellers. She just sits, watching each tool as though it might leave without her permission, and when you pause she looks up with a composure stretched paper-thin over something vast.)* They're good tools. *(quietly.)* The best. My son's. *(she straightens a chisel that didn't need straightening.)* He was a *carver.* A *fine* one. And these are — they're for *sale*, if you've the hands for them. I'll know if you don't. *(her eyes are steady and terrible.)* He'd not want them going to someone who'd let them *rust.*",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.orla_met", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "Goodwife Orla",
                text = "*(She lifts the fine plane, turns it in her hands, sets it down with great care.)* The harvest took him. *(flatly, the only way she can say it.)* You'll have heard how it goes — the *Choir* comes, and marks the *faithless*, and my Davin *served no god*, he served *wood*, he'd say, *\"the grain's the only scripture I trust, Mam\"* — *(her voice catches, steadies)* — and that was *enough*, for *them*, to *take* him. *(she looks at the tools.)* So now I've his *tools.* And everyone says *\"keep them, Orla, make a *shrine*, a *memory* corner\"* — and I *tried*, I *did*, I kept them *home* on the *shelf* where he *left* them, *clean* and *waiting*, and every *morning* I'd *look* at them and they'd *look* back and *neither* of us could *bear* it, because a *carver's* tools *want* to be *carving*, and *sitting* on a *shelf* they were just — *dying* *slower* than he *did.* *(she meets your eyes, fierce now.)* So I'm *selling* them. Not for *coin* — I'd *near* give them *away.* For *use.* I want them in the *hands* of someone *young*, just *starting*, who'll *wear* them *down* to *nothing* making *beautiful* things — because *that's* my *Davin*, you see, *that's* him *continuing*, his *good* tools in *working* hands, his *craft* going *on* in *strangers* who'll *never* know his *name.* *(quietly.)* A *shrine* keeps the *tools* and *loses* the *son.* *Selling* them *loses* the *tools* and keeps — keeps the *carving.* Keeps *him.* That's the *trade* I've *made* my *peace* with. *Mostly.*",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 18] \"You've kept one back. There's a gap in the set — a tool that's not on the blanket. You can sell the whole craft into working hands and still keep your son, but there's one thing your hands won't let go of, and which one it is *is* the whole of him. What did you keep, Orla?\"", nextNodeId = "kept", checkAbility = Ability.Wisdom, checkDC = 18, failNodeId = "compose" },
                    new DialogueChoice { text = "\"You're right that a shrine loses the son. But you've found something better than either keeping or selling — you've found *passing on.* His tools won't rust and they won't sit idle; they'll make beautiful things for fifty years. That's not losing him. That's lending him to the future.\"", nextNodeId = "passing" },
                    new DialogueChoice { text = "\"Let me buy the set — not to use, but to *place.* I know young carvers, apprentices with no tools and good hands. Let me put Davin's chisels where they'll be worn to nothing making beautiful things, and bring you word of what they make.\"", nextNodeId = "buy", effects = new[] { new FlagClause { key = "sq.davins_tools", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 3 } } },
                    new DialogueChoice { text = "\"Tell me about Davin. Not the harvest — the *carver.* 'The grain's the only scripture I trust.' A man who said that was worth knowing. Let me hear him while his tools are still warm from your hands.\"", nextNodeId = "davin", effects = new[] { new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 2 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "kept", speaker = "Goodwife Orla",
                text = "*(Her composure cracks clean down the middle, and her hand goes — unconsciously — to a pocket of her apron, closing around something there.)* ...You *counted* them. *(barely a whisper.)* The *set's* not *complete.* *(slowly, she draws it out: a small, worn carving knife, the handle shaped by years to fit one particular hand.)* His *first* knife. *(she holds it like it's still warm.)* He was *seven* when his *father* — *gone* now too, *years* back — gave it him. *Too big* for a *child's* hand, and he *grew* into it, and the *handle* — *see* — the *handle's* worn to the *shape* of *Davin's* *grip*, *only* his, *no one else's* hand fits it *now*, it's *molded* to a *boy* who *grew* into a *man* who's *gone.* *(her voice breaks.)* *This* one I *can't* sell. The *others* — the *fine* plane, the *good* chisels — they're *tools*, they're *Davin's craft*, and the *craft* should *go on.* But *this* — *(she closes her hand around it)* — this isn't a *tool* anymore. It's the *shape of his hand.* The *one* thing in the *world* that still *holds* the *exact* *grip* of my *boy.* *(she meets your eyes.)* You *asked* which I *kept*, and you're *right* that it's the *whole* of him. The *craft* goes to *strangers*, *gladly* — but the *hand*, the *actual shape of the living hand that held this* — *that* stays with his *mother.* *(quietly, fierce and wet.)* I'll be *buried* with it. So that *somewhere*, *always*, the *shape* of *Davin's* hand is *held* by *someone* who *loved* it. *That's* not a *shrine.* That's a *mother*, *keeping* the *one* part the *harvest* couldn't *take*: the *fit* of his *grip*, *worn* into *wood*, *hers* to *hold* till she *goes* too.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.orla_kept", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "passing", speaker = "Goodwife Orla",
                text = "*(Something eases in her drawn face — the relief of having her choice *named* as a third thing, not a defeat.)* Lending him to the future. *(quietly.)* ...Yes. That's — that's *kinder* than how I'd *put* it to myself. I'd been thinking *\"selling,\"* and *\"selling\"* felt like — like *giving him up*, *piece* by *piece*, for *coin*, a *betrayal* with a *price* on it. *(she touches the fine plane.)* But *lending.* *Passing on.* *(she nods slowly.)* A carver's tools aren't *meant* to be *owned*, are they — they're *meant* to be *used*, and then *handed* down, *master* to *apprentice*, for *generations.* That's how the *craft* has *always* *lived* — not in *shrines*, in *working* hands, *passed* along. *(her voice steadies.)* Davin *got* these from *his* father, some of them. They were *never* meant to *stop* with *him.* The *harvest* *stopped* my *son.* But it doesn't get to *stop* the *tools*, the *craft*, the *passing-on* — *that* I can *keep* *going*, *over* the *harvest's* *head*, by putting them in the *next* pair of *young* hands. *(she meets your eyes, fiercer now.)* So it's not *\"selling my dead son's tools.\"* It's *\"keeping the line unbroken when the harvest tried to break it.\"* *(quietly.)* Thank you for the *word.* *Lending.* I'll *carry* that. It makes the *blanket* feel less like a *funeral* and more like — a *handing-on.* Which is what a *craft* is. Which is what *Davin* would've *wanted*, over any *shrine.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.orla_passing", op = FlagOp.SetTrue }, new FlagClause { key = "act2.cataloguing_defeats_the_wall", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "buy", speaker = "Goodwife Orla",
                text = "*(Her steady composure trembles, and a desperate hope she's been guarding breaks through.)* You'd — *place* them. And bring me *word.* *(she grips the edge of the blanket.)* You don't — you can't *know* what — *(she steadies herself.)* The thing I've *dreaded*, selling them to *passing* strangers, is that they'd *vanish.* That Davin's *chisels* would go off in some *cart* to some *town* and I'd *never* know if they were *carving* beauty or *rusting* in a *drawer* or *sold* again for *scrap.* *(her voice fills.)* The *not-knowing.* That's the *worst* of it. To *let* them *go* and *never* learn what they *became.* *(she meets your eyes, fervent.)* But if *you* place them — with *young* carvers, *good* hands, and *bring me word* of what they *make* — then I'm not *losing* them into the *dark.* I'm *sending* them somewhere I can *follow.* *(she begins, carefully, to wrap the tools.)* Tell the apprentices — tell them the tools were *Davin's*, that he said *\"the grain's the only scripture I trust,\"* that they should *listen* to the *wood* the way he did. *(her hands shake.)* And *come back.* *Even* if it's *years.* Tell me what they *carved.* A *cradle*, maybe. A *door.* A *toy* for some *child.* *(quietly, weeping and smiling.)* Let me *hear* that my boy's *tools* made a *cradle*, somewhere, in *hands* he *never* met. That's — that's the *only* afterlife I *believe* in anymore. The *one* the *harvest* can't *touch*: his *craft*, *carving cradles*, *long* after *they* burned his *name.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.orla_buy", op = FlagOp.SetTrue }, new FlagClause { key = "sq.davins_tools", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "davin", speaker = "Goodwife Orla",
                text = "*(The grief gentles into something warmer as she's invited, for once, to speak of the living boy instead of the taken one.)* Davin. *(she smiles, and it costs her, and she does it anyway.)* He was — *stubborn.* *Gods*, so stubborn. Would *not* be *rushed.* A *customer* would want a *chair* by *market-day* and Davin would say *\"the wood's not ready to be a chair yet,\"* as if the *wood* had *opinions*, and he'd *lose* the *sale* rather than *carve* something *before* it was *right.* *(she laughs softly.)* Drove me *mad.* We were *poor*, and he'd *turn away* coin because the *grain* *\"wasn't speaking to him yet.\"* *(her voice warms.)* But the things he *made* when it *did* speak — *(she shakes her head)* — people would *weep.* He carved a *mourning-box* for the *widow* Pell, for her *husband's* ashes, and he *covered* it in *swifts* — the *birds* — because she'd said her man *loved* to watch them, and when she *saw* it she *sat* down on the *street* and *cried*, and *Davin* just — *stood* there, *awkward*, *patting* her *shoulder*, *mortified*, the way he *always* was when his *work* made someone *feel* too much. *(she meets your eyes.)* That was my *boy.* *Too honest* to *rush* the *wood*, *too shy* to *take* the *credit* when it *broke* your *heart.* *(quietly.)* *That's* who the *harvest* called *faithless* and *took.* A man who thought *wood had opinions* and *carved swifts* for a *widow's* grief. *(her jaw sets.)* If *that's* who the *gods* throw to the *Wall*, then the *gods* can *keep* their *heaven.* My *Davin's* worth *ten* of it.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.orla_davin", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "compose", speaker = "Goodwife Orla",
                text = "*(She gathers her composure back over the crack, smoothing it like a blanket over a sleeping child.)* You're kind to *ask.* *(quietly, closing the subject.)* But I've *said* my piece, and the tools won't *sell* themselves with me *blubbering* over them. *(she straightens the row of chisels.)* They're *good* tools. *Fair* prices. If you've the *hands*, *look* them *over.* If you *don't* — *(her steady, terrible eyes)* — *move* along, and let someone who *does* come *see* them. *(she folds her hands in her lap.)* I'll be *here.* I'm *here* every *market-day.* Selling my *son*, a *chisel* at a *time*, to *anyone* with *hands* enough to *deserve* him. *(and she returns to her quiet vigil over the blanket of tools, composure stretched paper-thin, waiting for the right hands.)*",
                autoNextNodeId = "close",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "Goodwife Orla",
                text = "*(Goodwife Orla sits behind her blanket of a dead son's tools — selling not for coin but so his craft will live on in working hands, keeping back only the one knife worn to the shape of his grip — and whether she showed you the thing she'll be buried with or composed herself back behind her grief, you carry away the quiet defiance of a mother against the harvest: that they could burn her son's name and throw him to the Wall, but they could not stop his chisels from carving cradles in strangers' hands for fifty years, nor unmake the one knife that still holds the exact shape of his living grip.)*",
            });

            NpcHarvestMotherDialogue = g;
        }

        private void BuildNpcHarvestBoyDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.harvest.boy";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "A Boy Who Does Not Speak",
                text = "*(A boy of perhaps ten sits on a step at the edge of the emptied quarter, a stick of charcoal in his hand, drawing on the flagstones — and he does not look up when you approach, does not startle, does not speak. An old woman nearby murmurs without being asked:)* \"You'll get nothing from him, traveler. That's the Vane boy. Hasn't said a *word* since the harvest came through — saw it *take* his mother, they say, right in front of him, and he's not made a *sound* since. Three months now. *(she shakes her head.)* The healers tried. The priests tried. Nothing. He just — *draws.* All day. The same thing, mostly. *(she lowers her voice.)* Won't say what it is. *Can't*, maybe. Poor mite.\" *(The boy keeps drawing, and you see now that the figures under his charcoal are tall, and hooded, and wrong.)*",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.silentboy_met", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "The Silent Boy",
                text = "*(You crouch nearby, not crowding him, and after a long moment the boy's eyes flick to you — measuring, wary, intelligent. He does not speak. But he turns the charcoal in his fingers, and then, deliberately, he slides a clean scrap of parchment toward you, and taps it, and offers the charcoal. An invitation, of a kind: *he* will not speak, but he is asking if *you* will. He watches to see what you'll do with the silence — whether you'll fill it with noise, like the healers and the priests, or whether you'll meet him where he is.)*",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 18] \"*(You don't try to make him talk. You take the charcoal, and on the parchment you draw, simply: a question mark, and beside it, an ear — 'I'm listening, however you want to say it.' Then you wait, and let the silence be his to fill, his way.)*\"", nextNodeId = "listen", checkAbility = Ability.Wisdom, checkDC = 18 },
                    new DialogueChoice { text = "[INSIGHT 16] \"He doesn't speak because the last time speech mattered, it failed — he must have screamed a warning, or cried out, and it changed nothing, his mother was taken anyway. Speech *betrayed* him. So you honor the betrayal: you tell him, quietly, that he never has to speak again to be heard.\"", nextNodeId = "betrayed", checkAbility = Ability.Wisdom, checkDC = 16 },
                    new DialogueChoice { text = "\"*(You sit beside him and look at what he's drawing — the tall hooded figures — and you don't flinch, and you don't shush it. You just look, steadily, at the thing he saw, so he knows someone else can bear to see it too.)*\"", nextNodeId = "see", effects = new[] { new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 3 } } },
                    new DialogueChoice { text = "\"*(Gently:)* You don't have to talk. But those drawings — the hooded ones — they're not nothing, are they. They're *evidence.* You're the one person who saw the harvesters' faces and lived. Will you let me carry your drawings where they'll be seen?\"", nextNodeId = "evidence", effects = new[] { new FlagClause { key = "sq.boys_drawings", op = FlagOp.SetTrue } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "listen", speaker = "The Silent Boy",
                text = "*(The boy studies your drawing — the question mark, the ear — for a long, still moment. And something in his small, guarded face *changes*: the wariness of a child braced for another adult who will *talk at* him, *talk over* him, *demand* he *perform* a *recovery* he hasn't got — eases, because you have, instead, simply *offered to listen* in the *only* language he has *left.* Slowly, he takes the charcoal back. And he draws — not the hooded figures this time, but a smaller scene, careful and deliberate: two figures, a tall one and a small one, holding hands. And then he draws, around the tall one, a circle, and slowly, deliberately, he *scribbles it out* — gone, taken. And then he points at the small figure, left alone, and then he points at *himself*, and then he looks up at you, and his eyes are *streaming*, *silently*, and he has, without a single word, *told you everything*: my mother, and the taking, and the alone. He didn't need his voice. He needed someone willing to read the silence. He leans, very slightly, against your shoulder, and lets the tears come, soundless, finally witnessed.)*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.silentboy_listen", op = FlagOp.SetTrue }, new FlagClause { key = "act5.witness_then_release", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "betrayed", speaker = "The Silent Boy",
                text = "*(The boy goes very still, and his eyes lock onto yours with a sudden, startled intensity — because you have named the thing no one else guessed. Slowly, he nods. Just once. And then he takes the charcoal and draws, fast and hard: a small figure, mouth open wide — *screaming* — and lines coming out of the open mouth toward the hooded figures, and the hooded figures *not stopping*, not even *turning*, the scream landing on them like rain on stone. He taps the screaming mouth. He taps the un-turning figures. And then, deliberately, he draws a line through the screaming mouth — crossing it out — and closes his own lips tight, and looks at you. *He warned them. He screamed. It did nothing. His mother was taken mid-scream.* And so he has concluded, with a child's terrible logic, that *speech is useless*, that his voice *failed at the one moment it had to work*, and he has *abandoned* it as a *broken tool.* You meet his eyes and tell him, quietly, that he never has to speak again to be heard — that his silence is not a *failure*, it is a *verdict* he has every right to, and you will learn to hear him *however* he chooses to be heard. He closes his eyes. And the rigid set of his shoulders — held three months — finally, slightly, *loosens.*)*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.silentboy_betrayed", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "see", speaker = "The Silent Boy",
                text = "*(You sit beside him, and you look — really look — at the hooded figures under his charcoal, the tall wrong shapes of the harvesters, the thing he saw. And you do not flinch, and you do not say *\"don't draw such things,\"* and you do not *shush* it away the way the frightened adults do. You just *look*, steadily, at the horror he carries, so that he knows — for the first time in three months — that *someone else can bear to see it too.* The boy watches your face as you look at his drawing. Watches you *not* turn away. And something he has been carrying utterly alone — the *unbearableness* of being the *only* one who *saw* — shifts, fractionally, onto a *second* set of eyes. He doesn't speak. But he picks up the charcoal and adds one more detail to the hooded figures, a detail he'd left out before because he'd had no one to show it to: between two of the harvesters, a small drawn shape — his mother's face, looking *back*, looking *for him.* He taps it. He taps his own eyes. *She saw me too. At the end. She was looking for me.* And he lets you see *that*, the worst and most precious thing, because you proved you could *look.*)*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.silentboy_see", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "evidence", speaker = "The Silent Boy",
                text = "*(The boy's eyes sharpen, and for the first time something other than grief moves in them — a fierce, focused *purpose.* He understands the word *evidence.* He gathers the scattered scraps around him — and you see now there are *dozens*, weeks of them, the same hooded figures over and over — and he sorts through them with sudden urgency, choosing, and presses a careful selection into your hands. They are not the wild scrawls of a traumatized child. Looked at together, in sequence, they are a *record*: the harvesters arriving, the marking of the faithless, the *taking* — and crucially, on several, a detail rendered with obsessive care: a *symbol* on the harvesters' robes, a sigil, the same one each time, drawn by a child who *saw it up close* and *could not forget it.* He taps the sigil. He taps his own eyes. Then he mimes — carefully — carrying the papers *away*, and holding them *up*, and many eyes *looking.* He cannot say *\"make them answer for what they did to my mother.\"* But he has *drawn* it, and *sorted* it, and *chosen* you to *carry* it, and that is a louder testimony than any words. He looks at you, and for one moment the grief-locked face is fierce as a little judge. Then he nods, once: *go. Make them seen.*)*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.silentboy_evidence", op = FlagOp.SetTrue }, new FlagClause { key = "sq.boys_drawings", op = FlagOp.SetTrue }, new FlagClause { key = "act2.cataloguing_defeats_the_wall", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "The Silent Boy",
                text = "*(The Vane boy bends back over his charcoal at the edge of the emptied quarter — drawing the hooded figures who took his mother, silent for three months and perhaps for years — and whether you read his pictures, honored his abandoned voice, looked steadily at his horror, or carried his drawings out as evidence, you carry away the gentlest lesson the harvest left: that being *heard* was never the same as being *spoken to*, and that the deepest kindness you can do a soul who has lost their words is not to demand them back, but to learn, patiently, to listen in whatever language the grief has left them.)*",
            });

            NpcHarvestBoyDialogue = g;
        }

        private void BuildNpcHarvestHealerDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.harvest.healer";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "Sister Maud",
                text = "*(A healer sits amid her useless supplies — bandages, salves, splints, the tools of a lifetime's mending — outside a house full of the harvest's survivors, and she is not tending anyone. She is staring at her own hands as though they have betrayed her. When she sees you, she laughs, short and bitter.)* Come for a healer? *(she gestures at her kit.)* I've *bandages.* I've *poultices.* I can set a *bone*, close a *wound*, break a *fever*, draw *poison.* *(her voice cracks.)* I can do *none* of it for what's in *that* house. *(she looks at the door.)* Thirty years a healer, and the harvest brought me the *one* wound my whole *life* never *taught* me to *touch.* So *yes*, traveler — come for a healer. You'll find *me* here, *useless* as a *chocolate* *kettle*, surrounded by *tools* that *mend* *everything* *except* what's *actually* *broken.*",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.maud_met", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "Sister Maud",
                text = "*(She turns a roll of bandage over in her hands, not using it, just holding it.)* In *there* — *(she nods at the house)* — there's a *man* whose *wife* was *taken.* He's not *wounded.* Not a *mark* on him. He just — *stopped.* Won't *eat.* Won't *speak.* Stares at the *wall* where her *cloak* still *hangs.* *(she sets the bandage down.)* There's a *girl* whose *whole family* went to the *Wall*, and she's *fine*, *physically*, *perfect* health, and she *screams* in her *sleep* and *claws* her *own* arms *bloody* and I can *bandage* the *arms* but I *can't* — *(her voice breaks)* — I *can't* reach the *thing* that's *making* her *claw* them. *(she looks at her hands.)* Thirty years. I have *mended* this *quarter's* *bodies* through *plague* and *fire* and *childbirth* and *brawls.* I am the *best* healer in the *Lower City* and I am *useless* — *worse* than useless, because they *come* to me, they *expect* me to *fix* it, and I *open* my *kit* and there's *nothing* in it for *grief*, *nothing* for a *soul* the *harvest* *hollowed* out, *nothing*, *nothing*, and I *watch* their *faces* *fall* when they *understand* that the *healer* *can't* *heal* *this.* *(she meets your eyes, anguished.)* So I've *stopped.* I *sit* out here. Because I *can't* *bear* to go *in* and *fail* them with my *hands* *full* of *the wrong tools.*",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 18] \"You think you're failing because you can't *cure* the grief. But the man staring at his wife's cloak doesn't need it cured — that would mean forgetting her, and he'd rather die. He needs someone to *sit* in the room and not flee the unfixable. You haven't run out of healing, Maud. You've confused it with *curing.*\"", nextNodeId = "curing", checkAbility = Ability.Wisdom, checkDC = 18, failNodeId = "bitter" },
                    new DialogueChoice { text = "\"The girl claws her arms and you bandage them and feel useless. But you're *wrong* that the bandaging is nothing. Every time you tend the arms she tore, you tell her — without words — *you are worth tending, even the parts you're destroying.* That's not failure. That's the deepest medicine there is.\"", nextNodeId = "bandage" },
                    new DialogueChoice { text = "\"There's a priestess I met at a bleeding altar who learned this when her gods fell: the holy part was never the cure, it was the *binding.* You can't heal what the harvest did. But you can *be present* with it — and presence, it turns out, is the one medicine that never runs out.\"", nextNodeId = "presence" },
                    new DialogueChoice { text = "\"Thirty years mending bodies, and the first wound you can't fix has stopped you cold. But tell me honestly, Maud — is it *them* you can't bear to fail, or is it that *you* don't know who you are if you're not the one who fixes it?\"", nextNodeId = "identity", effects = new[] { new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 2 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "curing", speaker = "Sister Maud",
                text = "*(The bandage stills in her hands. She stares at it, and slowly, the distinction lands like a key turning.)* ...Curing. Not healing. *(quietly.)* I've — *(she looks at the house)* — I've been treating *grief* like a *fever.* Like a *thing* to be *broken*, *driven* *out*, *fixed*, so the person comes back *\"well\"* — *cloak* *taken* down, *wife* *forgotten*, *normal.* *(her voice shakes.)* And you're *right* that he *doesn't want that.* If I *could* *\"cure\"* him — *reach* in and *take away* the *grief* — I'd be taking away the *last* thing he *has* of *her.* The *grief* *is* the *love*, still *burning*, with *nowhere* to *go.* *Curing* it would be a *second* bereavement. *(she sets the bandage down.)* I've been *standing* at that *door*, *certain* I had *\"nothing\"* for him — because the *only* tool I *reached* for was *\"make it stop.\"* *(she meets your eyes, something dawning.)* But *\"sit in the room and don't flee\"* — *that* I *have.* That's *not* in my *kit*, it's in my — *(she presses a hand to her chest)* — and I *forgot* it was a *healer's* tool at *all*, because no one *taught* me it *counted.* *(she stands, slowly.)* Thirty years and I thought *healing* meant *fixing.* But the *man* with the *cloak* doesn't need *fixing.* He needs a *healer* who can *sit* with the *unfixable* and *not call it failure.* *(quietly, resolved.)* I can *do* that. I've *always* been able to *do* that — I just never *let* myself *count* it as *medicine.* *(she picks up her kit.)* Come *with* me, traveler. I'm going to go *sit* with a man and his *wife's* cloak, and *not try to fix it*, and find out if *presence* was the *tool* I had *all along.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.maud_curing", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "bandage", speaker = "Sister Maud",
                text = "*(She looks at the roll of bandage, and her eyes fill.)* Every time I tend the arms she tore. *(slowly.)* ...I *told* myself it was *pointless.* *\"She'll just *claw* them *again* tonight, what's the *use* of *bandaging*, I'm not *fixing* anything, I'm just — *cleaning up* after a *wound* that *re-opens* by *morning.\"* *(her voice breaks.)* But you're saying the *bandage* *says* something. *(she presses the roll to her chest.)* That *every* time I *clean* and *wrap* the *arms* she *destroys*, I'm telling her — *\"you are worth tending. Even the parts of you that you're trying to* ruin. *Even when you* re-break *what I* fix. *I will* keep *tending you,* every *morning,* because you are *worth* the *re-doing.\"* *(she looks at the house.)* That's — that's not *nothing*, is it. To a *girl* who *claws* herself because some *part* of her believes she *shouldn't* have *survived* when her *family* didn't — a *healer* who *keeps* *tending* her, *keeps* *insisting* she's *worth* the *care*, *every* *single* *morning*, *no matter* how *many* times she *undoes* it — *(her voice fills)* — that's the *one* argument *against* the *clawing* that *might*, *eventually*, *land.* *Not* a *speech.* A *bandage.* *Re-applied.* *Forever* if it *takes* forever. *(she stands, fierce now.)* I've been *bandaging* her *arms* and calling it *failure* because they *re-open.* But the *re-opening* was *never* the *point.* The *re-tending* is. *Thank* you. I'll wrap her arms *every* morning of my *life* if that's what it *takes* to *out-stubborn* the *thing* telling her she's *worthless.* That's a *medicine.* I just *couldn't see* it *working* because it works *too slow* to *watch.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.maud_bandage", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "presence", speaker = "Sister Maud",
                text = "*(She is quiet, turning the idea over with the care of a craftswoman handling an unfamiliar tool.)* The binding, not the cure. *(slowly.)* *Presence* as a *medicine.* *(she looks at her kit, then at her own hands.)* I think — I think I've been *afraid* of *presence*, traveler. Because *presence* doesn't *do* anything you can *see.* A *bandage* you can *point* to. A *fever* breaking you can *measure.* *(her voice tightens.)* But *sitting* with a *grieving* man, *hour* after *hour*, *changing* *nothing*, *fixing* *nothing*, just — *being there* — it *feels* like *doing nothing*, and a *healer* who *does nothing* feels like a *fraud.* *(she meets your eyes.)* And yet. *(quietly.)* When *I* lost my *own* — years back — I *don't* remember the *words* anyone said. I don't remember any *\"cure.\"* I remember *who sat with me.* Who *stayed* in the *room* when there was *nothing* to *do.* Who *didn't flee* my *unfixable* grief. *(her voice fills.)* *That's* what *healed* me. Not a *poultice.* A *presence.* And I *received* it *gratefully*, thirty years ago, and then *spent* thirty years *thinking* it didn't *count* as *healing* because it *left* no *mark* you could *measure.* *(she stands.)* The harvest brought me a wound my *kit* can't touch. But it *also* — *(she presses her hand to her chest)* — it *reminded* me of the *medicine* I *was* *given* and *forgot* I could *give.* *Presence.* The one that *never* runs *out*, because it's not *in* the *kit* — it's just *me*, *staying*, *refusing* to *flee.* I can do *that.* For *all* of them. *Starting* now.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.maud_presence", op = FlagOp.SetTrue }, new FlagClause { key = "act4.faith_through_doubt", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "identity", speaker = "Sister Maud",
                text = "*(The question lands hard, and she flinches, then goes very still, and when she speaks it's with the painful honesty of someone caught by a true thing.)* ...Is it them, or is it me. *(quietly.)* You're a *hard* one, to ask that. *(she looks at her hands.)* ...It's *both.* But the *part* I *don't* say out loud — the part you've *poked* — is the *me.* *(her voice tightens.)* Thirty years, I've *been* *\"the healer.\"* It's *who I am*, in *this* quarter — *\"go to Sister Maud, she'll fix it.\"* My *whole self*, my *whole worth*, my *whole place* in the *world*, is *I am the one who* fixes *it.* *(she meets your eyes.)* And the harvest brought me a thing I *can't* fix — and it's not *just* that I'm *failing* *them*, it's that *without the fixing, I don't know who I* am. *(her voice breaks.)* If I'm *not* the *healer-who-mends*, then I'm just — a *woman* with a *kit* full of *useless* tools, *sitting* in the *dark*, as *helpless* as *anyone.* And *that* — *that* terrifies me more than *failing* them. *(quietly, ashamed.)* So when I *sit* out *here* instead of going *in* — it's *not* only that I *can't* bear to *fail* *them.* It's that I *can't* bear to *meet* the *version* of *me* that *can't* fix it. *(she looks at you.)* You've *named* it. The *useless* feeling isn't *about* the *patients.* It's *grief* — for the *healer* I *was*, who *can't* exist in a *world* with *wounds* this *deep.* *(she draws a shaky breath.)* Maybe I have to *let* *her* die. The *fixer.* And find out if there's a *different* healer *under* her — one who can *help* *without* *fixing.* I don't *know* if there is. But you've made it so I *can't* keep *hiding* out *here* *pretending* the *problem* is *them.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.maud_identity", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "bitter", speaker = "Sister Maud",
                text = "*(She shakes her head and packs a bandage roughly back into her kit.)* *Pretty* words. *(bitterly.)* \"Curing isn't healing,\" \"presence is medicine\" — you sound like the *priests*, traveler, and the *priests* are *no* *use* either. *(she snaps the kit shut.)* I deal in *things that work.* *Bandages.* *Salves.* *Bone-sets.* Things you can *see* *mend.* And for what's in *that* *house*, I have *nothing* that *works*, and *dressing* it up in *philosophy* doesn't *change* that. *(she looks away.)* Go on. Find someone who *wants* a *sermon.* I'll sit here with my *useless* *kit* and at least have the *honesty* to *call* it *useless*, instead of *pretending* that *sitting* and *failing* is some *deep* *medicine.* *(and she stares at the door she cannot bring herself to open, the best healer in the Lower City, defeated for the first time by a wound that leaves no mark.)*",
                autoNextNodeId = "close",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "Sister Maud",
                text = "*(Sister Maud sits with her kit of useless tools outside the house full of the harvest's hollowed survivors — the finest healer in the Lower City, undone by the first wounds her hands cannot mend — and whether you helped her see that presence was the medicine she had all along, or left her guarding the bitter honesty of her helplessness, you carry away the lesson the harvest taught even the healers: that there is a grief no poultice reaches, and that the deepest care was never the curing but the staying — sitting in the room with the unfixable, refusing to flee, and calling that, too, a kind of mending.)*",
            });

            NpcHarvestHealerDialogue = g;
        }
    }
}
