// AUTO-GENERATED by tools/dlg-compile.py from a .dlg source — do not edit by hand.
// Re-generate with: python3 tools/dlg-compile.py
using UnityEngine;
using SunderedCrown.Dialogue;
using SunderedCrown.Stats;

namespace SunderedCrown.Content
{
    public class NetherilDenizensContent
    {
        public DialogueGraph NpcNethVaelDialogue { get; private set; }
        public DialogueGraph NpcNethApprenticeDialogue { get; private set; }
        public DialogueGraph NpcNethKeeperDialogue { get; private set; }
        public DialogueGraph NpcNethWeavedeafDialogue { get; private set; }

        public NetherilDenizensContent()
        {
            BuildNpcNethVaelDialogue();
            BuildNpcNethApprenticeDialogue();
            BuildNpcNethKeeperDialogue();
            BuildNpcNethWeavedeafDialogue();
        }

        private void BuildNpcNethVaelDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.neth.vael";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "Steward Vael",
                text = "*(The floor tilts three degrees. Crystal chandeliers swing. Far below, through the great windows, the ground is *coming up.* And a silver-haired majordomo in immaculate livery glides toward you with a tray of tiny, perfect canapés, not one of which has slid an inch, and bows exactly as deep as your apparent station warrants.)* A refreshment, honored guest, while the enclave... *adjusts its altitude.* *(the floor lurches; he compensates without spilling.)* The salmon is from the Inner Sea, which no longer exists at this elevation, so I should enjoy it promptly. *(a small, perfect smile.)* Is there anything at all I can bring you? We are rather *fully stocked*, as it happens. No one is... checking out.",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.vael_met", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "Steward Vael",
                text = "*(He straightens a painting that will not survive the hour.)* You're looking at me the way they all do, near the end. *(quietly, still smiling, still holding the tray level as the world cants.)* Wondering why the steward doesn't *run.* Doesn't *scream.* Doesn't *pray.* *(he offers the tray again.)* Honored guest, I have served the Seventh Enclave for fifty-one years. I have laid these tables, polished this silver, learned which magelord takes wine and which takes water and which takes a discreet eye turned the *other* way. *(the floor groans.)* And I find, now that the ground is rising to meet us, that I do not know how to be a man who *isn't serving.* I never built one. There was no time; there was always a table to lay. *(he meets your eyes, and the smile holds, but something vast moves behind it.)* So I will serve until the floor stops being a floor. Not from *denial*, you understand. From *love.* It is the only language in which I ever learned to say *I am glad you were here.* A canapé, honored guest? Please. Let me say it to *someone* before the end.",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 17] \"This isn't service anymore. It's a *vigil.* You're not pretending the city won't fall — you're making sure that when it does, the last thing anyone feels is *cared for.* That's not a footman's reflex. That's a priest's.\"", nextNodeId = "vigil", checkAbility = Ability.Wisdom, checkDC = 17, failNodeId = "bow" },
                    new DialogueChoice { text = "\"Then sit with me, Vael. Put the tray down. For five minutes be a *man* I'm glad was here, instead of a steward. The salmon can wait. The ground can wait.\"", nextNodeId = "sit" },
                    new DialogueChoice { text = "\"Fifty-one years of laying tables, and you never built a self outside the service. But the service *was* a self, Vael. A real one. You loved them, in the only grammar you were given. That counts.\"", nextNodeId = "counts", effects = new[] { new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 3 } } },
                    new DialogueChoice { text = "\"Take the canapé, share it with me, and tell me one thing you'd have done if there'd ever been time for a Vael who wasn't serving.\"", nextNodeId = "dream", effects = new[] { new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 2 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "vigil", speaker = "Steward Vael",
                text = "*(The tray dips — just slightly — the first imperfection in fifty-one years.)* ...A vigil. *(the smile finally trembles.)* You're the first to *name* it. They think I'm in *shock*, or *mad*, or too *low* a creature to grasp that we're dying. *(quietly, fiercely gentle.)* I grasp it better than any magelord up there clawing at his teleport-scrolls that won't fire because the Weave is *screaming.* I have *always* grasped what the table is *for*, honored guest. A table is never about the food. It is about the people saying, with forks and candlelight, *we are here, together, and it matters.* *(the city shudders; he steadies the tray by instinct.)* So yes. A vigil. I am keeping the last table of the Seventh Enclave, so that no soul in my care falls out of the sky *unattended.* Frightened, perhaps. But not *unattended.* Never that. *(he straightens.)* I cannot stop the fall. I was never a wizard. But I can make certain the fall is *witnessed* by someone who *gives a damn* — and that, it turns out, is what I was for all along. I just needed the world to end to see it.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.vael_vigil", op = FlagOp.SetTrue }, new FlagClause { key = "act3.witnessed_fall", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "sit", speaker = "Steward Vael",
                text = "*(He looks at the tray. At the canting floor. At you. And then — slowly, as if setting down something that weighs fifty-one years — he places the tray on a side table and *sits.*)* ...There. *(his hands, freed, do not know where to rest.)* Do you know, I cannot recall the last time I sat in this hall. One does not *sit* where one *serves.* *(the city falls; the light through the windows goes strange and golden.)* Five minutes. As a *man.* *(he draws a breath that shakes.)* Then my name is Corin. Vael is the *house* name, the steward's name; my mother called me Corin, before she sold my indenture to the enclave to keep my sisters fed. *(quietly.)* I have not heard it aloud in fifty-one years. *(he looks at you, and the steward is gone, and a person is there.)* Corin. I was glad to be here. Not the *enclave* — the *being.* The mornings. The good silver catching the sun. The one magelord who always said *thank you, Vael* like he meant it. *(the floor tilts further.)* Thank you for the five minutes, honored guest. I shall stand again in a moment and finish the vigil. But I wanted, *once*, to fall as *Corin.* You gave me that. It is the finest tip I have received in half a century.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.vael_corin", op = FlagOp.SetTrue }, new FlagClause { key = "act3.witnessed_fall", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "counts", speaker = "Steward Vael",
                text = "*(The smile holds, but his eyes shine.)* It counts. *(very softly.)* You don't know — you *can't* know — how long I have needed someone to say that the *serving* was *real.* The other servants pity themselves; the magelords pity *us*; everyone treats a life of service as a life *deferred*, a thing one *survives* until one can finally *begin living.* *(he shakes his head.)* But I was *living*, honored guest. Every laid table was a sentence in the only language I had. *I am glad you exist. I want your evening to be lovely. Let me carry the weight you cannot see.* *(the city groans toward the ground.)* That is not a *lesser* love because it wore an apron. *(he picks up the tray again, but gently now, like a thing he's chosen rather than a thing he's bound to.)* You've given me the one gift I could not give myself: the knowledge that my fifty-one years were not a *wait* for a life. They *were* the life. And it was a life of *love*, spoken in silver and salmon and a thousand level trays. I shall finish it level. Thank you. *Truly.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.vael_counts", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "dream", speaker = "Steward Vael",
                text = "*(He accepts this with a courtly tilt of the head, and shares the canapé — a small, absurd communion as the world ends.)* If there had been time for a Vael who wasn't serving. *(he considers it with genuine care, as one considers a serious question.)* ...I would have kept *bees.* *(a soft, surprised laugh.)* Isn't that *foolish.* The world is falling and I tell you I'd have kept *bees.* But I think of it often — a small house, a few hives, the patience of it, the way a bee *serves the hive* without a *master*, only the *work* and the *sweetness.* *(quietly.)* I have served *people* my whole life, and people are kind and cruel by turns. Bees are only ever *bees.* I think I would have liked tending a thing that needed me without ever *commanding* me. *(the floor lurches; he steadies the tray.)* Well. No bees, now. But it was a *good* dream, and I am glad to have spoken it aloud *once*, to someone who asked. Most people never ask the steward what he'd *dream.* You did. That is a kindness I shall carry the rest of the way down.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.vael_dream", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 3 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "bow", speaker = "Steward Vael",
                text = "*(He bows, deflecting your scrutiny with fifty-one years of polished grace.)* Honored guest is kind to take an interest in the help. *(the smile is a perfect, impenetrable wall.)* But there is nothing to *name.* I am merely doing my work, as I always have, as I shall until I *can't.* *(he offers the tray.)* The salmon, truly, is exceptional. Do let me bring you something. It is what I am *for*, and I should so like to be *for* something, in the time remaining. *(and he glides on, level and luminous and utterly unreachable, to lay one more table against the falling sky.)*",
                autoNextNodeId = "close",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "Steward Vael",
                text = "*(The steward moves on through the canting hall — tray level, livery immaculate, the last vigil of the Seventh Enclave kept in canapés and courtesy — and whether he fell as Vael or as Corin, you carry the knowledge that the most dignified soul in a dying magocracy was never a magelord at all, but the man who decided no one in his care would fall out of the sky *unattended.*)*",
            });

            NpcNethVaelDialogue = g;
        }

        private void BuildNpcNethApprenticeDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.neth.apprentice";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "A Boy at a Threshold",
                text = "*(Outside a sealed arcane sanctum, a thin boy of perhaps fifteen stands rigid, hands clasped, staring at a door behind which the air itself screams. Through the gap you glimpse it: a man wreathed in stolen fire, reaching up toward a *spell* the size of a god. The boy does not move. His knuckles are white. He has been standing here, you sense, for a very long time, in a posture of absolute obedience, while the world ends three feet away.)*",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.apprentice_met", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "Karsus's Apprentice",
                text = "*(He speaks without turning, in the flat careful voice of a child reciting a rule he cannot afford to doubt.)* You mustn't go in. *(quietly.)* The Master is *working.* He left an instruction. The last instruction. He said — *(his voice wavers, steadies)* — he said *\"Whatever you hear, whatever you see, do not interrupt me. Not for the world. Not for the sky. Not for anything.\"* And then he sealed the door, and began. *(through the gap, the screaming spell swells.)* I know what he's casting. I'm his apprentice; I read the margins of his book. He is reaching for *Mystryl's* power. To become the *god of magic.* And the Weave cannot *survive* a mortal seizing it — it will *die*, and every spell in the world with it, and the enclaves will fall, *all* of them, because we float on the Weave and the Weave is about to *stop.* *(his white knuckles tremble.)* I could open the door. I could break his concentration. I could *stop it.* The whole apocalypse. With one *word.* *(he stares at the door.)* But he *told me not to interrupt.* And he is the only person in my whole life who ever *wanted me in the room.* So I... stand here. And I don't.",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 18] \"He's the only one who ever wanted you in the room — so opening that door doesn't feel like saving the world. It feels like losing the one person who ever *kept* you. You're not obeying an order. You're protecting a *love.* And it's going to kill everyone.\"", nextNodeId = "love", checkAbility = Ability.Wisdom, checkDC = 18, failNodeId = "recite" },
                    new DialogueChoice { text = "[PERSUADE 17] \"Listen to me. The deepest obedience isn't doing what he *said.* It's doing what he'd *want* if he were sane. He didn't say 'don't interrupt me while I murder the sky.' He said it before he knew. *Save him from the instruction.*\"", nextNodeId = "save", checkAbility = Ability.Charisma, checkDC = 17, failNodeId = "recite" },
                    new DialogueChoice { text = "\"What's your name? Not 'the apprentice.' Your *name.* He never used it, did he. Tell me, and I'll use it, and then you decide about the door as a *person*, not a *function*.\"", nextNodeId = "name", effects = new[] { new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 3 } } },
                    new DialogueChoice { text = "\"I'll open the door, then. You won't have disobeyed — *I* will. Stand aside, and let the disobedience be *mine*, and keep your loyalty clean.\"", nextNodeId = "mine", effects = new[] { new FlagClause { key = "act3.apprentice_spared_choice", op = FlagOp.SetTrue } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "love", speaker = "Karsus's Apprentice",
                text = "*(The boy flinches as if struck, and finally — finally — turns to look at you, and his face is breaking.)* ...The one who *kept* me. *(barely a whisper.)* Yes. *Yes.* That's — nobody understands, they say *just open the door, you stupid boy, the world is ending* — as if the world ending is *worse* than — *(he chokes.)* I was a *foundling.* Nobody wanted me. And the greatest arcanist in the *history of Netheril* looked at me, a nothing, a gutter-child, and said *you. You'll do. Stand in my room.* *(tears now, openly.)* Do you know what that *is*, to a child who was *no one*? He *chose* me. And the door is the *price.* If I open it, I save the sky and I lose the one person who ever *saw* me — because he'll know I *interrupted*, he'll know I *failed* the one instruction, and the seeing will *stop*, and I'll be *no one* again, in a falling world, alone. *(he sobs.)* So you see why I *can't.* It's not the *world* I'm choosing against. It's the *being no one again* I can't survive. *(he turns back to the door, shaking.)* Tell me it's worth it. Tell me being seen for two years is worth — *no.* No, don't. I know the answer. I just can't *make my hand move.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.apprentice_love", op = FlagOp.SetTrue }, new FlagClause { key = "act3.apprentice_grief", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "save", speaker = "Karsus's Apprentice",
                text = "*(The boy goes very still. The argument lands somewhere the orders can't follow.)* ...What he'd *want* if he were sane. *(slowly.)* The deepest obedience. *(he stares at the screaming door, and something shifts in his ruined face — not rebellion, but a *higher* loyalty clicking into place.)* He didn't *know.* When he said *don't interrupt* — he meant *don't break my concentration on a great work.* He didn't mean *let me kill every soul who ever cast a candle-flame.* He didn't *know* the Weave would *die.* *(his voice strengthens.)* If he knew — if the Master I *know*, the one who *chose* me, could see what the spell *costs* — he would *want* to be stopped. He would *command* it. *(the boy's hand rises toward the door, trembling but *moving* now.)* So interrupting him isn't *disobeying* him. It's obeying the man he'd *be* if the hubris hadn't *blinded* him. I'm not breaking faith. I'm *keeping* it — with the *better* Master, the one who'd never want to be the god who *ended magic.* *(he grips the handle, weeping, resolute.)* Forgive me, Master. I'm interrupting you. Because you taught me to think, and *thinking* says you'd thank me. It's the most loyal thing I've ever done. *(to you, fierce through tears.)* Stand back. I'm opening the door.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.apprentice_intervenes", op = FlagOp.SetTrue }, new FlagClause { key = "act3.apprentice_opens_door", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "name", speaker = "Karsus's Apprentice",
                text = "*(The question stops him cold — a thing no one has asked in two years.)* My... name. *(he says it like a word in a dead language.)* It's — *(he has to reach for it.)* — *Eshe.* I'm Eshe. *(quietly, wondering.)* He never used it. Not once. He called me *boy*, or *apprentice*, or *you.* And I told myself that was *intimacy* — that I mattered too much for a *name*, that I was just *his.* *(the screaming door, the white knuckles.)* But you asked, and I had to *dig* for it, and that — that tells me something I've been hiding from, doesn't it. *(slowly.)* A person who *kept* me would know my *name.* He kept my *use.* That's — that's not the same thing. *(he looks at the door with new, terrible clarity.)* Eshe could open that door. *The apprentice* can't — the apprentice is a *function*, and functions *obey.* But *Eshe* is a *person*, and a person can decide the sky is worth more than the one man who used him and never learned he was *Eshe.* *(he breathes.)* Thank you for my name. I think I needed it back before my hand could move. Stand aside... I have a door to open. As *Eshe.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.apprentice_named", op = FlagOp.SetTrue }, new FlagClause { key = "act3.apprentice_opens_door", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "mine", speaker = "Karsus's Apprentice",
                text = "*(Hope and horror war in his face.)* *You'd* — you'd open it. So I wouldn't have to have — *(he grabs at it, desperate, then falters.)* ...No. *(quietly, and it costs him everything.)* No. That's — that's *kind*, and it's a *lie* I want *so badly* to take. But if *you* open it, I'll have *let* you, and *letting* is the same as *doing*, I'm not a *child*, I know that. *(he straightens, shaking.)* And if I let you carry it, then I never *chose*, and I'll spend whatever's left of the world telling myself I'd have stood at that door forever out of *loyalty* — when the truth is I was just *afraid.* *(he meets your eyes.)* If the door opens, *I* have to be the one. Not to save the world — you could do that. To save *me* from being the boy who let someone else be brave so his *loyalty could stay clean.* *(he turns to the door.)* But... stay. Stand with me while I do it. *That* I'll take. Not your hand on the door. Just — *someone there*, when I lose him. So I'm not *no one* the *instant* it's done.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.apprentice_chooses", op = FlagOp.SetTrue }, new FlagClause { key = "act3.apprentice_opens_door", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "recite", speaker = "Karsus's Apprentice",
                text = "*(The boy shakes his head fast, retreating into the rule like a shell.)* No. No, you're *twisting* it. The instruction was *clear.* *\"Whatever you hear, whatever you see, do not interrupt.\"* *(he clamps his hands together.)* I *won't* be the apprentice who failed the one thing. I *won't.* He *chose* me, and choosing comes with *obeying*, that's — that's the *whole* of it, that's the only thing I *know* how to do well. *(the door screams; he squeezes his eyes shut.)* Go away. *Please.* Every word you say makes my hand want to move and I *can't let it*, I *can't*, because if I open that door I lose the only — *(he shudders.)* Just go. Let me obey in peace. It's all I have. It's all I've ever had.",
                autoNextNodeId = "close",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "Karsus's Apprentice",
                text = "*(Whatever you leave him with, the boy stands at the threshold of the end of an age — a foundling who was chosen for his *use* and never asked his name — and the apocalypse behind that door turns, in the space of one trembling hand, on the oldest question there is: whether a child can love someone enough to *disobey* them, and survive being no one again.)*",
            });

            NpcNethApprenticeDialogue = g;
        }

        private void BuildNpcNethKeeperDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.neth.keeper";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "The Mythallar-Keeper",
                text = "*(In the heart of the enclave, a vast crystalline engine pulses — the mythallar, the artifact that holds the whole city aloft — and its light is *wrong*, stuttering amber where it should burn white. A calm woman in keeper's robes makes small adjustments, and as nobles hurry past she calls out, warm and certain:)* \"A momentary flux, my lords! The mythallar is *recalibrating* — perfectly routine! Do enjoy the evening!\" *(they relax; they move on; they believe her. Then she sees you watching, and the warmth on her face does not change at all, but her eyes — her eyes tell you that she knows you know.)*",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.keeper_met", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "The Mythallar-Keeper",
                text = "*(She keeps her voice pitched to carry comfort, but the words she gives *you* are bare.)* You're not a noble. Nobles want to be *told.* You want to *know.* *(she adjusts a failing crystal; the amber stutters.)* So: the mythallar is dying. The Weave it draws from is *screaming* — something has wounded it at the root, far away, and the wound is racing toward us. In perhaps an hour, this engine stops, and when it stops, the Seventh Enclave stops being a *city in the sky* and becomes a *very large rock that was briefly confused about gravity.* *(calmly.)* There is no fixing it. The wound is not *here*; it is in the *Weave itself.* I have known for three hours. *(she turns to you fully.)* And in those three hours, I have told *four hundred souls* that everything is *fine.* I have *lied*, beautifully, continuously, to every frightened face that passed — and I want you to understand, before you judge me, that I did not lie to *save myself.* I lied because the truth buys *nothing* but an hour of *screaming*, and the lie buys an hour of *peace*, and if these are the last hours of four hundred people, I decided they would be *calm* ones. *(her composure does not crack.)* Tell me I was wrong. People do. I have an hour to find out if they're right.",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 18] \"You're not lying *to* them. You're lying *for* them — the way you'd hum to a child in a falling carriage. But you'll never know if you robbed someone of their last *true* hour: a goodbye they'd have said, if you'd let them be afraid.\"", nextNodeId = "robbed", checkAbility = Ability.Wisdom, checkDC = 18, failNodeId = "serene" },
                    new DialogueChoice { text = "[PERSUADE 17] \"There's a third path between panic and a pretty lie. The *quiet* truth — told to the few who can *act.* Not 'we're fine,' not 'we're doomed,' but 'we have an hour; spend it on what matters.' Let me help you tell *that* one.\"", nextNodeId = "third", checkAbility = Ability.Charisma, checkDC = 17, failNodeId = "serene" },
                    new DialogueChoice { text = "\"Who did *you* lie to that you loved, Keeper? There's a specific face behind this much composure. Tell me the one lie that's costing you.\"", nextNodeId = "face", effects = new[] { new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 3 } } },
                    new DialogueChoice { text = "\"You decided four hundred strangers should be calm instead of informed. That's a *god's* decision, made by a tired engineer. I won't tell you it was right. But I'll tell you it was *brave.*\"", nextNodeId = "brave", effects = new[] { new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 2 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "robbed", speaker = "The Mythallar-Keeper",
                text = "*(For the first time the calm wavers — a single crack through perfect porcelain.)* ...The goodbye they'd have said. *(quietly.)* That. *That* is the thing that will follow me down. *(she steadies a failing valve by reflex.)* You see it exactly. I weighed *panic* against *peace* and chose peace — but there's a *third* thing in the scale I tried not to look at: the woman who, *told the truth*, would have run to her daughter's chamber and held her for the last hour. The man who would have *finally said it* to the one he never told. *(her hands still.)* My beautiful lie gave four hundred people a *calm* hour. It also stole, from some unknowable number of them, their *true* one — the goodbye, the confession, the last honest hour they'd have *chosen* if I'd let them be *afraid.* *(she meets your eyes, and the composure is a held thing now, not an effortless one.)* I will never know which I did to whom. That's the keeper's burden — I tend the engine, so I *decide*, and deciding means I'll fall not knowing if I gave peace or *robbed* goodbyes. *(softly.)* I think... I think I'd tell one true person, now. So that at least *one* soul gets the hour they'd choose. Will you help me pick who can *bear* it? I've spent my courage on the lying. I've little left for the truth.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.keeper_robbed", op = FlagOp.SetTrue }, new FlagClause { key = "act3.keeper_tells_truth", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "third", speaker = "The Mythallar-Keeper",
                text = "*(Her eyes sharpen — the engineer recognizing a better solution.)* The quiet truth. *(slowly.)* Not the *lie* that infantilizes and not the *truth* that stampedes. The truth told *narrow* — to the steward who can ready the children, the captain who can keep order, the priest who can shrive the dying. *(she sets down her tools.)* Gods. I framed it as *two* doors — *peace or panic* — and stood between them congratulating myself on choosing the kinder. But you're right, there was always a *third* door, and I didn't open it because the third door requires *trusting people with a piece of the weight*, and I — *(a thin breath)* — I am a *keeper.* I hold the engine *alone.* I hold the *secret* alone. Sharing is not in my training. *(she straightens, decided.)* But an hour is too little to hoard. Help me tell the *right* few — quietly, precisely — so that the last hour of the Seventh Enclave isn't a *lie* or a *riot* but a *city quietly putting its house in order.* Children gathered. Debts forgiven. Hands held by *choice.* *(fiercely calm.)* That's a better falling than I'd planned. I was going to give them a beautiful lie. You've offered me a chance to give them a *dignified truth.* Let's spend the hour well.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.keeper_third_path", op = FlagOp.SetTrue }, new FlagClause { key = "act3.keeper_quiet_truth", op = FlagOp.SetTrue }, new FlagClause { key = "act3.witnessed_fall", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "face", speaker = "The Mythallar-Keeper",
                text = "*(The composure holds, but her voice drops to something private.)* The one I love that I lied to. *(a long pause.)* ...My apprentice. Joss. Nineteen. He stood right *there* an hour ago — *(she nods at a spot by the engine)* — and he *saw* the amber stutter, and he's *clever*, he *knows* the readings, and he looked at me with the question already forming, and I — *(her hands tighten)* — I *smiled* and said *\"recalibration, Joss, fetch me the third lens.\"* And he *believed* me, because I'm his teacher, and he *trusts* me, and he *went to fetch the lens*, calm, while I let him walk away from his own last hour *learning a lie about valves.* *(quietly, the crack widening.)* He's the one. The face behind the composure. I can lie to four hundred strangers and keep my hands steady, but I sent the *boy I love like a son* to fetch a *lens* instead of telling him to *run home to his mother*, and *that* — *(she steadies herself on the engine)* — that one I cannot dress up as mercy. That one was just *cowardice* wearing a teacher's smile. *(she looks at you.)* Find Joss. Tell him the truth I couldn't. Let him spend his hour as *Joss*, not as the apprentice still believing in lenses. *Please.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.keeper_joss", op = FlagOp.SetTrue }, new FlagClause { key = "act3.find_joss", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "brave", speaker = "The Mythallar-Keeper",
                text = "*(Something in her eases, just slightly, at the word she didn't expect.)* Brave. *(a small, tired breath.)* No one's offered me *that* one. *Cold*, I've been called, in the three hours since I started lying — by the one other keeper who knows, who thinks I should *sound the alarm* and let the chips fall. *(she adjusts the dying engine.)* But sounding the alarm is *easy*, you see. It moves the weight *off* me and *onto* four hundred panicking souls. The *hard* thing — the thing I chose — was to *carry* the truth *alone* so that *they* wouldn't have to, and to *spend my own last hour lying* so that *theirs* could be *calm.* *(quietly.)* It may have been *wrong.* I've made my peace with possibly being *wrong.* What I could not bear was being *cowardly* — and you've named it *brave*, and I find that I needed, more than absolution, to be *seen* deciding the hard thing on purpose. *(she returns to the engine, steadier.)* Thank you. Now go — spend *your* hour better than I'm spending mine. Somebody in this city should get to fall *honestly.* I've chosen the lie. Don't *you* be calm. Be *true.* One of us should.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.keeper_brave", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 3 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "serene", speaker = "The Mythallar-Keeper",
                text = "*(The warm, certain mask slides back into place, seamless.)* You're very kind to take an interest in the *engineering.* *(she smiles the smile she gives the nobles.)* But truly — a momentary flux. The mythallar recalibrates; the evening continues; there is *nothing* to trouble yourself over. *(she turns back to the stuttering amber light, her composure a sealed door.)* Do enjoy what's left of the party. The salmon, I'm told, is exceptional. *(and she will not let you in again — she has chosen her lie, and she will keep it beautifully, alone, to the end.)*",
                autoNextNodeId = "close",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "The Mythallar-Keeper",
                text = "*(The keeper turns back to the dying heart of the city — tending an engine that cannot be saved, weighing four hundred calm lies against four hundred true goodbyes — and you carry away the cruelest arithmetic in Netheril: that mercy and cowardice can wear the very same smile, and the only soul who'll ever know which one she chose is the one who has to fall holding the answer.)*",
            });

            NpcNethKeeperDialogue = g;
        }

        private void BuildNpcNethWeavedeafDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.neth.weavedeaf";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "A Calm Child in a Screaming City",
                text = "*(All around, arcanists clutch their heads and shriek — the Weave is dying, and to anyone attuned to it, its death is an unbearable *scream* tearing through the mind. Magelords weep blood. Apprentices claw at their ears. And in the middle of it, on a stone bench, a small girl sits *perfectly calm*, swinging her feet, watching the chaos with the mild interest of someone watching rain. She notices you noticing her stillness.)* You're not screaming either. *(she tilts her head.)* But you're not deaf like me. You hear it. You're just... *used* to terrible noises, I think. *(she pats the bench.)* Sit. You're the first grown-up who's looked at me instead of *through* me all day. Usually I'm the *broken* one. Today I'm the only one not bleeding from the ears, so. *(a small shrug.)* Funny how that works.",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.weavedeaf_met", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "The Weave-Deaf Child",
                text = "*(She keeps swinging her feet, but her child's-voice carries something far older than her years.)* I was born Weave-deaf. It means I can't *hear* magic — can't feel the Weave, can't ever be a wizard, which in *Netheril* is like being born without a *face.* *(matter-of-fact.)* They tested me at four. The arcanist made the special light and asked what color it sang, and I said *lights don't sing*, and his face went all *sorry*, and after that everyone's face went all *sorry* whenever they looked at me. *Poor thing. Weave-deaf. Useless.* *(she watches a magelord collapse, screaming.)* And now the Weave is *dying*, and its dying is the loudest, worst sound there has ever been, and it's killing everyone who can *hear* it — driving them mad, stopping their hearts — and *I can't hear it at all.* *(she turns to you, and her calm is the eeriest thing in the falling city.)* The thing that made me *broken* my whole life is the only reason I'm the one person here who can still *think.* So I've been thinking. Somebody has to. Want to hear what the only calm person in a dying city worked out? I bet I'm right. Nobody ever lets me finish, usually.",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 16] \"Every day of your life they called you broken for not hearing the one thing everyone treasured. And the universe just proved that the 'defect' was the *survival.* You weren't *less.* You were *built for exactly this hour.*\"", nextNodeId = "built", checkAbility = Ability.Wisdom, checkDC = 16, failNodeId = "small" },
                    new DialogueChoice { text = "\"Tell me what you worked out. You're the only clear head in the sky and we're falling — I'd be a fool not to listen to the one person who isn't screaming.\"", nextNodeId = "worked" },
                    new DialogueChoice { text = "\"What's your name? I want to thank the right person when your clear head saves lives. Not 'the Weave-deaf girl.' *You.*\"", nextNodeId = "name", effects = new[] { new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 3 } } },
                    new DialogueChoice { text = "\"Come with me. The arcanists are useless and the engine's failing, but *you* can think, and I need someone who isn't drowning in the scream. Be my clear head.\"", nextNodeId = "come", effects = new[] { new FlagClause { key = "act3.weavedeaf_guide", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 2 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "built", speaker = "The Weave-Deaf Child",
                text = "*(For the first time, the eerie calm cracks — into something much more like a child, eyes filling.)* ...Built for this hour. *(very quietly.)* You really think — *(she scrubs at her eyes, fierce.)* They said *broken* so many times I — I made it my *name*, almost. The broken one. The deaf one. The *sorry-faced* one. I stopped trying to be *good* at things because *what's the point*, a Netherese who can't touch the Weave is a *joke*, a *waste*, a — *(she swallows.)* And now everyone who could touch the Weave is *dying of it*, and I'm sitting here *fine*, and *thinking*, and you're telling me I wasn't *less* — I was *for* something — *(she draws a shaking breath, and the calm that returns is different now, owned.)* That changes it. That changes *everything* about every *sorry* face. They felt sorry for the one thing that's keeping me *alive* and *clear* while they bleed. *(she stands, small and suddenly certain.)* Then I'm not going to *waste* it being sad about being right too late. I'm going to *use* it. Come on. The clear head's getting up. There are people to pull out of the scream before we hit the ground, and I'm the only one who can walk through it without falling down. *Built for this hour.* I'm going to *believe* that. Watch me.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.weavedeaf_built", op = FlagOp.SetTrue }, new FlagClause { key = "act3.weavedeaf_guide", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 5 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "worked", speaker = "The Weave-Deaf Child",
                text = "*(She brightens — *finally*, someone's letting her finish — and lays it out with the crisp logic of a mind that thinks because no scream is stopping it.)* Right. So. Everyone's trying to *fix* the Weave or *escape* on teleport-magic, yes? *(she ticks it off on small fingers.)* Both *stupid.* The Weave's *dying* — you can't fix it, and every spell *fails* now, so teleporting just *splatters* you somewhere instead of *here.* *Magic is the thing that's broken.* So stop using magic. *(she points.)* The enclave is falling, but it's *falling*, not *vanished* — there's *time*, minutes, before the ground. And there are *non-magic* ways down. The cargo-gliders in the under-docks — *cloth and wood*, no Weave, the merchants use them when they don't want to pay the teleport-tax. They *still work*, because they were *never* magic. *(fiercely.)* Everyone's ignoring them because in *Netheril* you don't take the *peasant* way down — magic is for *lords*, gliders are for *cargo.* But the lords are all *bleeding from the ears*, and the *cargo-way* is the only way that *works* when the Weave is dead. *(she grins, sharp.)* The broken girl found the way out, and it's the way they were all too *proud* to look at. Funny how that works. Get people to the under-docks. I'll show you. I'm the only one who can read the way without a *guiding-spell* — because I *never had one.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.weavedeaf_plan", op = FlagOp.SetTrue }, new FlagClause { key = "act3.glider_escape", op = FlagOp.SetTrue }, new FlagClause { key = "act3.weavedeaf_guide", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "name", speaker = "The Weave-Deaf Child",
                text = "*(She blinks, genuinely startled.)* My name. *(slowly, like testing whether it's safe.)* ...It's Sefris. *(quietly.)* Most people don't ask. I'm *the Weave-deaf girl*, or *the Marsh's daughter*, or just *her*, the one you don't put in the wizard-school. *(she studies you.)* You asked like it *matters* which one I am. Like there's a *Sefris* worth thanking and not just a *defect* worth pitying. *(something steadies in her.)* Sefris. Yeah. *(a small, fierce smile.)* You know what — I like hearing it said like that. Like a *name* and not a *diagnosis.* *(she hops off the bench.)* Okay. *Sefris* is going to help you save some people, and when it's over and we're on the ground and not *under* it, you're going to tell whoever's left that *Sefris* did it. Not the deaf girl. *Sefris.* The one who could think when the whole sky was screaming. *(she offers a small hand to shake, solemn as a treaty.)* Deal?",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.weavedeaf_named", op = FlagOp.SetTrue }, new FlagClause { key = "act3.weavedeaf_guide", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "come", speaker = "The Weave-Deaf Child",
                text = "*(She hops off the bench immediately, as if she's been waiting all day to be *asked* to matter.)* *Finally.* *(she falls into step.)* Everyone else today either screamed at me or *prayed* at me or told me to *sit still and be brave*, and not *one* of them said *you can think, come help.* *(she glances up at you, sharp and pleased.)* You did. First one. *(matter-of-fact, walking into the chaos as the arcanists fall around her.)* I can walk through the scream — it's just *quiet* to me, I'll lead. I can find the ways the guiding-spells used to mark, because I learned every hall *by counting steps* instead of by magic — deaf kids do that. *(she takes your hand, small and certain.)* Stay close to the deaf girl, grown-up. Today the deaf girl's the one with *ears.* Come on. Let's go pull people out of a sky that won't stop screaming, and let's do it the *broken* way, which turns out to be the *only* way that *works.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.weavedeaf_joins", op = FlagOp.SetTrue }, new FlagClause { key = "act3.weavedeaf_guide", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 3 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "small", speaker = "The Weave-Deaf Child",
                text = "*(She shrugs, the calm sliding back over whatever you stirred.)* It's okay. You don't have to make it a *whole thing.* *(she swings her feet.)* I'm used to being the broken one. Today it's *useful* broken instead of *sad* broken, that's all. Doesn't mean anything. *(but she watches you a moment longer than her words allow, as if hoping you'll insist it *does* — and when you don't, she just nods, and goes back to watching the screaming city with her terrible, lonely calm.)*",
                autoNextNodeId = "close",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "The Weave-Deaf Child",
                text = "*(The Weave-deaf child sits — or rises — in the heart of the screaming enclave, the one clear mind in a city of bleeding wizards, and you carry away the truest law of the whole falling age: that the thing a proud world calls *broken* is so often the thing built, in secret, for the hour the world breaks — and that the deaf girl counting steps in the dark was always the one who'd know the way down.)*",
            });

            NpcNethWeavedeafDialogue = g;
        }
    }
}
