// AUTO-GENERATED by tools/dlg-compile.py from a .dlg source — do not edit by hand.
// Re-generate with: python3 tools/dlg-compile.py
using UnityEngine;
using SunderedCrown.Dialogue;
using SunderedCrown.Stats;

namespace SunderedCrown.Content
{
    public class PrologueContent
    {
        public DialogueGraph PrologueReservationDialogue { get; private set; }
        public DialogueGraph PrologueWakingDialogue { get; private set; }
        public DialogueGraph PrologueChoirHeraldDialogue { get; private set; }

        public PrologueContent()
        {
            BuildPrologueReservationDialogue();
            BuildPrologueWakingDialogue();
            BuildPrologueChoirHeraldDialogue();
        }

        private void BuildPrologueReservationDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "prologue.reservation";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "The Wall",
                text = "*(There is no speaker. The voice is the architecture itself — a sound like a million held breaths.)* Here is the place kept for you. Read the niche. The name is half-formed; the mortar has not set. You were always going to be here. The only surprise is that you are reading it with eyes.",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "prologue.wall_seen", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "The Wall",
                text = "*(Your own name is being spoken somewhere behind you, over a body that is yours — and one word in it you cannot hold. It slides off the mind like water off glass.)*",
                choices = new[]
                {
                    new DialogueChoice { text = "\"Whose name is that?\"", nextNodeId = "name" },
                    new DialogueChoice { text = "[ARCANA 12] \"This isn't a punishment. It's a filing system.\"", nextNodeId = "filing", checkAbility = Ability.Intelligence, checkDC = 12, failNodeId = "cold" },
                    new DialogueChoice { text = "\"I don't belong here.\"", nextNodeId = "refuse", effects = new[] { new FlagClause { key = "prologue.refused_wall", op = FlagOp.SetTrue } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "name", speaker = "The Wall",
                text = "Yours. It has always been yours. The word you cannot keep is the one that makes you a person instead of a vacancy. Someone is saying it now. Someone will forget it. *(A long, patient silence.)* So will you.",
                autoNextNodeId = "pull",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "filing", speaker = "The Wall",
                text = "*(For the first time the voice seems almost to attend to you.)* ...A cold way to put it. A true one. We are the souls no ledger wanted. Filed under nothing. You read quickly, for the newly dead. *(beat)* You will need that.",
                autoNextNodeId = "pull",
                onEnter = new[] { new FlagClause { key = "prologue.wall_insight", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "cold", speaker = "The Wall",
                text = "Doubt is the crime, little vacancy. You will learn the punishment by living inside it. Read your niche. Wait your turn.",
                autoNextNodeId = "pull",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "refuse", speaker = "The Wall",
                text = "*(The held breath of a million almost laughs.)* No one belongs here. That is the entire point. Belonging was the thing you all lacked. *(The mortar at the edge of your name has not set.)* ...And yet yours is the one that did not take. Curious. Hold that thought. Something else has hold of it too.",
                autoNextNodeId = "pull",
                onEnter = new[] { new FlagClause { key = "prologue.crack_seeded", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "pull", speaker = "The Wall",
                text = "*(Far off, a hand on your true chest. A pull, like a hook behind the navel. The Wall recedes — unwilling, for the first time in its existence, to let one go.)*",
            });

            PrologueReservationDialogue = g;
        }

        private void BuildPrologueWakingDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "prologue.waking";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "Sister Garrow",
                text = "*(Grey robes, a grave-warden's lantern, a face that has buried more people than it has loved.)* Be still. You stopped breathing on this slab a quarter-hour past. I closed your eyes myself. And now they are open, and Kelemvor's seal on your soul is — *(she falters, a priest losing her certainty)* — torn. Cleanly. From the inside.",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "prologue.garrow_met", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "Sister Garrow",
                text = "I have served the Lord of the Dead forty years. I have never once seen a thing come back. So I will ask plainly, and your answer decides whether I help you up or put you down: do you know what you are?",
                choices = new[]
                {
                    new DialogueChoice { text = "\"I saw the Wall. My name is in it.\"", nextNodeId = "wall", effects = new[] { new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 5 }, new FlagClause { key = "prologue.told_garrow_wall", op = FlagOp.SetTrue } } },
                    new DialogueChoice { text = "\"I don't know. But something pulled me back.\"", nextNodeId = "pulled", effects = new[] { new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 3 } } },
                    new DialogueChoice { text = "[INSIGHT 13] \"You're not afraid of me. You're afraid you've been lied to for forty years.\"", nextNodeId = "doubt", checkAbility = Ability.Wisdom, checkDC = 13, failNodeId = "guard" },
                    new DialogueChoice { text = "\"Put me down, then. If you can.\"", nextNodeId = "defiant", effects = new[] { new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 2 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "wall", speaker = "Sister Garrow",
                text = "*(She goes very still.)* The Wall of the Faithless. You saw it from the inside and walked out the wrong way. *(She helps you sit, and her hands are shaking, and she is ashamed of it.)* Then the doctrine I have preached over a thousand graves is at best incomplete. I would rather know that than be comfortable. Come. The Cinderhaunt is no place to be newly alive.",
                autoNextNodeId = "escape",
                onEnter = new[] { new FlagClause { key = "prologue.garrow_shaken", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "pulled", speaker = "Sister Garrow",
                text = "Something. *(dry)* In my experience, child, \"something\" with the strength to unmake Kelemvor's own seal is rarely benign. We will find out together what has its hand on you. On your feet. The harvesters will have heard your heart restart.",
                autoNextNodeId = "escape",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "doubt", speaker = "Sister Garrow",
                text = "*(The lantern trembles, just once.)* ...You read the living as easily as the dead read you. Yes. If you are real — and you are insultingly warm for a corpse — then someone has been wrong for a very long time, and I have helped them be wrong. I intend to make that right. Starting with getting you out of here. Move.",
                autoNextNodeId = "escape",
                onEnter = new[] { new FlagClause { key = "prologue.garrow_doubt", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 8 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "defiant", speaker = "Sister Garrow",
                text = "*(A grim flicker that might, in better light, be respect.)* No. I don't think I can. And a thing I cannot put down is a thing I had best understand. Walk with me, Returned. The exit is through the harvest-floor, and the harvest is not finished.",
                autoNextNodeId = "escape",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "guard", speaker = "Sister Garrow",
                text = "Spare me the cold-reading, corpse. Better confessors than you have tried. *(She offers a hand anyway.)* Up. Questions later. Knives now.",
                autoNextNodeId = "escape",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "escape", speaker = "Sister Garrow",
                text = "Stay behind me until you remember how your own legs work. When the Returned come — and they will — strike for the joints, not the heart. They have no more use for hearts than you did, an hour ago.",
            });

            PrologueWakingDialogue = g;
        }

        private void BuildPrologueChoirHeraldDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "prologue.choir_herald";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "Choir Herald",
                text = "*(A masked acolyte of the Faithless Choir, frozen at the cellar mouth, staring at you like a sum that won't add.)* No. No, you're — I sealed that door. I read the rites. You were *filed.* They don't — *(his voice cracks behind the mask)* — they never come back. Not once. Not in all the years.",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "prologue.herald_met", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "Choir Herald",
                text = "He'll want to know. Gods help me, he'll *want* you. *(He backs toward the stair, hands raised.)* I'm not your enemy. I'm not — we're trying to *end* the Wall, do you understand? The man who runs us watched it take his own daughter. If you are what you are, then you are the thing he has prayed twenty years to find.",
                choices = new[]
                {
                    new DialogueChoice { text = "\"Who is he?\"", nextNodeId = "name" },
                    new DialogueChoice { text = "[PERSUADE 14] \"Then take me to him. No tricks.\"", nextNodeId = "escort", checkAbility = Ability.Charisma, checkDC = 14, failNodeId = "flee" },
                    new DialogueChoice { text = "\"I'm no one's miracle. Run.\"", nextNodeId = "dismiss", effects = new[] { new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 3 } } },
                    new DialogueChoice { text = "\"...\"", nextNodeId = "flee" },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "name", speaker = "Choir Herald",
                text = "Aldric Morn. *(He says it the way some say a saint's name and others say a curse — and isn't sure which he means.)* The Heretic of the Lower City. Forty years a Doomguide, until he stopped believing the dead were being kept and started believing they were being *thrown away.* Find a chandler's shop with a kettle always on. He'll be expecting you. He's been expecting you for twenty years.",
                autoNextNodeId = "gone",
                onEnter = new[] { new FlagClause { key = "aldric.name_known", op = FlagOp.SetTrue }, new FlagClause { key = "prologue.points_to_aldric", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "escort", speaker = "Choir Herald",
                text = "*(He hesitates, then nods, fast.)* ...Yes. Yes, all right. But not like this, not bleeding, not with a Doomguide of Kelemvor at your shoulder — *(he glances at Garrow)* — she'll have us both in cells. Go up, go quiet, find the kettle. Tell him the herald sent you. Tell him... tell him it's true. After all this time, it's *true.*",
                autoNextNodeId = "gone",
                onEnter = new[] { new FlagClause { key = "aldric.name_known", op = FlagOp.SetTrue }, new FlagClause { key = "prologue.herald_ally", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = -2 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "dismiss", speaker = "Choir Herald",
                text = "*(Something in him sags with relief and grief at once.)* ...Maybe you're right. Maybe a miracle should get to choose. *(He turns to flee, then stops.)* His name is Aldric Morn. If you ever want to know what you are — that's the man who's spent his life asking. For what it's worth. For whatever you are.",
                autoNextNodeId = "gone",
                onEnter = new[] { new FlagClause { key = "aldric.name_known", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "flee", speaker = "Choir Herald",
                text = "*(He's already gone up the stair, three steps at a time, shouting a name into the dark above — Aldric, Aldric, it's true — and the word follows you out of the Cinderhaunt like a hook already set.)*",
                autoNextNodeId = "gone",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "gone", speaker = "Sister Garrow",
                text = "*(quietly, beside you)* Aldric Morn. I knew him, Returned. Before. He was the best of us. *(She looks at the stair the herald fled up, and her grave-warden's face is, for once, simply afraid.)* Which is exactly why I want to reach him before he reaches you.",
                onEnter = new[] { new FlagClause { key = "prologue.complete", op = FlagOp.SetTrue } },
            });

            PrologueChoirHeraldDialogue = g;
        }
    }
}
