// AUTO-GENERATED by tools/dlg-compile.py from a .dlg source — do not edit by hand.
// Re-generate with: python3 tools/dlg-compile.py
using UnityEngine;
using SunderedCrown.Dialogue;
using SunderedCrown.Stats;

namespace SunderedCrown.Content
{
    public class SpellplagueDenizensTwoContent
    {
        public DialogueGraph NpcPlagueCausalityDialogue { get; private set; }
        public DialogueGraph NpcPlagueWitnessDialogue { get; private set; }

        public SpellplagueDenizensTwoContent()
        {
            BuildNpcPlagueCausalityDialogue();
            BuildNpcPlagueWitnessDialogue();
        }

        private void BuildNpcPlagueCausalityDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.plague.causality";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "A Small Frantic Clerk",
                text = "*(A diminutive figure in a clerk's eyeshade stands amid the blue-fire chaos with a great ledger and a look of profound professional outrage, attempting to herd events into a queue. As you watch, a raindrop falls *upward*, a man ages backward three seconds and forward five, and a sound arrives before the thing that makes it. The clerk makes a strangled noise and stamps something.)* NO. *(to the rain.)* No, no, no — you fall *down*, you fall *down* and *then* you make the *splash*, that is the — *(the splash happens; the drop follows)* — that is *backwards*, that is — *(he sees you)* — oh, thank the *vanished gods*, a *person*, a *sequential* person — you *do* still experience *one-thing-then-another*, don't you? *Please* tell me you do. I am *losing my mind*, except I can't even be sure I *have* it *yet*, the way things are *going.*",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.causality_met", op = FlagOp.SetTrue }, new FlagClause { key = "act4.spellplague_witnessed", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "The Clerk of Causality",
                text = "*(He flips through his ledger, which keeps re-paginating itself.)* Allow me to introduce myself, which is *difficult*, because the Spellplague *murdered* the *Weave*, and the Weave is — *was* — the *substrate* that *enforced* the rule I *administer.* *(he draws himself up to his unimpressive height.)* I am *Causality.* Or his — *clerk*, his *avatar*, his *local representative* — the *principle* that *this* happens *because* of *that*, that *effects* follow *causes*, that you *strike* the flint *and then* you get the *spark* and *not* the *reverse.* *(he gestures despairingly at the unraveling world.)* And I am *LOSING.* Events are happening *out of order.* Consequences *precede* their *deeds.* People *regret* things they have *not yet done* and *celebrate* victories that *un-happen.* *(he sags.)* And everyone treats me as a *joke* — the *little clerk* shouting *\"in order! in order!\"* at a *hurricane.* *(quietly, and here the comedy turns.)* But do you understand what I am *fighting* for, sequential one? If *cause* no longer *yields* effect — if *nothing* you *do* reliably *leads* to *anything* — then *nothing you do* ***means*** *anything.* No *deed* has a *consequence.* No *kindness* leads to a *result.* No *choice* ***matters***, because *choosing* is just *betting* that *this* will cause *that*, and I — *(his voice cracks)* — I am the *rule* that makes *meaning* ***possible***, and I am *failing*, and if I *fall*, then *every* story, *every* life, *every* *\"and so, because of what she did...\"* — *all* of it becomes *noise.* I am not fighting for *tidiness*, stranger. I am fighting for the possibility that *anything anyone does* ***counts.***",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 18] \"You think you're losing because the world's gone non-sequential. But meaning never lived in the *order*, clerk — it lives in the *connection.* A kindness 'counts' not because it comes *before* a result, but because someone *witnessed* it and *carried* it forward. *Memory* enforces meaning where *time* can't.\"", nextNodeId = "memory", checkAbility = Ability.Wisdom, checkDC = 18, failNodeId = "frantic" },
                    new DialogueChoice { text = "\"If causality's dying, then the one place meaning can still live is in *choices made without knowing they'll pay off.* A deed done with no guarantee of consequence isn't *meaningless* — it's the *purest* kind. You're not the clerk of meaning. You're the clerk of *reward.* Let it go.\"", nextNodeId = "reward" },
                    new DialogueChoice { text = "\"What happens to *you* if you lose? Does Causality just... stop? Or does the little clerk keep standing in the hurricane shouting 'in order' forever, because someone has to, even when no one's listening?\"", nextNodeId = "lose", effects = new[] { new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 2 } } },
                    new DialogueChoice { text = "\"Here's a sequence I can promise you holds: I am going to *thank* you, and *then* you are going to feel *slightly* less alone. Cause, and effect. One small place where the rule still works — because I'm *choosing* to make it.\"", nextNodeId = "small", effects = new[] { new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 3 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "memory", speaker = "The Clerk of Causality",
                text = "*(He stops mid-stamp. The ledger goes still in his hands. He stares at you as a man stares at a column that finally *balances.*)* ...Memory enforces meaning where time can't. *(slowly.)* Oh. *Oh.* *(he sits down heavily on a chunk of floating masonry.)* I have been — I have spent this entire *catastrophe* trying to *re-impose the order* — to *force* cause *back* in front of effect, *physically*, in *time* — and *failing*, because the *Weave* that *let* me do that is *dead.* *(he looks at his ledger with new eyes.)* But you're saying *meaning* never *needed* the *temporal* order at all. That when someone does a *kindness*, and another *remembers* it, and *carries* it, and *acts* differently *because* they *hold* it — *that* connection, *that* \"because,\" lives in the *rememberer's mind*, not in the *clock.* *(he stands, electrified.)* *Memory* is a *second causality!* A *cause* and *effect* linked not by *time* but by *a witness who holds them together!* *(he flips frantically to a fresh page.)* Then I am *not* obsolete! The Weave-causality is *dead* — but *memory-causality* cannot be *plague-changed*, because it doesn't live in the *Weave*, it lives in *people who remember*, in *people who carry*, in — *(he looks at you, joyous.)* — in *exactly* the thing your whole *road* has been *built* on! *Names kept!* *Records made!* *Songs sung!* *That's* causality *surviving its own substrate* — *meaning, enforced by memory, when time itself has failed!* *(he stamps his ledger triumphantly.)* I shall *relocate the office.* From *time*, which is *lost* — to *memory*, which *endures.* Thank you, sequential one. You've just saved *meaning itself*, and you did it *out of order*, which I shall *graciously* allow this *once.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.causality_memory", op = FlagOp.SetTrue }, new FlagClause { key = "act4.meaning_lives_in_memory", op = FlagOp.SetTrue }, new FlagClause { key = "act2.cataloguing_defeats_the_wall", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "reward", speaker = "The Clerk of Causality",
                text = "*(He bristles — then deflates, then looks at you with the wounded honesty of a bureaucrat shown his own job description.)* The clerk of *reward.* *(quietly.)* That's — that's *unkind*, and *accurate*, which is the *worst* combination. *(he sags onto his ledger.)* You're saying I've conflated two things. *Meaning* — *\"this deed mattered\"* — and *reward* — *\"this deed paid off.\"* And I've been *defending* meaning while *actually* clutching *reward*: the *guarantee* that if you do *good*, *good* *follows*, in *order*, *reliably*, like a *receipt.* *(he looks at the chaos.)* And *that* — the *receipt* — *is* what the Spellplague *killed.* You *can't* be *sure* anymore that *kindness* leads to *anything.* *(slowly, the despair turning over into something braver.)* But you say a deed done with *no guarantee of consequence* isn't *meaningless* — it's the *purest* kind. *(he frowns, working it.)* Because if I *only* do good *when* I can *count* on the *reward*, then I'm not *good*, I'm just *transacting.* But if I do good *into a hurricane* — *not knowing* if cause will *ever* yield effect, *not knowing* if it *counts*, and *choosing* it *anyway* — *(he stands, shaky.)* — *that's* the only *meaning* the *Weave* never gave and *can't* take away. *(quietly.)* You've demoted me from *clerk of meaning* to *clerk of reward*, and then shown me that *losing the reward* is what *finally* makes *meaning* ***free.*** *(a rueful, liberated laugh.)* I think I'll *resign* the *reward* office. It was a *tyrant* of a job anyway. *Let* deeds be *unrewarded.* They were *never* less *meaningful* for it. *You* certainly aren't.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.causality_reward", op = FlagOp.SetTrue }, new FlagClause { key = "act4.meaning_without_reward", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "lose", speaker = "The Clerk of Causality",
                text = "*(The frantic energy drains, and he looks, suddenly, very small and very tired.)* What happens to me. *(quietly.)* ...I don't *know.* That's the *honest* answer, and I *hate* honest answers, they're so *unsequential.* *(he looks at his ledger.)* Perhaps Causality *\"stops\"* — though *\"stops\"* is a *temporal* word, and if I'm *gone*, there's no *time* for me to *stop* *in*, so even my *ending* is — *(he waves a hand)* — *paradoxical*, *typical*, *infuriating.* *(he meets your eyes, and the comedy falls away entirely.)* But here is what I *think* happens, and it's the thing that *keeps me standing in the hurricane*: I think the little clerk *keeps shouting* \"*in order, in order*\" *forever* — *not* because anyone's *listening*, *not* because it *works*, but because *someone has to hold the* idea *of order* — the *memory* that there *was* such a thing as *one-thing-then-another*, that *deeds* once *led* to *consequences* — *alive*, *even* in a world that's *forgotten* it. *(softly.)* If *I* stop *believing* in *sequence*, then *no one* does, and then it's not just *broken* — it's *un-rememberable.* So I *shout.* Into the *wind.* The *last* witness that *meaning* was ever *possible.* *(he straightens, picks up his stamp.)* It's a *thankless, hopeless, eternal* post. *(a small, brave smile.)* But you'd be *astonished*, sequential one, how *many* of the *best* posts are.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.causality_lose", op = FlagOp.SetTrue }, new FlagClause { key = "act4.held_the_post", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "small", speaker = "The Clerk of Causality",
                text = "*(He blinks at you — and then, as you thank him, and as the promised small warmth visibly lands, his whole face *transforms*, the way a drowning man's does when his foot touches bottom.)* ...You did it. *(he whispers.)* Cause — *(you thanked him)* — and *effect* — *(he feels less alone)* — *in* *order.* *On purpose.* *(he clutches the ledger to his chest.)* In the *middle* of a *hurricane* that *un-sequences* *everything*, you *manufactured* — by *choosing* it — *one* clean *link* of *cause-and-effect*, and you did it with the *one* material the Spellplague *can't* corrupt: a *deliberate human kindness*, *witnessed* and *received.* *(his eyes shine.)* That's the *secret*, isn't it. Causality isn't *dead.* It's just *stopped being automatic.* The *Weave* used to *enforce* it for *free* — every cause *yielding* its effect *whether* anyone *meant* it or not. *(fiercely, joyously.)* And *now* — now it has to be *chosen.* *Hand-made.* *Deed* by *deed*, by *people who decide* *\"I will do this, so that that may follow,\"* and *mean* it, and *make* the link *hold* by *force of will and memory.* *(he stamps his ledger.)* You haven't *saved* the *old* causality. You've shown me the *new* one: *the kind people make on purpose, one kindness at a time.* It's *slower.* It's *harder.* It requires *intention.* *(he beams.)* It's *infinitely* better. Thank you, sequential one. You just *caused* something. *On purpose.* In a world that said you *couldn't.* Go *cause* some *more.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.causality_small", op = FlagOp.SetTrue }, new FlagClause { key = "act4.meaning_lives_in_memory", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "frantic", speaker = "The Clerk of Causality",
                text = "*(He's already turned away, stamping at a sunbeam that arrived before its dawn.)* No time, no time — well, *no order*, which is *worse* than no time — *(he chases an effect back toward its cause)* — I can't *philosophize*, sequential one, I have to *re-shelve* the *afternoon*, it's gotten *in front of* the *morning* again — *(stamp)* — *in ORDER*, you wretched hours, *in ORDER* — *(and he scurries off into the chaos, the little clerk of cause-and-effect, shouting his hopeless liturgy at a world that has stopped listening, too frantic to hear that he'd already been told how to win.)*",
                autoNextNodeId = "close",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "The Clerk of Causality",
                text = "*(The clerk of causality stamps and shouts amid the blue-fire chaos — the bureaucrat of meaning itself, fighting to keep \"and so, because of what she did\" from dissolving into noise — and whether you showed him that meaning could relocate from time into memory, or left him shouting into the hurricane, you carry away the strange comfort at the bottom of the Spellplague: that when the rule which made deeds matter *automatically* finally breaks, meaning does not die — it simply has to be *made by hand*, one chosen kindness at a time, by people stubborn enough to insist that what they do still *counts.*)*",
            });

            NpcPlagueCausalityDialogue = g;
        }

        private void BuildNpcPlagueWitnessDialogue()
        {
            var g = ScriptableObject.CreateInstance<DialogueGraph>();
            g.conversationId = "npc.plague.witness";
            g.startNodeId = "0";

            g.nodes.Add(new DialogueNode
            {
                id = "0", speaker = "A Woman With a Hole in Her Memory",
                text = "*(A woman sits very still against a blue-scarred wall, holding her own head as though it might come apart, and there is a particular terror in her — not the terror of someone who *remembers* something awful, but of someone who *almost* does, who can feel the *shape* of a horror pressing against a place where the memory should be and isn't.)* Don't — *(she flinches at your approach, then steadies)* — sorry. Sorry. I thought you might be — *(she searches your face)* — no. I don't know *who* I thought you might be. That's the *trouble.* *(she laughs, thin and frightened.)* I *saw* something. I *know* I saw something. Something *important*, something *terrible*, the kind of thing you *build the rest of your life around having seen.* And the Spellplague — *(she presses her temple)* — the blue fire came through, and it *reached into my head*, and it *took the seeing out*, and left the *hole* where it *was.* And the *hole* remembers being *full.* That's the *worst* part. The *hole* remembers.",
                autoNextNodeId = "1",
                onEnter = new[] { new FlagClause { key = "npc.witness_met", op = FlagOp.SetTrue }, new FlagClause { key = "act4.spellplague_witnessed", op = FlagOp.SetTrue } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "1", speaker = "The Witness",
                text = "*(She speaks carefully, as though circling a pit in the dark.)* Here is what I *have.* *(she counts the fragments.)* I was *somewhere I shouldn't have been.* It was *night.* There were *two* figures. One of them — *(she frowns, straining)* — one of them *killed* the other. A *murder.* And it wasn't — *(she shivers)* — it wasn't a *robbery*, a *brawl*, a *normal* killing. It was something *worse.* Something that *mattered* beyond the two of them. *(her hand trembles.)* And the *thing* I *can't* shake — the splinter the plague *left* — is that the *killer* turned, *after*, and *looked* at me. *Saw* me *see.* And the *face* — *(she squeezes her eyes shut)* — the face was — *familiar.* Not a *stranger's* face. A face I *knew*, or *would* know, or — *(she opens her eyes, desperate.)* And then the *blue fire*, and the *hole*, and now I *can't* recover it, and *part* of me is *grateful*, because whatever I *saw* was the kind of thing that gets a *witness* killed — but *part* of me *can't live* with the *hole*, because that *murder mattered*, and I'm the *only* one who *saw*, and if I *don't* remember it, then it's like it *never happened*, and *someone* got *away* with something *the whole world* should *know.* *(she looks at you.)* Help me decide, stranger. Do I *dig it back up* — and maybe die of what I *learn* — or do I let the plague's *mercy* stand, and let the *hole* keep its *secret*, and keep *me* *safe* and *hollow?*",
                choices = new[]
                {
                    new DialogueChoice { text = "[INSIGHT 18] \"The face was familiar because you'd seen it before — or *will.* A murder that 'mattered beyond the two of them,' a killer who knew you'd matter as a witness, a face out of its own time. You didn't see a *crime*, you saw a *loop.* And the plague didn't erase it to hurt you. It erased it to *protect the killer's secret.*\"", nextNodeId = "loop", checkAbility = Ability.Wisdom, checkDC = 18, failNodeId = "fragile" },
                    new DialogueChoice { text = "\"The plague's 'mercy' isn't mercy — it's *editing.* Someone or something decided you shouldn't have seen, and the blue fire was the *eraser.* A blank that was *imposed* on you isn't peace. It's a *cover-up* you're hosting in your own skull. You have a right to your own eyes.\"", nextNodeId = "coverup" },
                    new DialogueChoice { text = "\"Don't dig it all up at once — that's what terrifies you, the whole horror landing in one blow. Reconstruct it *slowly*, with a witness of your own. Me. One fragment at a time, with someone beside you, so you never have to face it alone.\"", nextNodeId = "slowly", effects = new[] { new FlagClause { key = "sq.reconstruct_the_murder", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 3 } } },
                    new DialogueChoice { text = "\"Maybe the kindest thing isn't to make you remember. Maybe it's to ask: if the hole stays, can you *live* with not-knowing — truly live, not just survive? Because a hollow safety that eats you slowly isn't safer than a terrible truth.\"", nextNodeId = "live", effects = new[] { new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 2 } } },
                }
            });

            g.nodes.Add(new DialogueNode
            {
                id = "loop", speaker = "The Witness",
                text = "*(She goes white, and her hand flies to her mouth, and the fragments you've named click into a shape that terrifies her far more than the blank did.)* ...A *loop.* *(barely a whisper.)* A face *out of its own time.* *(she stares at you.)* That's — that's *why* it felt *familiar* and *impossible* at *once.* I *knew* the face and I'd *never seen* it, *both*, and I thought I was *going mad*, but you're saying — *(she shudders)* — the killer was *someone who'd been here before.* Someone *looping.* And the one they *killed* — *(her eyes widen)* — *also* looping? One *version* killing *another?* *(she grips her knees.)* And they *looked at me* because — because a *witness* to a *loop-murder* is *dangerous*, I could *tell* someone, I could *break* the *secret* that the *loop* depends on *no one knowing* — so the *plague*, or *whatever rides* the plague, *reached in* and *took it*, not to *spare* me but to *spare the killer.* *(she looks at you with dawning, vertiginous horror.)* I'm not a *traumatized survivor.* I'm a *deleted witness.* The *hole* in my head is a *crime scene someone tidied.* *(her voice shakes.)* And *you* — you *knew* the shape of it *before I said it.* Which means *you* know about the *loop.* Which means — *(she searches your face, half-terrified, half-hoping)* — *stranger.* Was it *your* face? The one I *saw*? *Tell* me. Is the killer I witnessed *you* — or *something* that *wears* you?",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.witness_loop", op = FlagOp.SetTrue }, new FlagClause { key = "act4.deleted_witness", op = FlagOp.SetTrue }, new FlagClause { key = "act3.loop_glimpsed", op = FlagOp.SetTrue }, new FlagClause { key = "companion.ilfaeril.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "coverup", speaker = "The Witness",
                text = "*(Something hardens in her frightened face — the particular anger of someone who's just realized their peace was *done to them.*)* A cover-up I'm *hosting.* *(slowly.)* In my own *skull.* *(she lowers her hands from her head.)* I've been treating the *hole* as a *wound* — something the plague *did* to me, *random*, like the rain falling up. *(her jaw sets.)* But you're right that it's too *neat.* The plague *un-sequenced* the *whole world* — and yet it reached into *my* head and *surgically* removed *one specific memory*, the *one* that was *dangerous to someone*, and left *everything else*? *(she stands, unsteady but furious.)* That's not *chaos.* That's *targeting.* That's a *hand* using the plague as a *tool*, to *edit* a *witness.* *(quietly, fiercely.)* And everyone's been *telling* me to be *grateful.* *\"The plague spared you the trauma. Let it lie. The blank is a blessing.\"* *(she shakes her head.)* It's *not* a blessing. It's a *gag.* Someone *reached into my mind* and *decided what I'm allowed to know about my own life*, and *dressed* it as *mercy*, and I have been *thanking* them for it. *(she looks at you, resolved and scared.)* I want my *eyes* back. Not because the truth is *safe* — it *isn't*, you've made that *clear* — but because *no one* gets to *edit* what I *saw* and call it *kindness.* The *memory* is *mine.* The *seeing* is *mine.* Even the *terrible* ones. *Especially* those. Help me take it *back.*",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.witness_coverup", op = FlagOp.SetTrue }, new FlagClause { key = "sq.reconstruct_the_murder", op = FlagOp.SetTrue }, new FlagClause { key = "act4.deleted_witness", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "slowly", speaker = "The Witness",
                text = "*(The offer visibly loosens something in her — the terror was never only of the truth, but of facing it *alone.*)* Slowly. *(she breathes.)* With — with *you.* Beside me. *(she nods, fast, grateful.)* That's — yes. *That's* the thing I couldn't *name.* It's not that I *can't* face it. It's that I can't face it *alone*, in *one blow*, the whole *horror* landing at *once* with *no one* there to — to *catch* me, to *confirm* I *survived* the *remembering.* *(she presses her hands flat to steady them.)* A fragment at a time. The *night.* Then the *place.* Then the *two figures.* Then — *(she swallows)* — the *rest*, when I'm *ready*, and *not* before, and *never* without you *there.* *(she looks at you.)* You understand that a *witness* needs a *witness*, don't you. That the *un-seeing* can only be *undone* if there's *someone to see me see it again* — so that this time, the memory isn't a *lonely* terror in a *deleted* head, but a *shared* one, *held* between *two* people, where it *can't* be *taken* again. *(quietly, steadier than she's been.)* Let's reconstruct it. *Gently.* You hold the parts I can't carry yet. And when we reach the *face* — the *familiar*, *impossible* face — we'll reach it *together*, and *whatever* it turns out to be, I won't be *alone* with it. That's — that's the only way I can *bear* to *know.* Thank you for offering to *see with* me.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.witness_slowly", op = FlagOp.SetTrue }, new FlagClause { key = "sq.reconstruct_the_murder", op = FlagOp.SetTrue }, new FlagClause { key = "act1.mercy_remembered", op = FlagOp.SetTrue }, new FlagClause { key = "companion.naeve.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "live", speaker = "The Witness",
                text = "*(She is quiet a long moment, and the question — gentler than the others — reaches the part of her the terror was guarding.)* Can I *live* with not-knowing. *(slowly.)* *Truly* live. Not just *survive.* *(she looks at her hands.)* ...That's the question I've been *afraid* to ask, because I *suspect* the answer. *(quietly.)* The *hole* doesn't just *sit* there, stranger. It *pulls.* Every *quiet* moment, every *night*, my mind *drifts* to the *edge* of it and *probes* the *blank* and *recoils* and *drifts back* — like a *tongue* to a *missing tooth.* I am *not* at *peace.* I am *orbiting an absence.* *(she meets your eyes.)* So *can* I live with it? *(a long breath.)* No. I don't think I *can.* Not *really.* The *hollow safety* you named — it's *eating* me, *slowly*, from the *inside*, a little every *day*, and in *ten years* I'll be a *woman entirely built around a thing she won't look at*, and that's *not* a *life*, that's a *haunting* with a *pulse.* *(she straightens, frightened but clear.)* You didn't tell me to *dig* and you didn't tell me to *let it lie.* You asked if the *blank* was *survivable.* And asking it *honestly* — *(her voice firms)* — the answer is *no.* So I *have* to know. Not because knowing is *safe.* Because *not*-knowing is *killing me politely.* *(quietly.)* Stay with me while I find it. You asked the *one* question that *made the choice for me* — by making me *finally weigh* the *blank* instead of *hiding* in it.",
                autoNextNodeId = "close",
                onEnter = new[] { new FlagClause { key = "npc.witness_live", op = FlagOp.SetTrue }, new FlagClause { key = "sq.reconstruct_the_murder", op = FlagOp.SetTrue }, new FlagClause { key = "companion.garrow.approval", op = FlagOp.AddInt, amount = 4 } },
            });

            g.nodes.Add(new DialogueNode
            {
                id = "fragile", speaker = "The Witness",
                text = "*(She pulls back, wrapping her arms around herself, and the fear wins.)* No — no, don't — you're getting *close* to it, I can *feel* you *circling* the *hole* and it's making the *splinter* — *(she gasps, pressing her temple)* — *please.* Not *yet.* Maybe not *ever.* *(she shakes her head.)* I *know* you mean to *help*, but every *word* that gets *near* the *truth* makes the *pit* in my head *yawn wider*, and I am *not strong enough*, *today*, to fall *in.* *(she curls smaller.)* Let me keep the *blank* a *little* longer. The *hollow* is *killing* me, I *know* — but it's killing me *slowly*, and the *truth* might kill me *fast*, and *today*, *right now*, I want the *slow* one. *(she won't look at you.)* Come back when I'm — *stronger.* Or *don't.* The *hole* will *still be here.* The *hole*, I've learned, is *very patient.* *(and she sits against the blue-scarred wall, orbiting the absence in her own mind, not ready to look into the place where the murder used to be.)*",
                autoNextNodeId = "close",
            });

            g.nodes.Add(new DialogueNode
            {
                id = "close", speaker = "The Witness",
                text = "*(The deleted witness sits against the plague-scarred wall, holding a hole in her own memory where a murder used to be — a blank that was not chaos but *editing*, imposed by a hand that used the blue fire as an eraser — and whether she chose to reconstruct the terrible seeing or let the merciful gag stand, you carry away a cold splinter of your own: that the killer she half-remembers turned, and looked at her, with a face she knew and had never seen, out of its own time — and that somewhere in the loop you are walking, someone wears your face and has already learned to delete the ones who watch.)*",
            });

            NpcPlagueWitnessDialogue = g;
        }
    }
}
