// Combat analytics — Monte-Carlo the real engine and emit a standalone HTML report.
const fs=require("fs");
const { Dice, CharacterSheet, Ability, AttackResolver, CombatBalance, Sheet, Weapon } = require("./engine.js");

function hero(name,str,dex,ac,hp,primary,cast){
  const s=new CharacterSheet({displayName:name,baseArmorClass:ac,maxHitPoints:hp,level:5,
    classDef:{primaryAbility:primary,spellcastingAbility:cast||"wisdom"}});
  s.abilities.Set("strength",str);s.abilities.Set("dexterity",dex);s.abilities.Set("wisdom",14);return s;}
function dummy(ac,saveMod=0,hp=100000){const d=new CharacterSheet({baseArmorClass:ac,maxHitPoints:hp});
  d.abilities.Set("dexterity",10+saveMod*2);d.abilities.Set("wisdom",10+saveMod*2);return d;}

const heroes=[
  {u:hero("Sister Garrow",15,12,16,30,"strength","wisdom"), atk:Weapon("Maul","1d8")},
  {u:hero("Roen Alleywind",12,18,15,24,"dexterity","dexterity"), atk:Weapon("Twin Rapiers","1d8")},
  {u:hero("Varra",17,12,17,38,"strength","strength"), atk:Weapon("Greataxe","1d12")},
];
const ACs=[10,12,14,16,18], M=40000;

// per-attack hit% and DPR vs AC
function offense(att,ab,ac){
  let hits=0,dmg=0; for(let s=0;s<M;s++){Dice.Seed(s); const t=dummy(ac); const r=AttackResolver.Resolve(att,t,ab); if(r.hit)hits++; dmg+=r.damage;}
  return {hitPct:100*hits/M, dpr:dmg/M};
}
// time-to-kill: rounds for att's basic attack to drop a target of given AC/HP
function ttk(att,ab,ac,hp){
  let total=0,K=4000; for(let s=0;s<K;s++){Dice.Seed(s); const t=dummy(ac,0,hp); let rounds=0;
    while(t.IsAlive&&rounds<100){AttackResolver.Apply(t,AttackResolver.Resolve(att,t,ab));rounds++;} total+=rounds;}
  return total/K;
}

console.log("Hero offense (hit% / DPR) vs AC:");
const rows=heroes.map(h=>{
  const cells=ACs.map(ac=>({ac, ...offense(h.u,h.atk,ac)}));
  console.log(`  ${h.u.displayName.padEnd(16)} ` + cells.map(c=>`AC${c.ac}:${c.hitPct.toFixed(0)}%/${c.dpr.toFixed(1)}`).join("  "));
  return {name:h.u.displayName, atk:h.atk.abilityName, cells,
          ttkReturned:ttk(h.u,h.atk,12,15), ttkBoss:ttk(h.u,h.atk,15,40)};
});

// CombatBalance oracle (exact)
const p1=CombatBalance.WinRate(Sheet("Hero",16,16,28),Sheet("Brute",14,13,22),Weapon("Longsword","1d8"),Weapon("Club","1d6"),400);
const p2=CombatBalance.WinRate(Sheet("Duelist",18,14,20),Sheet("Brute",14,13,22),Weapon("Rapier","1d10"),Weapon("Club","1d6"),400);
const band=(p,lo,hi)=> p>=lo&&p<=hi?"OK":p>hi?"HIGH":"LOW";

// ---- emit HTML ----
const maxDpr=Math.max(...rows.flatMap(r=>r.cells.map(c=>c.dpr)));
const bar=(v,max,col,w=160)=>`<svg width="${w}" height="12"><rect width="${w}" height="12" fill="#1e1b27"/><rect width="${(w*v/max).toFixed(1)}" height="12" fill="${col}"/></svg>`;
const sec=rows.map(r=>`
  <h3>${r.name} — ${r.atk}</h3>
  <table><tr><th>vs AC</th><th>hit %</th><th>DPR</th><th></th></tr>
  ${r.cells.map(c=>`<tr><td>${c.ac}</td><td>${c.hitPct.toFixed(0)}%</td><td>${c.dpr.toFixed(2)}</td><td>${bar(c.dpr,maxDpr,"#c9a24b")}</td></tr>`).join("")}
  </table>
  <p class="ttk">Time-to-kill: a Returned (AC12, 15hp) in <b>${r.ttkReturned.toFixed(1)}</b> rounds · the Last Returned (AC15, 40hp) in <b>${r.ttkBoss.toFixed(1)}</b> rounds.</p>`).join("");
const out=`<!doctype html><meta charset=utf-8><title>Crown of Horns — Combat Analytics</title>
<style>body{background:#0c0b10;color:#d8d2c2;font:14px/1.6 Georgia,serif;max-width:760px;margin:24px auto;padding:0 18px}
h1{color:#e7c873}h2{color:#c9a24b;border-bottom:1px solid #2a2636;padding-bottom:4px;margin-top:28px}h3{color:#e7c873;margin:16px 0 4px}
table{border-collapse:collapse;width:100%;margin:4px 0}td,th{padding:3px 8px;text-align:left;border-bottom:1px solid #1e1b27;font-variant-numeric:tabular-nums}
th{color:#8a8198;font-weight:400;font-size:12px}.ttk{color:#9fc0e0;font-size:13px;margin:6px 0 0}
.flag-OK{color:#7fd0a0}.flag-HIGH{color:#e0a0a0}.flag-LOW{color:#9fc0e0}.muted{color:#6e6680;font-size:12px}</style>
<h1>Crown of Horns — Combat Analytics</h1>
<p class="muted">Monte-Carlo over the real engine (${M.toLocaleString()} samples/cell, .NET-faithful RNG). Generated by play/analyze.js.</p>
<h2>Hero offense</h2>${sec}
<h2>Balance oracle (CombatBalance.Report)</h2>
<table><tr><th>Matchup</th><th>Win %</th><th>Design band</th><th>Flag</th></tr>
<tr><td>Hero vs Brute</td><td>${p1}%</td><td>55–85%</td><td class="flag-${band(p1,55,85)}">${band(p1,55,85)}</td></tr>
<tr><td>Duelist vs Brute</td><td>${p2}%</td><td>35–70%</td><td class="flag-${band(p2,35,70)}">${band(p2,35,70)}</td></tr></table>
<p class="muted">A HIGH flag means the reference matchup is more lopsided than intended — surfaced straight from your own canary.</p>`;
fs.writeFileSync("balance_report.html",out);
console.log(`\nBalance oracle: Hero/Brute ${p1}% [${band(p1,55,85)}]  Duelist/Brute ${p2}% [${band(p2,35,70)}]`);
console.log("Wrote balance_report.html ("+out.length+" bytes).");
