#!/usr/bin/env python3
"""Build play/cast_gallery.html — every portrait + battle token, base64-embedded into
one standalone page (companions first, then NPCs, then the rogues' gallery of foes).
Re-run after regenerating art: python3 tools/make-cast-gallery.py"""
import base64, glob, os, html

ROOT = os.path.join(os.path.dirname(__file__), "..")
COMPANIONS = ["Sister Garrow","Roen Alleywind","Varra","Naeve","Ilfaeril","Maerin"]
PRINCIPALS = ["Aldric Morn","Mhaere","Sable","Tamsin","Quill","Wrenna Alleywind","Mother Cass",
              "High Lord Aelryth","Justiciar Veld","The Pale Cantor","The Returned"]

def b64(p):
    with open(p,"rb") as f: return base64.b64encode(f.read()).decode()

def card(name, img_path, sub=""):
    return (f'<div class="card"><img src="data:image/png;base64,{b64(img_path)}" alt="{html.escape(name)}">'
            f'<div class="nm">{html.escape(name)}</div>'
            + (f'<div class="sub">{html.escape(sub)}</div>' if sub else "") + "</div>")

def main():
    P = lambda n: os.path.join(ROOT, "Assets/Resources/Portraits", n + ".png")
    S = lambda n: os.path.join(ROOT, "Assets/Resources/Sprites", n + ".png")
    sections = []

    comp = []
    for n in COMPANIONS:
        if os.path.exists(P(n)): comp.append(card(n, P(n), "companion"))
    sections.append(("The Company", comp))

    npcs = []
    for n in PRINCIPALS:
        if os.path.exists(P(n)): npcs.append(card(n, P(n)))
    # any other portraits not already shown
    shown = set(COMPANIONS) | set(PRINCIPALS)
    for p in sorted(glob.glob(os.path.join(ROOT,"Assets/Resources/Portraits/*.png"))):
        n = os.path.basename(p)[:-4]
        if n not in shown and n not in ("NPC","Roen","Garrow"): npcs.append(card(n, p))
    sections.append(("Faces of the Gate & the Eras", npcs))

    foes = []
    skip = shown | {"Player","Ally","Neutral","Enemy","Garrow","Quill, the Broker"}
    for p in sorted(glob.glob(os.path.join(ROOT,"Assets/Resources/Sprites/*.png"))):
        n = os.path.basename(p)[:-4]
        if n not in skip: foes.append(card(n, p, "battle token"))
    sections.append(("The Rogues' Gallery (battle tokens)", foes))

    body = ""
    total = 0
    for title, cards in sections:
        total += len(cards)
        body += f'<h2>{title} <span class="ct">({len(cards)})</span></h2><div class="grid">' + "".join(cards) + "</div>"

    out = f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"><title>Crown of Horns — Cast Gallery</title>
<style>*{{box-sizing:border-box}}body{{margin:0;background:radial-gradient(1100px 600px at 50% -10%,#241f30,#0c0b10);
color:#d8d2c2;font:14px/1.5 Georgia,serif;padding:18px 26px}}
h1{{color:#e7c873;font-size:24px;margin:6px 0 2px}}.sub{{color:#8a8198;font-size:12px;font-style:italic}}
h2{{color:#c9a24b;font-size:14px;letter-spacing:1.5px;text-transform:uppercase;margin:26px 0 10px;border-bottom:1px solid #2a2636;padding-bottom:6px}}
.ct{{color:#6e6680;font-weight:400}}
.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(132px,1fr));gap:12px}}
.card{{background:linear-gradient(#16141d,#131119);border:1px solid #2a2636;border-radius:8px;padding:10px;text-align:center}}
.card:hover{{border-color:#c9a24b}}
.card img{{width:100%;image-rendering:auto;border-radius:5px;background:#0f0d15}}
.nm{{margin-top:7px;font-size:12.5px;color:#e7c873}}.sub{{font-size:10.5px;color:#8a8198}}
.foot{{margin-top:26px;color:#6e6680;font-size:11.5px}}</style></head><body>
<h1>Crown of Horns — Cast Gallery</h1>
<div class="sub">Every face in the game right now — {total} fully generated, era-tinted placeholder portraits &amp; battle tokens.
These are the exact files the engine loads by name (Resources/Portraits, Resources/Sprites); drop real art with the same names to replace any of them.</div>
{body}
<div class="foot">Generated by tools/make-cast-gallery.py from the committed art. All images procedurally generated — no external assets, no licenses.</div>
</body></html>"""
    dst = os.path.join(ROOT, "play", "cast_gallery.html")
    open(dst,"w").write(out)
    print(f"wrote play/cast_gallery.html ({len(out)//1024} KB, {total} cards)")

if __name__ == "__main__":
    main()
